### PR TITLE
Correctly implement hashCode for ImmArray and FrontStack

### LINKED ISSUE #1623: Contract keys are broken in Scenarios
I'm working on a DAML model for group chats:
https://gist.github.com/bame-da/7eb238eb87d8e20d6362948c22a50bed

The `MessageIndex` contract has a key, which goes wrong in two ways:

1. At the end of the `second_post` scenario, I have two active `MessageIndex` contracts with the same key
2. The reason we even *try* to create the second index is that the `lookupByKey` in `GetOrCreateIndex` doesn't work.

### PR DESCRIPTION
**Pull request by gerolf-da**
ImmArray and FrontStack violated the contract between equals and
hashCode. ImmArray had a wrong implementation of hashCode, and
FrontStack had no implementation at all.

Fixes #1623.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/FrontStack.scala [hunk 1]
```diff
@@ -109,6 +109,8 @@ final class FrontStack[+A] private (fq: FQ[A], len: Int) {
     case _ => false
   }
 
+  override def hashCode(): Int = toImmArray.hashCode()
+
```
Comment (remyhaemmerle-da) [inline daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/FrontStack.scala]: missing the same thing for BackStack

Comment (remyhaemmerle-da) [reply daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/FrontStack.scala]: We need a tests for that as well.

File: daml-lf/data/src/test/scala/com/digitalasset/daml/lf/data/ImmArrayTest.scala [hunk 2]
```diff
@@ -136,6 +136,16 @@ class ImmArrayTest extends FlatSpec with Matchers with Checkers {
     ImmArray[Int](1).relaxedSlice(0, -1) shouldBe ImmArray.empty[Int]
   }
 
+  it should "implement equals and hashCode correctly" in {
+    val long = ImmArray(1, 2, 3, 4)
+    val shortened = long.relaxedSlice(0, 2)
```
Comment (remyhaemmerle-da) [inline daml-lf/data/src/test/scala/com/digitalasset/daml/lf/data/ImmArrayTest.scala]:
```suggestion
    val shortened = long.relaxedSlice(1, 3)
```

File: daml-lf/data/src/test/scala/com/digitalasset/daml/lf/data/ImmArrayTest.scala [hunk 3]
```diff
@@ -136,6 +136,16 @@ class ImmArrayTest extends FlatSpec with Matchers with Checkers {
...
+
+    val short = ImmArray(1, 2)
```
Comment (remyhaemmerle-da) [inline daml-lf/data/src/test/scala/com/digitalasset/daml/lf/data/ImmArrayTest.scala]:
```suggestion
    val short = ImmArray(2, 3)
```

File: daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/FrontStack.scala (hunk 1 above)
Comment (gerolf-da) [reply daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/FrontStack.scala]: Yes, there are no tests at all yet for FrontStack and BackStack, at least as far as I can tell.

Comment (gerolf-da) [reply daml-lf/data/src/main/scala/com/digitalasset/daml/lf/data/FrontStack.scala]: @remyhaemmerle-da: if you want to add tests, please feel free to take over the PR.
