### PR TITLE
Fix race condition in the initialization of scenario ctx roots

### LINKED ISSUE #1306: Race condition in setting up scenario contexts
There is a race condition somewhere in setting up the scenario contexts which has caused issues on CI and locally. We should investigate and fix it.

### PR DESCRIPTION
**Pull request by cocreature**
Fixes #1306

The problem was caused by the following steps:

1. We first call setFilesOfInterest. However that does not block until
 ofInterestRule finishes and subsequent calls to shakeRun will kill
 the current run so we never reach the point where the scenario
 context roots are updated.

2. We then call runScenarios before ever setting up the context roots
and throw an exception.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs [hunk 1]
```diff
@@ -251,13 +250,36 @@ runScenariosRule =
...
+        Env{..} <- getServiceEnv
+        DamlEnv{..} <- getDamlServiceEnv
+        filesOfInterest <- liftIO $ readVar envOfInterestVar
+        openVRs <- liftIO $ readVar envOpenVirtualResources
+        let files = Set.toList (filesOfInterest `Set.union` Set.map vrScenarioFile openVRs)
+        deps <- forP files $ \file -> do
+            transitiveDeps <- maybe [] transitiveModuleDeps <$> use GetDependencies file
+            pure $ Map.fromList [ (f, file) | f <- transitiveDeps ]
+        -- We want to ensure that files of interest always map to themselves even if there are dependencies
+        -- between files of interest so we union them separately.
```
Comment (hurryabit) [inline daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs]:
```suggestion
        -- between files of interest so we union them separately. (`Map.union` is left-biased.)
```

File: daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs [hunk 2]
```diff
@@ -258,6 +258,29 @@ encodeModule lfVersion m =
...
+        DamlEnv{..} <- getDamlServiceEnv
+        filesOfInterest <- liftIO $ readVar envOfInterestVar
+        openVRs <- liftIO $ readVar envOpenVirtualResources
+        let files = Set.toList (filesOfInterest `Set.union` Set.map vrScenarioFile openVRs)
+        deps <- forP files $ \file -> do
+            transitiveDeps <- maybe [] transitiveModuleDeps <$> use GetDependencies file
+            pure $ Map.fromList [ (f, file) | f <- transitiveDeps ]
+        -- We want to ensure that files of interest always map to themselves even if there are dependencies
+        -- between files of interest so we union them separately. (`Map.union` is left-biased.)
+        pure $ Map.fromList [(f,f) | f <- files] `Map.union` Map.unions deps
```
Comment (neil-da) [inline daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs]: Data.Tuple.Extra.dupe

File: daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs [hunk 3]
```diff
@@ -258,6 +258,29 @@ encodeModule lfVersion m =
...
+
+getScenarioRootRule :: Rules ()
+getScenarioRootRule =
+    defineEarlyCutoff $ \GetScenarioRoot file -> do
+        ctxRoots <- use_ GetScenarioRoots ""
+        case Map.lookup file ctxRoots of
+            Nothing -> liftIO $ throwIO $ ScenarioRootException file
```
Comment (neil-da) [inline daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs]: If this is an internal exception just call `fail` or similar.

File: compiler/haskell-ide-core/src/Development/IDE/State/RuleTypes.hs [hunk 4]
```diff
@@ -36,6 +37,17 @@ import           Development.IDE.Types.SpanInfo
 -- | Kick off things
 type instance RuleResult OfInterest = ()
 
+-- ^ A map from a file A to a file B whose scenario context should be
+-- used for executing scenarios in A. We use this when running the scenarios
+-- in transitive dependencies of the files of interest so that we only need
+-- one scenario context per file of interest.
+type instance RuleResult GetScenarioRoots = Map FilePath FilePath
```
Comment (neil-da) [inline compiler/haskell-ide-core/src/Development/IDE/State/RuleTypes.hs]: Move out of haskell-ide-core.

File: daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs (hunk 2 above)
Comment (cocreature) [reply daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs]: :+1:

File: daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs (hunk 3 above)
Comment (cocreature) [reply daml-foundations/daml-ghc/ide/src/Development/IDE/State/Rules/Daml.hs]: Changed to `fail`

File: compiler/haskell-ide-core/src/Development/IDE/State/RuleTypes.hs (hunk 4 above)
Comment (cocreature) [reply compiler/haskell-ide-core/src/Development/IDE/State/RuleTypes.hs]: Moved to the `.Daml` version of this module.
