### PR TITLE
Properly mangle/unmangle names in the scenario service

### LINKED ISSUE #5593: (0.13.54) Certain scenario names seem to crash scenario service
I've found that scenario names containing an apostrophe in the middle will sometimes consistently compile and cause scenario service backend errors like the following:

```
2020-04-17 06:45:00.59 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: Apr 17, 2020 4:45:00 PM io.grpc.internal.SerializingExecutor run

2020-04-17 06:45:00.59 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@47849443

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: com.digitalasset.daml.lf.archive.Reader$ParseError: string "se't_test" does not match regex "[A-Za-z\$_][A-Za-z0-9\$_]*"

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at com.digitalasset.daml.lf.scenario.Context$.$anonfun$assert$1(Context.scala:42)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at scala.util.Either.fold(Either.scala:189)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at com.digitalasset.daml.lf.scenario.Context$.com$digitalasset$daml$lf$scenario$Context$$assert(Context.scala:42)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at com.digitalasset.daml.lf.scenario.Context.interpretScenario(Context.scala:172)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at com.digitalasset.daml.lf.scenario.ScenarioService.$anonfun$runScenario$1(ScenarioServiceMain.scala:86)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at scala.Option.flatMap(Option.scala:171)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at com.digitalasset.daml.lf.scenario.ScenarioService.runScenario(ScenarioServiceMain.scala:74)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at com.digitalasset.daml.lf.scenario.api.v1.ScenarioServiceGrpc$MethodHandlers.invoke(ScenarioServiceGrpc.java:643)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:808)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

2020-04-17 06:45:00.60 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR:        at java.lang.Thread.run(Thread.java:748)

2020-04-17 06:45:00.61 [ERROR]  [test ScenarioService]  [] 
SCENARIO SERVICE STDERR: 
File:     src/Test/My/Module.daml
Hidden:   no
Range:    62:0-62:9
Source:   Scenario
Severity: DsError
Message: 
  "Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusUnknown
  (StatusDetails {unStatusDetails = \"\"})))"
```

In this case, `se't_test` was the name of the problematic scenario.

### PR DESCRIPTION
**Pull request by cocreature**
Previously, we just passed in whatever we had in DAML land which broke
the scenario service as soon as a name needed mangling. This PR fixes
mangling when passing identifiers to the scenario service and
unmangles them again when pretty printing.

fixes #5593

changelog_begin

- [DAML Studio] Fix a bug where scenarios with names that are mangled
  in DAML-LF resulted in a crash in the scenario service.

changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/scenario-service/client/src/DA/Daml/LF/PrettyScenario.hs [hunk 1]
```diff
@@ -46,6 +47,23 @@ type M = ExceptT Error (Reader (MS.Map NodeId Node, LF.World))
...
+unmangleModuleName t = LF.ModuleName (map unmangle $ T.splitOn "." t)
+
+unmangle :: T.Text -> T.Text
+unmangle s = case unmangleIdentifier s of
+    Left err -> error err
+    Right (UnmangledIdentifier s) -> s
+
+{-# COMPLETE UnmangledQualifiedName #-}
+pattern UnmangledQualifiedName :: LF.ModuleName -> T.Text -> TL.Text
+pattern UnmangledQualifiedName mod def <- (unmangleQualifiedName . TL.toStrict -> (mod, def))
```
Comment (associahedron) [inline compiler/scenario-service/client/src/DA/Daml/LF/PrettyScenario.hs:65]: Throwing run time errors in patterns makes me a bit anxious...

Comment (cocreature) [reply compiler/scenario-service/client/src/DA/Daml/LF/PrettyScenario.hs:65]: Yeah it’s not great but if this actually fails something is broken so I’d rather have it blow up than fall back into some other code path.
