### PR TITLE
Keeping loaded packages after reset

### LINKED ISSUE #1979: Sandbox 100.13.10 reloads the package when invoking the`Reset` service
**Steps to reproduce**
1. Set up a system monitor to watch CPU and RAM
2. start sandbox (`java -jar sandbox-100.13.10.jar --port 8080 my.dar`) with a dar containing a large package dalf (ours is 78MB).
3. Observe that sandbox loads the dar, visible in a CPU spike and large RAM footprint (from 0.13.10 sandbox seems to eagerly load packages, which is a good idea :+1: . Intended? )
4. reset sandbox using `grpcurl`, like this:
```
 grpcurl -d "$(grpcurl -plaintext localhost:8080 com.digitalasset.ledger.api.v1.LedgerIdentityService/GetLedgerIdentity)" -plaintext localhost:8080 com.digitalasset.ledger.api.v1.testing.ResetService/Reset
```
5. Observe that sandbox again produces a CPU spike, and RAM allocation might increase again)

**What's your preferred solution?**
Sandbox should not "reboot" but simply use a new ledger, and should be ready to use within milliseconds after a reset. This used to be the case.

The reset service is essential for proper feature and integration testing. Changing sandbox behaviour may cause performance issues (it did in the past). It would be a good idea to monitor its performance.

**About your system**
 - OS: Linux
 - SDK version 0.13.10

### PR DESCRIPTION
**Pull request by gabor-aranyossy**
fixes #1979

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/index/StandaloneIndexServer.scala [hunk 1]
```diff
@@ -119,16 +119,23 @@ class StandaloneIndexServer(
     }
   }
 
+  private def loadDamlPackages(): InMemoryPackageStore = {
+    // TODO is it sensible to have all the initial packages to be known since the epoch?
```
Comment (stefanobaghino-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/index/StandaloneIndexServer.scala]: It looks like the previous logic was to set `Instant.now` as the `knownSince` time. It probably makes sense to keep it as is.

Comment (rautenrieth-da) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/index/StandaloneIndexServer.scala]: Interesting. The sandbox application always used `EPOCH` (see https://github.com/digital-asset/daml/pull/2091/files#diff-9ee24205d1c2b37348e86cc67c097e36L173), while the standalone index server used `Instant.now` before.

Why do we need to load any packages at all here? The read service contains ledger entries for package uploads, the package store should be updated from these entries.

If the initial packages are somehow packages that the ledger needs, but does not expose through the read service, then these should be uploaded at `EPOCH`, to make sure they predate any other ledger entries.

Comment (gabor-aranyossy) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/index/StandaloneIndexServer.scala]: it might be just a temporary solution. Let me change it to `Instant.now` so we can merge this.
