### PR TITLE
damldocs: Rewrite class method extraction and fix handling of default methods.

### LINKED ISSUE #2659: docs generation generates duplicate references for `default` methods of type classes
If type classes have a `default` method implementation, the doc generation generates a duplicate function reference. Here's the failing example: 

```
class Convertible a b where
  convert : a -> b
  default convert : (Generic a repA, Generic b repB, GenConvertible repA repB) => a -> b
  convert = to . cv . from
```

### PR DESCRIPTION
**Pull request by associahedron**
Fixes #2659 and some other problems with the handling of class methods.

As part of this, I changed how typeclass method docs are stored, and rewrote the extraction of class methods to actually keep track of the type signature and docs of a generic default method. (Previously it only fetched the type signature and docs for the exported typeclass method! And also caused duplicate anchors.)

I added a test case for generic default methods.

### CODE REVIEW

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs [hunk 1]
```diff
@@ -53,9 +53,10 @@ applyHide = concatMap onModule
         -- as that would be a security risk
         onTemplate x = [x | not $ isHide $ td_descr x]
         onFunction x = [x | not $ isHide $ fct_descr x]
+        onMethod x = [x | not $ isHide $ cm_descr x]
         onClass x
             | isHide $ cl_descr x = []
-            | ClassDoc {..} <- x = [x { cl_functions = concatMap onFunction cl_functions }]
+            | ClassDoc {..} <- x = [x { cl_methods = concatMap onMethod cl_methods }]
```
Comment (cocreature) [inline compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs]: It would be nice to move renaming to a separate PR in the future. This is already a very large diff.

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs [hunk 2]
```diff
@@ -298,53 +267,91 @@ getFctDocs ctx@DocCtx{..} cl_nameM (DeclData decl docs) = do
...
-      [ getFctDocs ctx (Just cl_name) (DeclData (L dloc (SigD noExt (ClassOpSig p b [L loc name] n))) (MS.lookup name subdocs))
-      | L loc name <- names
-      ]
-    f _ _ = []
+    -- All documentation of class members is stored in tcdDocs.
+    -- To associate the docs with the correct member, we convert all members
+    -- and docs to declarations, sort them by their location
+    -- and then use collectDocs.
+    -- This is the equivalent of Haddock’s Haddock.Interface.Create.classDecls.
+    subDecls :: [(LHsDecl GhcPs, Maybe DocText)]
```
Comment (cocreature) [inline compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs]: Note to myself and other reviewers: This corresponds to most of what `memberDocs` did before. What changed is that now we postprocess this with `getMethodDocs`.

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs [hunk 3]
```diff
@@ -298,53 +267,91 @@ getFctDocs ctx@DocCtx{..} cl_nameM (DeclData decl docs) = do
...
+            flip mapMaybe rdrNamesL $ \rdrNameL -> do
+                let cm_name = Fieldname . packRdrName . unLoc $ rdrNameL
+                    cm_anchor = guard (not cm_isDefault) >>
+                        Just (functionAnchor dc_modname cm_name)
+                (id, dmInfoM) <- MS.lookup cm_name opMap
+                ty <- case (cm_isDefault, dmInfoM) of
+                    (True, Nothing) ->
+                        error "getMethodDocs: expected default method to have associated default method info"
+                    (True, Just (_, GenericDM ty)) -> Just ty
+                    _ -> Just (idType id)
```
Comment (cocreature) [inline compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs]: Can it ever happen that we get `(False, Just …)`? If that should also be an error I would suggest to change this to only case on `dmInfoM` and instead have something like `when (cm_isDefault /= isJust dmInfoM) $ error …`.

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Render/Hoogle.hs [hunk 4]
```diff
@@ -101,20 +101,21 @@ cls2hoogle ClassDoc{..} = concat
                  ++ maybe [] ((:["=>"]) . type2hoogle) cl_super
                  ++ wrapOp (unTypename cl_name) : cl_args
       , "" ]
-    , concatMap (fct2hoogle . addToContext) cl_functions
+    , concatMap classMethod2hoogle cl_methods
+    ]
+
+classMethod2hoogle :: ClassMethodDoc -> [T.Text]
+classMethod2hoogle ClassMethodDoc{..} | cm_isDefault = [] -- hide default methods from hoogle search
+classMethod2hoogle ClassMethodDoc{..} = concat
```
Comment (cocreature) [inline compiler/damlc/daml-doc/src/DA/Daml/Doc/Render/Hoogle.hs]: This case is almost identical to `fct2hoogle`. Can we share the code here?

File: compiler/damlc/tests/daml-test-files/DefaultMethods.daml [hunk 5]
```diff
@@ -31,3 +31,11 @@ class Id a where
   id = \x -> x
 
 instance Id Int where
+
+-- | Default implementation with a separate type signature for the default method.
+class MyShow t where
```
Comment (cocreature) [inline compiler/damlc/tests/daml-test-files/DefaultMethods.daml]: I believe this PR also fixes the `(+), (-) : a -> a -> a` case right? If so, can we get a test for that as well?

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs (hunk 3 above)
Comment (associahedron) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs]: `(False, Just ...)` is expected whenever we're processing a typeclass method's original signature, but there also exists a default implementation. It's not an error. The ``

Comment (cocreature) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs]: Ah I see, in that case maybe spell that out in a comment? :)

File: compiler/damlc/tests/daml-test-files/DefaultMethods.daml (hunk 5 above)
Comment (associahedron) [reply compiler/damlc/tests/daml-test-files/DefaultMethods.daml]: I think that was already fixed, but a test case can't hurt :)

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs (hunk 1 above)
Comment (associahedron) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs]: They have different types that contain different data, it's not just renaming.

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs (hunk 3 above)
Comment (associahedron) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Extract.hs]: 👍

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs (hunk 1 above)
Comment (cocreature) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs]: Fair enough.

Comment (associahedron) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs]: Apologies for the large PR. It is somewhat atomic, however.

Comment (cocreature) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Annotate.hs]: No worries, some PRs aren’t easily splittable and that’s totally fine :slightly_smiling_face:

File: compiler/damlc/daml-doc/src/DA/Daml/Doc/Render/Hoogle.hs (hunk 4 above)
Comment (associahedron) [reply compiler/damlc/daml-doc/src/DA/Daml/Doc/Render/Hoogle.hs]: Probably going to try and refactor the Hoogle renderer in a future PR.
