### PR TITLE
Idempotent package uploads

### LINKED ISSUE #2130: Uploading more than one package to Sandbox fails with Postgres backend
Attempting to upload more than one package to the Sandbox (provided all packages have been built with the same version of the SDK) fails with this error in the _Postgres_ logs:

```
2019-07-12 15:44:05.609 UTC [67] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2019-07-12 15:44:05.609 UTC [67] DETAIL:  Key (package_id)=(a5264aaa710fe11a94ac80d71efc1083997ed09f39047888ae1c1d90cc4a549a) already exists.
2019-07-12 15:44:05.609 UTC [67] STATEMENT:  insert into packages(package_id, upload_id, source_description, size, known_since, ledger_offset, package)
	select $1, $2, $3, $4, $5, ledger_end, $6
	from parameters
```

Sandbox logs nothing.

The faulty code is here: https://github.com/digital-asset/daml/blob/master/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala#L1062

It rolls back the entire transaction on the event of any key conflict, which prevents the other DALFs in the same archive from being loaded. Because every DAR contains a copy of the stdlib, this effectively means that only one DAR can be uploaded.

### PR DESCRIPTION
**Pull request by da-tanabe**
Makes package uploads idempotent.

Fixes #2130.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala [hunk 1]
```diff
@@ -1073,15 +1074,15 @@ private class PostgresLedgerDao(
...
-              SQL_INSERT_PACKAGE,
-              namedPackageParams
-            )
-            PersistenceResponse.Ok
-          }.recover {
-            case NonFatal(e) if e.getMessage.contains("duplicate key") =>
-              conn.rollback()
+            import scala.math.min
+            val changeCount = executeBatchSql(SQL_INSERT_PACKAGE, namedPackageParams)
+              .map(min(0, _))
```
[the remark this answers is not in the document]
Comment (stefanobaghino-da) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala]: I believe the failing test in CI is because of this. You can run
```bash
bazel test //ledger/sandbox:sandbox-scala-tests_test_suite_src_test_suite_scala_com_digitalasset_platform_sandbox_stores_ledger_sql_PostgresDaoSpec.scala
```
to test locally.

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala [hunk 2]
```diff
@@ -1073,15 +1074,15 @@ private class PostgresLedgerDao(
                     "package" -> p._1.toByteArray
                 )
               )
-            executeBatchSql(
-              SQL_INSERT_PACKAGE,
-              namedPackageParams
-            )
-            PersistenceResponse.Ok
-          }.recover {
-            case NonFatal(e) if e.getMessage.contains("duplicate key") =>
```
Comment (stefanobaghino-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala]: I really didn't like this, the whole logic relies on the error message as a _stable API_. Good riddance!

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala [hunk 3]
```diff
@@ -1073,15 +1074,15 @@ private class PostgresLedgerDao(
...
-              conn.rollback()
+            import scala.math.min
+            val changeCount = executeBatchSql(SQL_INSERT_PACKAGE, namedPackageParams)
+              .map(min(0, _))
+              .sum
+            if (changeCount == packages.length) {
+              PersistenceResponse.Ok
```
Comment (stefanobaghino-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala]: I would suggest to change the return type of this to make sure the consumer can understand better. Ideally it would be `Map[PackageId, PersistenceResponse]` but I'm not sure it would be possible to get this information esaily. I guess `Map[PersistenceResponse, Int]` will do.

File: ledger/UNRELEASED.md [hunk 4]
```diff
@@ -21,4 +21,6 @@ the release script will make a proper link to JIRA.
 
 ### Fixed
 
+Sandbox: Fix a bug preventing more than one package to Sandbox with a Postgres backend (see #2130).
```
[the remark this answers is not in the document]
Comment (stefanobaghino-da) [reply ledger/UNRELEASED.md]: This file was removed by #2140.

[the remark this answers is not in the document]
Comment (da-tanabe) [reply ledger/UNRELEASED.md]: Done.

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala [hunk 5]
```diff
@@ -349,13 +349,11 @@ private class SqlLedger(
...
-          UploadPackagesResult.Ok
-        case PersistenceResponse.Duplicate =>
-          // Note: package upload is idempotent, apart from the fact that we only keep
-          // the knownSince and sourceDescription of the first upload.
-          UploadPackagesResult.Ok
+      .map { _ =>
+        // Note: We discard any information about duplicates vs. non-duplicates here,
+        // as package upload is idempotent, apart from the fact that we only keep
+        // the knownSince and sourceDescription of the first upload.
+        UploadPackagesResult.Ok
```
Comment (rautenrieth-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala]: This makes the code less resistant against adding a new case to `PersistenceResponse` (e.g., `PersistenceResponse.Error`). I don't have a strong opinion, but my personal preference would be listing both cases explicitly.

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala [hunk 6]
```diff
@@ -1073,15 +1074,18 @@ private class PostgresLedgerDao(
...
-              namedPackageParams
-            )
-            PersistenceResponse.Ok
-          }.recover {
-            case NonFatal(e) if e.getMessage.contains("duplicate key") =>
-              conn.rollback()
-              PersistenceResponse.Duplicate
+            import scala.math.max
+            val changeCount: Int = executeBatchSql(SQL_INSERT_PACKAGE, namedPackageParams)
+              .map(max(0, _))
```
Comment (rautenrieth-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala]: Why the `max(0, _)`? I can't find nice docs for `BatchSql`, but it looks like it should return the number of changed rows for each batch element (which should be exactly 0 or 1). Does it return something like -1 in some cases?

Comment (da-tanabe) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/PostgresLedgerDao.scala]: Under the hood, anorm calls this method: https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#executeBatch()

It returns either a nonnegative number or one of two error codes, both of which are negative values. (One of those cases is `SUCCESS_NO_INFO`, so not sure what the right behavior is for this case… :-/ )

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala (hunk 5 above)
Comment (stefanobaghino-da) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala]: It's not strictly necessary right now, but since it's information that it's available to the data access object I see no reason to discard it upstream either. Furthermore, it would be very difficult to understand in which case to return `Ok` and in which return `Duplicate` if the end result is mixed. Do you think we should add the concept of `Duplicate` to this layer as well?

**Comment by stefanobaghino-da** [comment]
Took over @da-tanabe's work to add tests and some logging, ready for review.

**Comment by stefanobaghino-da** [comment]
Fun fact: by working on someone else's PR you can approve your own contribution.

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala [hunk 7]
```diff
@@ -349,13 +349,17 @@ private class SqlLedger(
...
-          UploadPackagesResult.Ok
-        case PersistenceResponse.Duplicate =>
-          // Note: package upload is idempotent, apart from the fact that we only keep
-          // the knownSince and sourceDescription of the first upload.
-          UploadPackagesResult.Ok
+      .map { result =>
+        result.get(PersistenceResponse.Ok).fold(logger.info(s"No package uploaded")) { uploaded =>
+          logger.info(s"Successfully uploaded $uploaded packages")
+        }
+        for (duplicates <- result.get(PersistenceResponse.Ok)) {
```
Comment (gerolf-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala]:
```suggestion
        for (duplicates <- result.get(PersistenceResponse.Duplicate)) {
```

Comment (stefanobaghino-da) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala]: Ugh, thanks, fixed.
