### PR TITLE
Fix hashing of keys in the new contract store

### LINKED ISSUE #5680: Fix hashing in the new contract store
The new contract store currently uses `KeyHasher` to compute key hashes.

This, however, is now deprecated and the contract store should be fixed to use the `hash` member defined on `GlobalKey` instead.

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Use `GlobalKey.hash` instead of `KeyHasher.hashKey`

Fixes #5680

### TODO

- [x] Test data migration https://github.com/stefanobaghino-da/test-5680-data-migration

changelog_begin
changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
[First test](https://github.com/stefanobaghino-da/test-5680-data-migration/tree/fc6d067007e3b786bd29597913c3376abfb7278b) fails after migration with a
```
Error: User abort: Submit failed with code 3: Reason: [InvalidLookup(com.daml.lf.transaction.Node$GlobalKey@47dd864b,None,Some(AbsoluteContractId(#0000000000000005:0)))]
```
Investigating.

**Comment by stefanobaghino-da** [comment]
I was setting the fields in the wrong order. :facepalm: 

I have a very unpleasant relationship with weak typing.

**Comment by stefanobaghino-da** [comment]
Better examination made me notice that the migration appears to not have run at all, as it's not in `flyway_schema_history`. Investigating.

File: ledger/sandbox/src/main/scala/db/migration/postgres/V28_Fix_key_hashes.scala [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        val contractId = keysRows.getString("contract_id")
+        val rawTemplateId = keysRows.getString("template_id")
+        val templateId = Ref.Identifier.assertFromString(rawTemplateId)
+        val rawKeyValue = keysRows.getBinaryStream("create_key_value")
+        val keyValue = ValueSerializer.deserializeValue(rawKeyValue)
+        val key = GlobalKey.assertBuild(templateId, keyValue.value)
+        val hashBytes = key.hash.bytes.toInputStream
+
+        fixHash.setString(1, contractId)
+        fixHash.setBinaryStream(2, hashBytes)
```
Comment (stefanobaghino-da) [inline ledger/sandbox/src/main/scala/db/migration/postgres/V28_Fix_key_hashes.scala:40]:
```suggestion
        fixHash.setBinaryStream(1, hashBytes)
        fixHash.setString(2, contractId)
```

**Comment by stefanobaghino-da** [comment]
> Better examination made me notice that the migration appears to not have run at all, as it's not in `flyway_schema_history`. Investigating.

Wrong naming, adding a self-review and fixing.

File: ledger/sandbox/src/main/scala/db/migration/postgres/V28_Fix_key_hashes.scala [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+// SPDX-License-Identifier: Apache-2.0
+
+package db.migration.postgres
+
+import com.daml.lf.data.Ref
+import com.daml.lf.transaction.Node.GlobalKey
+import com.daml.platform.store.serialization.ValueSerializer
+import org.flywaydb.core.api.migration.{BaseJavaMigration, Context}
+
+final class V28_Fix_key_hashes extends BaseJavaMigration {
```
Comment (stefanobaghino-da) [inline ledger/sandbox/src/main/scala/db/migration/postgres/V28_Fix_key_hashes.scala:11]:
```suggestion
final class V28__Fix_key_hashes extends BaseJavaMigration {
```

**Comment by stefanobaghino-da** [comment]
The same failure occurs, investigating.

**Comment by stefanobaghino-da** [comment]
A very silly `not` in the wrong place was making the tests fail. Addressed in https://github.com/digital-asset/daml/pull/5681/commits/5fa9427e1eb09d65fb0553cab0f80ef0ce7e112c.
