### PR TITLE
LF: Make exceptions in choice's controller/obervser uncatchable

### LINKED ISSUE #13099: Catchability of signatories, observers & controllers
I don’t think any of these can be catchable since we don’t inser ta transaction node meaning we won’t divulge them. However, somewhat unclear what actually happens atm so we should investigate in partiuclar for cnotrollers because those can fail without a mailious submitter.

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
fixes #13099

No performance impact, measured.

==> ref.log <==
CollectAuthority.bench  CollectAuthority.dar  CollectAuthority:test  avgt  200  11.124 ? 0.030  ms/op
==> tested.log <==
CollectAuthority.bench  CollectAuthority.dar  CollectAuthority:test  avgt  200  11.152 ? 0.025  ms/op

==> replay.ref.log <==
ReplayBenchmark.bench  ???                           0  kv-3370.export  avgt  200  538.486 ? 3.757  us/op
==> replay.tested.log <==
ReplayBenchmark.bench  ???                           0  kv-3370.export  avgt  200  536.989 ? 4.201  us/op

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by remyhaemmerle-da** [comment]
I am running benchmarks. I will post the results once they are done.

File: daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ClosureConversion.scala [hunk 1]
```diff
@@ -156,6 +156,8 @@ private[speedy] object ClosureConversion {
       final case object ScopeExercise extends Cont
 
       final case class LabelClosure(label: Profile.Label) extends Cont
+
+      final case class PreventCatch() extends Cont
```
Comment (nickchapman-da) [inline daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ClosureConversion.scala:160]: why not a case object?

File: daml-lf/interpreter/src/test/scala/com/digitalasset/daml/lf/speedy/RollbackTest.scala [hunk 2]
```diff
@@ -65,10 +66,6 @@ class RollbackTest extends AnyWordSpec with Matchers with TableDrivenPropertyChe
                 u: Unit <- throw @(Update Unit) @M:MyException (M:MyException {message = "oops"});
                 x2: ContractId M:T1 <- create @M:T1 M:T1 { party = M:T1 {party} record, info = 500 }
               in upure @Unit ();
-          choice ChControllerThrow (self) (i : Unit) : Unit,
-            controllers (throw @(List Party) @M:MyException (M:MyException {message = "oops"}))
-            to
-              upure @Unit ();
```
Comment (remyhaemmerle-da) [inline daml-lf/interpreter/src/test/scala/com/digitalasset/daml/lf/speedy/RollbackTest.scala:71]: @nickchapman-da I drop the test, since exception thrown from the controllers cannot be caught any more. 
Is it fine, or should I change the test ?

File: daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/Compiler.scala [hunk 3]
```diff
@@ -446,9 +447,9 @@ private[lf] final class Compiler(
         )(
           env.toSEVar(choiceArgPos),
           env.toSEVar(cidPos),
-          translateExp(env, choice.controllers),
+          s.SEPreventCatch(translateExp(env, choice.controllers)),
           choice.choiceObservers match {
-            case Some(observers) => translateExp(env, observers)
+            case Some(observers) => s.SEPreventCatch(translateExp(env, observers))
             case None => s.SEValue.EmptyList
```
Comment (sofiafaro-da) [inline daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/Compiler.scala:453]: We also need this change in `translateInterfaceChoiceBody`

**Review by sofiafaro-da — APPROVED** [review]
LGTM, thank you!

File: daml-lf/transaction/src/main/scala/com/daml/lf/Error.scala [hunk 4]
```diff
@@ -21,6 +21,13 @@ object Error {
   /** Unhandled exceptions */
   final case class UnhandledException(exceptionType: Ast.Type, value: Value) extends Error
 
+  /** Uncatchable exceptions */
```
[the remark this answers is not in the document]
Comment (remyhaemmerle-da) [reply daml-lf/transaction/src/main/scala/com/daml/lf/Error.scala]: I drop `UncatchableException` and use `UnhandledException` as it is done in `PartialTransaction.rollbackTry` when throwing exception from old LF. 
If we want to be more precise, we could change that in the future.

File: daml-lf/interpreter/src/test/scala/com/digitalasset/daml/lf/speedy/ExceptionTest.scala [hunk 5]
```diff
@@ -467,11 +468,73 @@ class ExceptionTest extends AnyWordSpec with Matchers with TableDrivenPropertyCh
...
+         template (this: T) = {
+           precondition True;
+           signatories Cons @Party [M:T {party} this] Nil @Party;
+           observers Nil @Party;
+           agreement "Agreement";
+             choice BodyCrash (self) (u: Unit) : Unit, 
+                 controllers Cons @Party [M:T {party} this] Nil @Party,
+                 observers Nil @Party
+               to upure @Unit (throw @Unit @M:E (M:E {}));
+             choice SignatoriesCrash (self) (u: Unit) : Unit,
```
[the remark this answers is not in the document]
Comment (remyhaemmerle-da) [reply daml-lf/interpreter/src/test/scala/com/digitalasset/daml/lf/speedy/ExceptionTest.scala]: good catch.

File: daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/Compiler.scala (hunk 3 above)
Comment (remyhaemmerle-da) [reply daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/Compiler.scala:453]: test added.
