### PR TITLE
interpretation Error ValueNesting should not be in Dev

### LINKED ISSUE #17237: interpretation Error ValueNesting should not be in Dev
`com.daml.lf.interpretation.Error.Dev.Limit.ValueNesting` was wrongly classified as Dev Error in #16859

If should be moved in `com.daml.lf.interpretation.Error`.

### PR DESCRIPTION
**Pull request by carlpulley-da**
Fixes #17237

- [x] Prepare daml changes and capture snapshot
- [x] Prepare Canton changes with daml snapshot and capture snapshot - https://github.com/DACH-NY/canton/pull/14412
- [ ] Update daml with Canton snapshot and merge (for a future PR)
- [ ] Update Canton with daml snapshot and merge (for https://github.com/DACH-NY/canton/pull/14412)

### CODE REVIEW

File: daml-lf/transaction/src/main/scala/com/daml/lf/Error.scala [hunk 1]
```diff
@@ -146,6 +146,8 @@ object Error {
 
   final case class ContractIdInContractKey(key: Value) extends Error
 
+  final case class ValueNesting(location: String, limit: Int) extends Error
```
Comment (carlpulley-da) [inline daml-lf/transaction/src/main/scala/com/daml/lf/Error.scala:149]: Adding the `location` param from the `Dev` wrapping case class - this will likely be useful for tooling and error reporting?

File: daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/v2/ledgerinteraction/SubmitError.scala [hunk 2]
```diff
@@ -361,6 +361,15 @@ object SubmitError {
       )
   }
 
+  final case class ValueNesting(limit: Int) extends SubmitError {
+    override def toDamlSubmitError(env: Env): SValue =
+      SubmitErrorConverters(env).damlScriptError(
+        "ValueNesting",
+        18,
```
Comment (carlpulley-da) [inline daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/v2/ledgerinteraction/SubmitError.scala:368]: Not 100% that incrementing and bumping rank numbers is the correct way to do this?

File: daml-lf/transaction/src/main/scala/com/daml/lf/Error.scala (hunk 1 above)
Comment (remyhaemmerle-da) [reply daml-lf/transaction/src/main/scala/com/daml/lf/Error.scala:149]: cf above.

File: daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/v2/ledgerinteraction/SubmitError.scala (hunk 2 above)
Comment (remyhaemmerle-da) [reply daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/v2/ledgerinteraction/SubmitError.scala:368]: @samuel-williams-da ?

**Review by remyhaemmerle-da — APPROVED** [review]
LGTM, but let wait from @samuel-williams-da 's feeback.

Thanks

File: daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/v2/ledgerinteraction/SubmitError.scala (hunk 2 above)
Comment (samuel-williams-da) [reply daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/v2/ledgerinteraction/SubmitError.scala:368]: You need to add the new variant to `daml-script/daml3/Daml/Script/Questions/Submit/Error.daml` in the same position.

**Review by samuel-williams-da — COMMENTED** [review]
This introduces a few issues with the test tool.
You'll need to update `DeeplyNestedValueIT.scala` with the new error type.
You'll also need to add a new compatibility test exclusion, or extend the one that already exists for DeeplyNested, as now last weeks snapshot won't work with this version.
And lastly, this'll need a roundabout change to canton to ensure it encodes this error with its own code, then the upgrade docs will need updating, and the error code resources docs will need updating, this is a rather involved change...

**Review by loiskilberg-da — APPROVED** [review]
ok as far as language review
