### PR TITLE
Do not send archive commands if there is no active contract

### LINKED ISSUE #13796: Error on reload in daml start if there are no active contracts
Steps to reproduce:
1. Run `daml start` for create-daml-app (do nothing else, in particular do not login in your browser)
2. Press `r` in the terminal to reload
3. Observe the error
```
Failed to archive active contracts: "MISSING_FIELD(8,9f7010b7): The submitted command is missing a mandatory field: commands"
```
Looks like there are no active contracts so there are no commands to archive stuff. We should just not send  the command in that case instead of producing this error.

### PR DESCRIPTION
**Pull request by chunlokling-da**
fixes #13796

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

File: daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs [hunk 1]
```diff
@@ -501,34 +501,37 @@ reset args = do
...
+            let archiveCommends = [ L.ExerciseCommand
+                                    { tid = tid
+                                    , cid = cid
+                                    , choice = L.Choice "Archive"
+                                    , arg = L.VRecord $ L.Record Nothing []
+                                    }
+                                  | (_offset, _mbWid, events) <- chunk
+                                  , L.CreatedEvent {cid, tid} <- events
+                                  ]
+            if null archiveCommends then
```
Comment (ray-roestenburg-da) [inline daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs:513]:
```suggestion
            if null archiveCommands then
```

File: daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs [hunk 2]
```diff
@@ -501,34 +501,37 @@ reset args = do
...
+              pure ()
+            else do
+              cmdId <- liftIO UUID.nextRandom
+              let cmds =
+                    L.Commands
+                      { coms = archiveCommends
```
Comment (ray-roestenburg-da) [inline daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs:519]:
```suggestion
                      { coms = archiveCommands
```

**Review by ray-roestenburg-da — COMMENTED** [review]
Please rename `archiveCommends` to `archiveCommands`, LGTM otherwise!

**Review by ray-roestenburg-da — APPROVED** [review]

File: daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs [hunk 3]
```diff
@@ -501,34 +501,37 @@ reset args = do
...
-                    , dedupPeriod = Nothing
-                    , minLeTimeAbs = Nothing
-                    , minLeTimeRel = Nothing
-                    , sid = Nothing
-                    }
-            errOrEmpty <- L.submit cmds
-            case errOrEmpty of
-              Left err -> liftIO $ putStrLn $ "Failed to archive active contracts: " <> err
-              Right () -> pure ()
+            let archiveCommands = [ L.ExerciseCommand
```
Comment (S11001001) [inline daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs:504]: If you wanted to make a smaller change, you could write `let cmds cmdId` instead of moving the definition for the purpose of being in scope of the binding of `cmdId`.

**Review by S11001001 — APPROVED** [review]
LGTM, just some food for thought.

File: daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs [hunk 4]
```diff
@@ -525,10 +525,12 @@ reset args = do
                     , minLeTimeRel = Nothing
                     , sid = Nothing
                     }
-            errOrEmpty <- L.submit cmds
-            case errOrEmpty of
-              Left err -> liftIO $ putStrLn $ "Failed to archive active contracts: " <> err
-              Right () -> pure ()
+            unless null [ x | (_offset, _mbWid, _events) <- chunk, x <- events ] $ do
+              cmdId <- liftIO UUID.nextRandom
+              errOrEmpty <- L.submit cmds cmdId
```
Comment (S11001001) [inline daml-assistant/daml-helper/src/DA/Daml/Helper/Ledger.hs:530]:
```suggestion
              errOrEmpty <- L.submit $ cmds cmdId
```
