### PR TITLE
Fix automatic retry mechanism in scala bindings.

### LINKED ISSUE #3057: Retries through the scala client fail because they reuse the same command id
The command id is created in the client code and in case of a failure the retry is in the Scala Akka bindings. However we are persisting commands regardless their failure status (all except duplicate commands). The bindings though have a retry logic that seems to automatically retry all commands that didn't fail with INVALID_ARGUMENT_VALUE. These two seems to be at odds with each other.
See: `com.digitalasset.ledger.client.binding.retrying.CommandRetryFlow`

### PR DESCRIPTION
**Pull request by gerolf-da**
This fix only affects the usage of
com.digitalasset.ledger.client.binding.LedgerClientBinding#retryingConfirmedCommands

The retry mechanism didn't distinguish between submission failures and
final completion failures. Retrying completion failures with the same
commandId doesn't make sense, as the deduplication mechanism will kick
in.
The new mechanism now only retries commands with an updated LET and MRT
in case the server responds with a RESOURCE_EXHAUSTED status code (i.e.
backpressure).

Fixes #3057.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala [hunk 1]
```diff
@@ -72,12 +72,12 @@ object CommandRetryFlow {
                 } else if ((firstSubmissionTime plus maxRetryTime) isBefore timeProvider.getCurrentTime) {
                   RetryLogger.logStopRetrying(request, status, nrOfRetries, firstSubmissionTime)
                   PROPAGATE_PORT
-                } else if (NON_RETRYABLE_ERROR_CODES.contains(status.code)) {
-                  RetryLogger.logFatal(request, status, nrOfRetries)
-                  PROPAGATE_PORT
-                } else {
+                } else if (RETRYABLE_ERROR_CODES.contains(status.code)) {
```
Comment (stefanobaghino-da) [inline language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala]: Does this logic operate only on submission or on both submission and completion? Would this result in bugs if a completion would start to return an error code in `RETRYABLE_ERROR_CODES`?

Comment (gerolf-da) [reply language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala]: This operates on whatever produces a `Completion` value. Unfortunately the client side command tracking mechanism produces such values it self, even though it may not have received it from the ledger. This is used to communicate timeouts (ABORTED) and backpressure (RESOURCE_EXHAUSTED). The reason why I didn't count the ABORTED status code as retryable is that ABORTED is also used for actual rejections in completions.

Comment (gerolf-da) [reply language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala]: It's probably better to remove it altogether, because

- it's very brittle
- only works for *very* few cases
- the application needs to handle failure anyway, because even the retry mechanism can run into an upper bound of retries and the command can still fail.

Comment (leo-da) [reply language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala]: I agree with @gerolf-da, application should handle failures/retries.
The change looks good, does what it supposed to. I was actually going to ask about `ABORTED` and `UNAVAILABLE`... `ABORTED` case is explained above, how about `UNAVAILABLE`?
Here is the link explaining GRPC error codes: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
```
The service is currently unavailable. This is most likely a transient condition, which can be corrected by retrying with a backoff. Note that it is not always safe to retry non-idempotent operations.
```
I think it makes sense to add `UNAVAILABLE` to `RETRYABLE_ERROR_CODES`.

Comment (leo-da) [reply language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala]: do we actually claim that command submission is `idempotent`?

Comment (leo-da) [reply language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala]: I guess we don't claim it at all, read the PR summary:

>  Retrying completion failures with the same
commandId doesn't make sense, as the deduplication mechanism will kick
in.

What happens when deduplication mechanism kicks off?

Comment (gerolf-da) [reply language-support/scala/bindings-akka/src/main/scala/com/digitalasset/ledger/client/binding/retrying/CommandRetryFlow.scala]: In case of a transaction, it gets rejected. But interestingly, the deduplication mechanism currently doesn't work on rejections. In that case storing the rejection fails with a sql exception.
