### PR TITLE
Fix #12129: allow users' access to their own info

### LINKED ISSUE #12129: ledger api server: allow authenticated user to read its own user record and rights
Bug reported by @cocreature and @realvictorprm . To be fixed as part of the PoC.

### PR DESCRIPTION
**Pull request by meiersi-da**
CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description
- [x] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 1]
```diff
@@ -170,6 +172,26 @@ final class Authorizer(
...
+    authenticatedClaimsFromContext()
+      .flatMap(claims =>
+        if (claims.resolvedFromUser)
+          claims.applicationId match {
+            case Some(applicationId) => Success(Some(applicationId))
+            case None =>
+              Failure(
+                LedgerApiErrors.AuthorizationChecks.InternalAuthorizationError
+                  .Reject(
+                    "unexpectedly the user-id is not set in the authenticated claims",
```
Comment (mziolekda) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:185]:
```suggestion
                    "the user-id is not set in the authenticated claims",
```

File: ledger/sandbox-classic/src/test/lib/scala/platform/sandbox/auth/ServiceCallAuthTests.scala [hunk 2]
```diff
@@ -141,4 +146,11 @@ trait ServiceCallAuthTests
   protected val canReadAsAdminRandomParticipantId: Option[String] =
     Option(customTokenToHeader(forParticipantId(UUID.randomUUID.toString, adminToken)))
 
+  protected def createUserAsAdmin(userId: String): Future[(User, Option[String])] = {
```
Comment (mziolekda) [inline ledger/sandbox-classic/src/test/lib/scala/platform/sandbox/auth/ServiceCallAuthTests.scala:149]: This name is a bit misleading. It could be interpreted that the newly created user is an admin. Maybe createUserThroughAdmin or createUserByAdmin would be better?

**Review by mziolekda — APPROVED** [review]
two little nits, feel free to address in a follow up

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala (hunk 1 above)
Comment (meiersi-da) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:185]: The `unexpectedly` is there to remind the developer that this is not expected. It is an internal error.

File: ledger/sandbox-classic/src/test/lib/scala/platform/sandbox/auth/ServiceCallAuthTests.scala (hunk 2 above)
Comment (meiersi-da) [reply ledger/sandbox-classic/src/test/lib/scala/platform/sandbox/auth/ServiceCallAuthTests.scala:149]: thx
