### PR TITLE
correct JSON API upper date bound

### LINKED ISSUE #10449: Data Bounds Incorrectly Designated (9999-99-99)
In the DA_SDK.pdf, page 259/577:

#### 3.3.1.7 Date

> The dates must be between the bounds specified by Daml-LF and ISO 8601, [0001-01-01, 9999-99-99].

Shouldn't this be:

> The dates must be between the bounds specified by Daml-LF and ISO 8601, [0001-01-01, 9999-12-31].

Or is this only a Numerical format, and that the implied use would correctly be 9999-12-31?

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
As reported by @quid-agis. Fixes #10449.

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

**Comment by cocreature** [comment]
this is a duplicate of #10468

**Comment by realvictorprm** [comment]
sorry that I did not take care of the additional test yet. Did not spend time on looking into the spec tests further.

**Comment by garyverhaegen-da** [comment]
> this is a duplicate of #10468

But that's clearly dead: it's not moved in all of two days. Also this has tests now. 😇

(I blame GitHub for not refreshing #10449 so I could see the reference.)

File: ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala [hunk 1]
```diff
@@ -136,7 +136,13 @@ class ApiCodecCompressed[Cid](val encodeDecimalAsString: Boolean, val encodeInt6
       case Model.DamlLfPrimType.Timestamp => { case JsString(v) =>
         V.ValueTimestamp(assertDE(Time.Timestamp fromString v))
       }
-      case Model.DamlLfPrimType.Date => { case JsString(v) => V.ValueDate.fromIso8601(v) }
+      case Model.DamlLfPrimType.Date => { case JsString(v) =>
+        try {
+          V.ValueDate.fromIso8601(v)
+        } catch {
+          case _: Exception => throw DeserializationException(s"Invalid date: $v")
```
Comment (garyverhaegen-da) [inline ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala:143]: The table of failures in `ApiCodeCompressedSpec` expects `DeserializationException` specifically. I wasn't sure which side should be changed.

**Comment by realvictorprm** [comment]
> > this is a duplicate of #10468
> 
> But that's clearly dead: it's not moved in all of two days. Also this has tests now. 
> 
> (I blame GitHub for not refreshing #10449 so I could see the reference.)

Ignoring the fact that often enough PR's are left for one or two days :stuck_out_tongue: 

Jokes aside, thanks for doing this :cowboy_hat_face:

**Review by realvictorprm — APPROVED** [review]
Looks good to me :) Many thanks for taking over :+1:

File: ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala (hunk 1 above)
Comment (cocreature) [reply ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala:143]: Changing here seems fine but I’d prefer to catch `java.time.format.DateTimeParseException` and `IllegalArgumentException` instead of catching `Exception`.

File: ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala [hunk 2]
```diff
@@ -136,7 +136,13 @@ class ApiCodecCompressed[Cid](val encodeDecimalAsString: Boolean, val encodeInt6
       case Model.DamlLfPrimType.Timestamp => { case JsString(v) =>
         V.ValueTimestamp(assertDE(Time.Timestamp fromString v))
       }
-      case Model.DamlLfPrimType.Date => { case JsString(v) => V.ValueDate.fromIso8601(v) }
+      case Model.DamlLfPrimType.Date => { case JsString(v) =>
+        try {
+          V.ValueDate.fromIso8601(v)
```
Comment (cocreature) [inline ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala:141]: probably not in scope for this PR but we might want to consider having `fromIso8601`return an `Either` and having an `assertFromIso8601` that throws like we do in lots of other places.

**Review by cocreature — APPROVED** [review]
Thanks!

**Comment by realvictorprm** [comment]
@garyverhaegen-da I can take over the requested changes if you want, just ping me

File: ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala (hunk 1 above)
Comment (garyverhaegen-da) [reply ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala]: I slightly disagree but since you're not here to argue today I'll go with your approach.

File: ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala (hunk 2 above)
Comment (garyverhaegen-da) [reply ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala:141]: @realvictorprm Since you offered, do you want to take care of this part?

Comment (realvictorprm) [reply ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala:141]: Will do :)

Comment (garyverhaegen-da) [reply ledger-service/lf-value-json/src/main/scala/com/digitalasset/daml/lf/value/json/ApiCodecCompressed.scala:141]: Thanks!
