### PR TITLE
Make record constructors in contract keys work

### LINKED ISSUE #890: ContractKey of type record not working
Example: 
```
data Rec = Rec with
  a : Text
  b : Text
    deriving (Eq, Show)

data MyKey = MyKey with
  a : Text
  p : Party

template Foo
  with
    p : Party
    r : Rec
  where
    signatory p
    maintainer p
    key (MyKey with a = r.a, p): MyKey
```

Error: Failure to process DAML program, this feature is not currently supported.
Template key expression with etmapp.
Iou:$WMyKey (Iou:Rec.a (Iou:Foo.r this)) (Iou:Foo.p this)

### PR DESCRIPTION
**Pull request by hurryabit**
Currently, they don't always work because we don't inline record constructors
aggressively enough. The PR address this flaw by inlining more constructors.

Fixes #890.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/daml/907)

### CODE REVIEW

File: daml-foundations/daml-ghc/src/DA/Daml/GHC/Compiler/Convert.hs [hunk 1]
```diff
@@ -757,13 +757,14 @@ convertExpr env0 e = do
         -- work. Constructor workers are not handled (yet).
         | Just m <- nameModule_maybe $ varName x
         , Just con <- isDataConId_maybe x
-        , not ("$W" `isPrefixOf` is x)
+        -- , not ("$W" `isPrefixOf` is x)
```
Comment (neil-da) [inline daml-foundations/daml-ghc/src/DA/Daml/GHC/Compiler/Convert.hs]: Not a fan of arbitrarily commented out code

**Comment by hurryabit** [comment]
The whole `$WFoo` vs `$ctor:Foo` situation needs a cleanup. I'll do that in a separate PR during the next couple of days.

File: daml-foundations/daml-ghc/src/DA/Daml/GHC/Compiler/Convert.hs (hunk 1 above)
Comment (hurryabit) [reply daml-foundations/daml-ghc/src/DA/Daml/GHC/Compiler/Convert.hs]: That was an accident. Removed.

**Comment by hurryabit** [comment]
I'm not 100% sure what the relationship between `Foo` and `$WFoo` is but I've only seen cases where they have the same type so far. I expect the DAML-LF type checker to tell us if I'm mistaken.
