### PR TITLE
Fix an issue in module chasing caused by unnormalized file paths

### LINKED ISSUE #1284: Can't import inside twice nested modules in Windows
To replicate, in windows:

1. Create new project with `daml new p`
2. create a new module `A.B.C` and import main by creating `p/daml/A/B/C.daml` with
  ```
daml 1.2
module A.B.C where

import Main
   ```
3. Observe the error appearing on the import statement.

### PR DESCRIPTION
**Pull request by cocreature**
On Windows we can end up with rootModDir having / in the filepath
while rootPathDir uses \ so stripSuffix didn’t work.

This fixes #1284

As mentioned in the comment, this is a somewhat ugly workaround but I’d like to wait until @DavidM-D’s filepath changes land before attempting to fix this properly.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/haskell-ide-core/src/Development/IDE/Functions/Compile.hs [hunk 1]
```diff
@@ -233,7 +233,12 @@ runGhcSession IdeOptions{..} modu env act = runGhcEnv env $ do
 moduleImportPaths :: GHC.ParsedModule -> Maybe FilePath
 moduleImportPaths pm
   | rootModDir == "." = Just rootPathDir
-  | otherwise = dropTrailingPathSeparator <$> stripSuffix rootModDir rootPathDir
+  | otherwise =
+    -- TODO (MK) stripSuffix (normalise rootModDir) (normalise rootPathDir)
+    -- would be a better choice but at the moment we do not consistently
+    -- normalize file paths in the Shake graph so we can end up with the
+    -- same module being represented twice in the Shake graph.
+    Just $ dropTrailingPathSeparator $ dropEnd (length rootModDir) rootPathDir
```
Comment (neil-da) [inline compiler/haskell-ide-core/src/Development/IDE/Functions/Compile.hs]: What is rootPathDir doesn't start with rootModDir? I guess the alternative is adding nothing to the import path, so adding something wrong probably won't be harmful...

Comment (cocreature) [reply compiler/haskell-ide-core/src/Development/IDE/Functions/Compile.hs]: Yeah I don’t think it should cause issues. The whole area around file paths and include dirs deserves some refactoring and cleanup once the LSP side is done so I’ll leave it for that.
