### PR TITLE
Fix trace statement handling in DAML Script service

### LINKED ISSUE #7280: `debug` and `trace` statements should be output in the Transaction View of DAML Script in the IDE
It works for Scenarios.

### PR DESCRIPTION
**Pull request by cocreature**
This PR makes sure that we get both trace statements coming from the
ledger client as well as from the ledger server. In the script service
those are two different Speedy machines so we need to interleave
them. This is a bit messy so let me explain the steps (apologies for
not splitting it up but I think it’s easier to understand the
motivation when it is a single PR):

1. Abstract over the tracelog interface. The ringbuffer doesn’t makes
   sense for our purposes and is annoying to clear.

2. Pass in the respective fields of `Machine` to `Conversions` instead
   of the whole machine. This is both a simpler design (passing around
   mutable objects scares me) and it allows us to assemble the fields
   from different machines.

3. Initialize the ledger machine with a simple ArrayBuffer tracelog.

4. After `submit` and `submitMustFail` copy the tracelog from the
   ledger to the client.

fixes #7280

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/Runner.scala [hunk 1]
```diff
@@ -283,6 +283,33 @@ object Runner {
...
+      // FIXME: avoid override of non abstract method
+      override def definitions: PartialFunction[SDefinitionRef, SExpr] =
+        fromLedgerValue.orElse(compiledPackages.definitions)
+      override def packageLanguageVersion: PartialFunction[PackageId, LanguageVersion] =
+        compiledPackages.packageLanguageVersion
+    }
+  }
+
+  val machine =
+    Speedy.Machine.fromPureSExpr(extendedCompiledPackages, script.expr, onLedger = false)
```
Comment (aherrmann-da) [inline daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/Runner.scala:311]: This means the machine is now persisted across multiple runs, right? Does this mean we need to reset it after runs, e.g. between test cases in `daml test-script`?

**Review by aherrmann-da — APPROVED** [review]
LGTM. One question about resetting the machine in the runner between script tests.

File: daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/Runner.scala (hunk 1 above)
Comment (cocreature) [reply daml-script/runner/src/main/scala/com/digitalasset/daml/lf/engine/script/Runner.scala:311]: An indvidual `Runner` is specific to a single script. I’m not aware of any case where we call `run` multiple for a single script or reuse `Runner` at all so this doesn’t really matter. But I agree that the API here is confusing and doesn’t enforce that this is used correctly and we should fix this. I’ve changed it to return the machine from `runWithClients` now. It feels a bit weird to return `(Machine, Future[_])` but it does the trick and avoids this. We should probably also kill the `Runner`constructer since we never construct a runner without running it immediately.

File: compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/scenario/Context.scala [hunk 2]
```diff
@@ -206,11 +206,12 @@ class Context(val contextId: Context.ContextId, languageVersion: LanguageVersion
     val client = new IdeClient(compiledPackages)
     val participants = Participants(Some(client), Map.empty, Map.empty)
     runner.runWithClients(participants).transform {
-      case Success(v) => Success(Some((client.scenarioRunner.ledger, client.machine, Right(v))))
+      case Success(v) =>
+        Success(Some((client.scenarioRunner.ledger, (runner.machine, client.machine), Right(v))))
```
[the remark this answers is not in the document]
Comment (cocreature) [reply compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/scenario/Context.scala]: good idea, renamed.
