### PR TITLE
Compiler: Make LF 1.14 the default output

### LINKED ISSUE #8591: LF 1.13
Ticket for the next stable LF version after LF 1.12

Previous LF version ticket: #8369

Task:

- [x]  BigNumeric 
- [x] preview version (in SDK 1.13) 
- [x] release version (in SDK 1.14)
- [ ] default compiler output (in SDK 1.15) #9907

### LINKED ISSUE #9914: LF 1.14
Previous LF version ticket: #8591

this version of LF should include:

- [x] exceptions #8020
- [x] byKey flag Node #9632
- [x] preview version (in SDK 1.14) #9906
- [X] release version (in SDK 1.15) #10077
- [x] bump ledger API version #10175
- [ ] default compiler output (in SDK 1.16) #10394

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
fixes #9914

CHANGELOG_BEGIN

- [Compiler] Default compiler output LF version is now 1.14

CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-lf/engine/src/test/scala/com/digitalasset/daml/lf/engine/EngineTest.scala [hunk 1]
```diff
@@ -133,6 +132,15 @@ class EngineTest
         withKeyContractInst,
     )
 
+  val defaultKey = Map(
```
Comment (cocreature) [inline daml-lf/engine/src/test/scala/com/digitalasset/daml/lf/engine/EngineTest.scala:135]: Was this just broken before? I’m a bit confused why we now need to add a global key that we did not need before.

**Review by cocreature — APPROVED** [review]
Thanks! one minor comment

File: daml-lf/engine/src/test/scala/com/digitalasset/daml/lf/engine/EngineTest.scala (hunk 1 above)
Comment (remyhaemmerle-da) [reply daml-lf/engine/src/test/scala/com/digitalasset/daml/lf/engine/EngineTest.scala:135]: Before `1.14`, `by-key` node where replayed `by-id`, so we did not need to mock the `ResultNeedKey` lookup during reinterpretation. 

Now we have the `by-key` flag we replay them `by-key`, so we need to mock properly the  `ResultNeedKey` lookup.

Comment (cocreature) [reply daml-lf/engine/src/test/scala/com/digitalasset/daml/lf/engine/EngineTest.scala:135]: oh I see, so the state was broken before but because we replayed by-id speedy did not emit a SResultNeedKey. Thanks for the explanation

**Comment by remyhaemmerle-da** [comment]
to be merged after tomorrow (July 28th) release.
