### PR TITLE
language: fix: don't look for daml files in hidden directories

### LINKED ISSUE #3134: Package dependency chain causes ambiguity when not using `exposed-modules`
Using a setup where three packages depend on each other, the compiler fails to resolve the ambiguity for imports of the bottom package.

The attached 3-package setup [no-exposed.zip](https://github.com/digital-asset/daml/files/3705683/no-exposed.zip) configures packages with the following *dependencies:*
package 3 -> package 1
package 3 -> package 2
package 2 -> package 1
None of the `daml.yaml` files uses the (optional) `exposed-modules`.

Compilation fails with the following error:
```
$ for p in package1 package2 package3; do echo "daml build --project-root $p"; daml build --project-root $p ; done
daml build --project-root package1
Compiling package1 to a DAR.
Created .daml/dist/package1-0.0.1000.dar.
daml build --project-root package2
Compiling package2 to a DAR.
Created .daml/dist/package2-0.0.1000.dar.
daml build --project-root package3
Compiling package3 to a DAR.
File:    
  ./.daml/package-database/1.6/package2-0.0.1000-8565127e298c4d802bda3522084e1bffe06999ae3ad65a82cc9cac8bb6b6f444/Package2File.daml
Range:    5:7-5:19
Source:   not found
Severity: DsError
Message: 
  Ambiguous module name `Package1File':
  it was found in multiple packages:
  package1-0.0.1000 package2-0.0.1000
File:     ./Package3File.daml
Range:    5:7-5:19
Source:   not found
Severity: DsError
Message: 
  Ambiguous module name `Package1File':
  it was found in multiple packages:
  package1-0.0.1000 package2-0.0.1000
ERROR: Creation of DAR file failed.
```

### PR DESCRIPTION
**Pull request by robin-da**
Fixes #3134. When locating daml source files, we need to make sure we're
not recursing into the .daml directory, because it contains source files
of the dependencies.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-assistant/integration-tests/src/Main.hs [hunk 1]
```diff
@@ -138,9 +138,9 @@ noassistantTests damlDir = testGroup "no assistant"
               callProcess damlcPath ["build", "--project-root", "foobar", "--init-package-db", "yes"]
     ]
 
-packagingTests :: FilePath -> TestTree
-packagingTests tmpDir = testGroup "packaging"
-    [ testCaseSteps "Build package with dependency" $ \step -> do
+packagingTests :: TestTree
+packagingTests = testGroup "packaging"
+    [ testCaseSteps "Build package with dependency" $ \step -> withTempDir $ \tmpDir -> do
```
Comment (cocreature) [inline daml-assistant/integration-tests/src/Main.hs]: What changed that requires us to use `withTempDir` here now? It looks reasonable but I don’t see why this has to change with this PR.

File: daml-assistant/integration-tests/src/Main.hs [hunk 2]
```diff
@@ -230,15 +230,18 @@ packagingTests tmpDir = testGroup "packaging"
...
             , "  - daml-prim"
             , "  - daml-stdlib"
             , "  - " <> aDar
             ]
         withCurrentDirectory projectB $ callCommandQuiet "daml build"
         assertBool "b.dar was not created." =<< doesFileExist bDar
-    , testCase "Build package with SDK dependency" $ do
+        darFiles <- Zip.filesInArchive . Zip.toArchive <$> BSL.readFile bDar
+        assertBool "b.dar contains source file from package database" $
+            all (not . ("A.daml" `isSuffixOf`)) darFiles
```
Comment (cocreature) [inline daml-assistant/integration-tests/src/Main.hs]:
```suggestion
            not $ any ("A.daml" `isSuffixOf`) darFiles
```
feel free to ignore that but I find that slightly easier to read

File: daml-assistant/integration-tests/src/Main.hs (hunk 1 above)
Comment (robin-da) [reply daml-assistant/integration-tests/src/Main.hs]: we happen to use the same temporary directory for all separate packaging tests. That means it's very easy to pick up sources from other tests with unpredictable results. This, for example, happened when I changed the source field of the dependency test to "." instead of "A.daml" here.
