### PR TITLE
sandbox: fail on already existing port-file.

### LINKED ISSUE #7806: Align sandbox/json-api behaviour for already existing portfiles
The sandbox accepts and overwrites already existing port files. The JSON API server rejects them and fails. It would be good to align them. I prefer sandbox's behaviour because it allows for easy testing with temporarily created files.

### PR DESCRIPTION
**Pull request by robin-da**
Fixes #7806. This aligns the port file behavior of the sandbox with the
HTTP JSON API.

CHANGELOG_BEGIN
[sandbox/json-api] Both services have the same port-file behavior now. They fail when a port-file already exists and write port-files atomically.
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/participant-integration-api/src/main/scala/platform/apiserver/StandaloneApiServer.scala [hunk 1]
```diff
@@ -150,6 +150,10 @@ final class StandaloneApiServer(
 
   private def writePortFile(port: Port): Unit =
     config.portFile.foreach { path =>
-      Files.write(path, Seq(port.toString).asJava)
+      if (Files.exists(path)) { sys.error(s"Portfile ${path} already exists.") } else {
```
Comment (cocreature) [inline ledger/participant-integration-api/src/main/scala/platform/apiserver/StandaloneApiServer.scala:153]: Can we use `Portfiles.write` here and fix that to be atomic instead?

Comment (robin-da) [reply ledger/participant-integration-api/src/main/scala/platform/apiserver/StandaloneApiServer.scala:153]: sure. Is there any reason why `Portfiles` wasn't used before here?

Comment (cocreature) [reply ledger/participant-integration-api/src/main/scala/platform/apiserver/StandaloneApiServer.scala:153]: It got created after this piece of code was written and nobody bothered to switch this over (and we didn’t agree on changing the behavior in sandbox at the time).

File: libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala [hunk 2]
```diff
@@ -36,9 +36,11 @@ object PortFiles {
     }
 
   private def writeUnsafe(path: Path, port: Port): Unit = {
```
Comment (SamirTalwar-DA) [inline libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:38]: Can we get a test case for this logic?

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:38]: I think there is already one in PortFilesSpec. But yes, I'll check that there are tests, this is still a draft, I want to see all the tests that are failing now.

File: libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala [hunk 3]
```diff
@@ -36,9 +36,11 @@ object PortFiles {
...
-    import java.nio.file.StandardOpenOption.CREATE_NEW
+    if (Files.exists(path)) throw new FileAlreadyExistsException(path.toString())
```
Comment (cocreature) [inline libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:39]: This is racy. The file can get created between this check and the move. We need to set flags on the move to file if the file already exists and catch the exception.

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:39]: I couldn't find any files on the `move` command for the check. But let's see if there is another way.

Comment (cocreature) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:39]: https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...) claims that it will fail by default if it already exists so it looks like we already get what we need.

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:39]: oh perfect.

File: libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala [hunk 4]
```diff
@@ -36,9 +36,10 @@ object PortFiles {
     }
 
   private def writeUnsafe(path: Path, port: Port): Unit = {
-    import java.nio.file.StandardOpenOption.CREATE_NEW
     val lines: java.lang.Iterable[String] = List(port.value.toString).asJava
-    val created = Files.write(path, lines, CREATE_NEW)
+    val tmpFile = Files.createTempFile("portfile", "")
+    Files.write(tmpFile, lines)
+    val created = Files.move(tmpFile, path)
```
Comment (cocreature) [inline libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: There is an `ATOMIC_MOVE` flag, maybe we should use that and fall back to a non-atomic move if we have to? I’m not quite sure if not using that flag is equivalent to that or if it will always be non-atomic.

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: I was thinking the same thing when I read the docs. Not sure if ATOMIC_MOVE is the default or if we need to set it explicitly and deal with the possibility that the atomic move is not possible on a system.

Comment (cocreature) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: I guess if the docs are unclear, trying the atomic move first is the safe option? :shrug:

Comment (SamirTalwar-DA) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: From the [docs](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#move-java.nio.file.Path-java.nio.file.Path-java.nio.file.CopyOption...-):

> If the target file exists then it is implementation specific if the existing file is replaced or this method fails by throwing an IOException.

I know this works as you'd expect on Linux but I have no idea about other systems.

Comment (SamirTalwar-DA) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: Based on digging into this a little when writing _ledger-on-filesystem_, I came to the conclusion that on Linux and macOS, it probably does nothing _except_ when you try and move across file systems, in which case it errors because you can't do an atomic move across file systems.

On Windows, I _think_ it does nothing, but I'm not sure.

Comment (cocreature) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: That seems like a very questionable API. Why does requesting an atomic move change whether it overwrites a file or not :scream_cat:

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: Let's set the flag to be on the safe side then. I wouldn't bother with the additional error case for now though.

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala]: So I added ATOMIC_MOVE, which seems to work just fine on my local system. But a lot of tests are failing now on CI. Does anybody have an idea what's going on?

Comment (SamirTalwar-DA) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala]: > java.nio.file.AtomicMoveNotSupportedException: /home/vsts/.cache/bazel/_bazel_vsts/d5c8b3f1185416e5207d53317d3a7876/sandbox/linux-sandbox/667/execroot/com_github_digital_asset_daml/_tmp/e05013f2f0106511efb2381068335f20/portfile3984526891245692342 -> PortFilesSpec-8504083e-142d-42f8-8bee-d6495e77540d.dummy: Invalid cross-device link

Looks like the Bazel-allocated temporary directory isn't on the same volume.

I suggest just turning it off again and calling it best-effort.

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: Looks like it's ont that easy. Without `ATOMIC_MOVE` tests fail for me locally, while they pass with the flag set, but don't pass CI...

Comment (cocreature) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: @robin-da how does it fail locally? Presumably not with the same error?

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: tests fail with the `portfile not written in time` error. I try now to add a fallback for when `ATOMIC_MOVE` is not supported.

Comment (cocreature) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: huh that seems very odd. Which test is that? I can try to reproduce.

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala]: you can try assistant integration tests

Comment (cocreature) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala]: This is expected. daml-helper will use an already existing file as the port file. Here’s the fix:

```
diff --git a/daml-assistant/daml-helper/src/DA/Daml/Helper/Start.hs b/daml-assistant/daml-helper/src/DA/Daml/Helper/Start.hs
index 330954788..7386faa10 100644
--- a/daml-assistant/daml-helper/src/DA/Daml/Helper/Start.hs
+++ b/daml-assistant/daml-helper/src/DA/Daml/Helper/Start.hs
@@ -100,7 +100,8 @@ navigatorURL :: NavigatorPort -> String
 navigatorURL (NavigatorPort p) = "http://localhost:" <> show p
 
 withSandbox :: SandboxClassic -> SandboxPortSpec -> [String] -> (Process () () () -> SandboxPort -> IO a) -> IO a
-withSandbox (SandboxClassic classic) portSpec extraArgs a = withTempFile $ \portFile -> do
+withSandbox (SandboxClassic classic) portSpec extraArgs a = withTempDir $ \dir -> do
+    let portFile = dir </> "port-file"
     let sandbox = if classic then "sandbox-classic" else "sandbox"
     let args = [ sandbox
                , "--port", show (fromSandboxPortSpec portSpec)
```

However this gets us back to `ATOMIC_MOVE` overwriting existing files. I think we just need to not use `ATOMIC_MOVE` and hope that at least on Linux it’s still atomic. I don’t see a way to force an atomic move while not also overwriting the file (any kind of exists check is racy).

Comment (robin-da) [reply libs-scala/ports/src/main/scala/com/digitalasset/ports/PortFiles.scala:42]: ok that fixes it. No more `ATOMIC_MOVE` and :crossed_fingers: .

**Review by cocreature — APPROVED** [review]
Thanks! Please add a changelog entry for sandbox on merging.

**Review by cocreature — APPROVED** [review]
Thanks! Please add a changelog entry for merging.

**Review by hurryabit — COMMENTED** [review]
Nice work. Thank you!
