### PR TITLE
LF: Gracefully handle serialization error of Values beyond 2GB

### LINKED ISSUE #12392: ValueCoder fails with NegativeArraySizeException if serialized size exceeds 2GB
# Affected Daml version

1.18.1

# To reproduce

Run this program (as a scala test test case):
```
    val n = 500000000
    val textValue = ValueText("a" * n)
    val recordValue = ValueRecord(
      None,
      ImmArray(
        None -> textValue,
        None -> textValue,
        None -> textValue,
        None -> textValue,
        None -> textValue,
      ),
    )
    val versionedValue = Versioned(TransactionVersion.VDev, recordValue)

    // Fails with NegativeArraySizeException
    val valuePOrErr = ValueCoder.encodeVersionedValue(ValueCoder.CidEncoder, versionedValue)

    // Expected behavior: The program should fail with an EncodeError with a human readable message
    val valueP = valuePOrErr.value

    Console.println(valueP.getValue.size())
```

Alternative scenario: Set n to 900000000. Then it fails with an EncodeError, but the message is a bit clunky:
```
Serializing com.daml.lf.value.ValueOuterClass$Value to a ByteString threw an IOException (should never happen).
java.lang.RuntimeException: Serializing com.daml.lf.value.ValueOuterClass$Value to a ByteString threw an IOException (should never happen).
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:62)
	at com.daml.lf.value.ValueCoder$.encodeValue(ValueCoder.scala:517)
	at com.daml.lf.value.ValueCoder$.encodeVersionedValue(ValueCoder.scala:388)
	at com.daml.lf.value.ValueCoder$.encodeVersionedValue(ValueCoder.scala:380)
	at com.digitalasset.canton.protocol.WellFormedTransactionTest.$anonfun$new$9(WellFormedTransactionTest.scala:388)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1225)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1237)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1237)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1219)
	at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1296)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1296)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1295)
	at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1879)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1341)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1341)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1339)
	at com.digitalasset.canton.protocol.WellFormedTransactionTest.org$scalatest$BeforeAndAfterAll$$super$run(WellFormedTransactionTest.scala:17)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at com.digitalasset.canton.protocol.WellFormedTransactionTest.run(WellFormedTransactionTest.scala:17)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
Caused by: com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeStringNoTag(CodedOutputStream.java:1506)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeString(CodedOutputStream.java:1216)
	at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:3090)
	at com.daml.lf.value.ValueOuterClass$Value.writeTo(ValueOuterClass.java:1904)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessageNoTag(CodedOutputStream.java:1306)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1274)
	at com.daml.lf.value.ValueOuterClass$RecordField.writeTo(ValueOuterClass.java:5811)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessageNoTag(CodedOutputStream.java:1306)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1274)
	at com.daml.lf.value.ValueOuterClass$Record.writeTo(ValueOuterClass.java:4784)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessageNoTag(CodedOutputStream.java:1306)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1274)
	at com.daml.lf.value.ValueOuterClass$Value.writeTo(ValueOuterClass.java:1888)
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:59)
	... 54 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Failed writing a at index 205032799
	at com.google.protobuf.Utf8$UnsafeProcessor.encodeUtf8(Utf8.java:1526)
	at com.google.protobuf.Utf8.encode(Utf8.java:293)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeStringNoTag(CodedOutputStream.java:1487)
	... 67 more
```

# Additional context

Protobuf is known to not support messages beyond 2GB. Unfortunately, Protobuf seems to fail ungracefully on the attempt to serialize an excessively large message.

It would be very helpful, if you could explore how Protobuf fails if the message is too big and map these exceptions to human readable EncodeErrors.

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
The [Protobuf library](https://github.com/protocolbuffers/protobuf) uses an `int` to represent and computes the number of bytes needed to serialized a message, however it does not  handle at all overflows. Consequently the result of `com.google.protobuf.MessageLite#getSerializedSize: Int` on messages requiring more that 2GB is meaningless. The Protobuf serialization code, which uses this number, then fails in unexpected way by emitted different kinds of `RuntimeException`s when trying to process too big messages.

We identified two different `RuntimeException`s that can be throw in such a case:
- A `NegativeArraySizeException` in case the result of `getSerializedSize` is negative
- A generic `RunTimeException` with a cause of type com.google.protobug.OutOfSpaceException` in case the  result of `getSerializedSize` is positive (but smaller than required spaced needed to store the message).

fixes #12392

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/value/ValueCoder.scala [hunk 1]
```diff
@@ -526,4 +526,18 @@ object ValueCoder {
...
+  // Serialization of protobuf messages exceeding 2GB fails with different RuntimeExceptions.
+  // This functions tries to handle more gracefully those errors.
+  def toByteString(message: AbstractMessageLite[_, _]): Either[EncodeError, ByteString] =
+    try {
+      Right(message.toByteString)
+    } catch {
+      case _: RuntimeException =>
+        Left(
+          EncodeError(
+            s"Protobuf serialization of ${message.getClass.getName} failed: the message is probably too big."
```
Comment (matthiasS-da) [inline daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/value/ValueCoder.scala:539]: At least it won't throw anymore.

To make our support business easier, could you please:
- Embed the original exception (including stack trace) into the EncodeError. 
- Distinguish two cases: (1) message is too big (2) anything else. That way, we won't confuse our users with misleading assumptions of why an error occurred.

Comment (remyhaemmerle-da) [reply daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/value/ValueCoder.scala:539]: >     * Embed the original exception (including stack trace) into the EncodeError.

I will add the original exception. 
On the other hand, I am a bit reluctant to add the stack trace, as it does not fit very well in our current design of errors. Let us think a bit more about that.

>     * Distinguish two cases: (1) message is too big (2) anything else. That way, we won't confuse our users with misleading assumptions of why an error occurred.

The problem is there no simple way to detect if the message is too big. 
Basically the Protobuf library does not handle overflow when computing the message size, so when the message is too big, the computed size is just meaningless. 

In practice, I was able to make the proto library crashes with two different errors : 
- `java.lang.NegativeArraySizeException: -2147483570"`
- `java.lang.RuntimeException: Serializing com.daml.lf.value.ValueOuterClass$Value to a ByteString threw an IOException (should never happen).`

I prefer not :
- I cannot guarantee those errors happen only in case of too big message,
- I cannot guarantee no other exception would be thrown in case of too big message,
- The only way I can distinguish the second exception from others `RuntimeException`, is by matching the error message, I think it is terrible idea.

Comment (matthiasS-da) [reply daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/value/ValueCoder.scala:539]: Difficult situation...

If protobuf throws an exception in production or at a client, I need the stack-trace to help the client work around it. Without a stack trace it gets pretty hard. I also understand that you don't want to copy the stack-trace into the error message. 

How about this:
- For the expected errors (message too big), you discard the stack-trace.
- For the unexpected errors (everything else), you won't catch the exception so it is up to the caller to handle it.

(At some point, it would probably good to inject a logger into this class and just log the exception details. But this is a major breaking change and therefore probably out-of-scope for the moment.)

Now about distinguishing "message too big" from other errors. How about this:
* NegativeArraySizeException gets mapped to "message too big".
* RuntimeException: If I recall it correctly, if this is due to "message too big", there should be an ArrayIndexOutOfBoundsException further down the cause chain. So if you find a RuntimeException with ArrayIndexOutOfBoundsException as a cause, you map it to "message too big". Otherwise, you map it to "everything else".

I agree that we don't have 100% certainty how to detect a "message too big" scenario. I still think we should do our best to detect this case, because then the user can resolve the situation without getting back to us.

Comment (cocreature) [reply daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/value/ValueCoder.scala:539]: Matthias suggestion of discarding stack traces only on known exceptions makes sense to me. Throwing away stacktraces for exceptions that can occur from other stuff seems worse than letting them propagate to the caller.

**Review by cocreature — APPROVED** [review]
Nice, thank you!

**Comment by matthiasS-da** [comment]
Thanks to all of you, also from my side!
