### PR TITLE
auth tokens: support legacy sandbox format even with standard JWT claims present (#12285)

### LINKED ISSUE #12285: ledger api server: detect legacy custom tokens more robustly
This forum post (https://discuss.daml.com/t/namespace-missing-in-access-token/3606/2?u=cocreature) showed that there are legacy tokens being used that contain `sub` claims; e.g.
```
HEADER:ALGORITHM & TOKEN TYPE

{
“alg”: “RS256”,
“typ”: “JWT”,
“kid”: “blbuM_wwxxxxxmoRHgT52urXCnrRjo2upMfn9-W93DeU”
}

PAYLOAD:DATA

{
“exp”: 1788884832,
“iat”: 1688883951,
“auth_time”: 1639987633,
“jti”: “48wed2e6-84af-41ae-b5dd-976d29c3f999”,
“iss”: “https://xxx.xxx.xx”,
“aud”: “account”,
“sub”: “1f2971de-63e7-43fa-b791d-cb60ea920xxx”,
“typ”: “Bearer”,
“azp”: “xxx”,
“nonce”: “d5css71f-b0b8-4bfd-bhja-da67709027ec”,
“session_state”: “xxxefd-eb0f-4320-b79d-335xxx75”,
“acr”: “0”,
“allowed-origins”: [
“http://xxxx”,
“https://xxxxx”
],
“realm_access”: {
“roles”: [
“offline_access”
]
},
“resource_access”: {
“xxxxx-ui”: {
“roles”: [
“xxxxx-admin”
]
},
“account”: {
“roles”: [
“xxxxx-account”,
“xxxxx-account-links”,
“xxxxx-profile”
]
}
},
“scope”: “openid email profile”,
“ledgerId”: “xxxxxxxxxx”,
“actAs”: [
“Operator”
],
“email_verified”: true,
“name”: “xxxxxxxxx”,
“admin”: true,
“preferred_username”: “xxxxxxx”,
“given_name”: “xxxxx”,
“applicationId”: “xxxxxxxx”,
“family_name”: “xxxxxxx”,
“email”: “xxxxxxxxxxxx”,
“party”: “Operator”
}
```

These tokens are currently wrongly be parsed as standard claim tokens. This ticket is about changing the token format detection code to properly detect a token such as the above.

### PR DESCRIPTION
**Pull request by meiersi-da**
Fixes #12285 

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [x] Normal production system change, include purpose of change in description
- [x] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/AuthServiceJWTPayload.scala [hunk 1]
```diff
@@ -183,9 +189,8 @@ object AuthServiceJWTCodec {
   }
 
   def readStandardTokenPayload(jsValue: JsValue): Option[AuthServiceJWTPayload] = jsValue match {
-    // NOTE: there is the corner-case of a legacy Daml token containing a "sub" field.
-    // We accept that risk.
-    case JsObject(fields) if !fields.contains(oidcNamespace) && fields.contains("sub") =>
+    case JsObject(fields)
+        if fields.contains("sub") && !distinguishingCustomProps.exists(fields.contains) =>
```
Comment (cocreature) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/AuthServiceJWTPayload.scala:193]: This is slightly orthogonal but I find our APIs a bit confusing. If I’m just looking for something to decode a token, the first thing I’d try is `AuthServiceJWTCodec.readPayload`. However, that will only read non-standard tokens and to make things more confusing it will interpret a standard token as the legacy non-standard token which leads to rather confusing error messages.

I’d prefer if `readPayload` was the generic one that supports all formats and if we need to expose that API at all, the more specific ones have more specific names.

**Review by cocreature — APPROVED** [review]
Thanks! One comment on the APIs but they’re not actually modified int his PR so not a blocker.

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/AuthServiceJWTPayload.scala (hunk 1 above)
Comment (meiersi-da) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/AuthServiceJWTPayload.scala:193]: Good point. I'll address that in https://github.com/digital-asset/daml/issues/12049
