### PR TITLE
fix: project parties are not required

### LINKED ISSUE #8487: No party in daml.yaml file
Hi @digitalasset-cla, I am trying to run daml on fabric.

And for that I have fabric running in my system and also daml runtime is running. Now, I am trying to deploy daml contracts in daml runtime. 

Can I deploy the daml contract without specifying any party in the daml.yaml file.

That is can my daml.yaml file be :-

sdk-version: 1.7.0
name: daml_fabric
version: 0.1.0
source: daml
parties:
dependencies:
- daml-prim
- daml-stdlib
- daml-trigger
sandbox-options:
- --wall-clock-time
- --ledgerid=dt-task-sandbox
start-navigator: false

I don't want to register parties on the ledger through daml.yaml file, I want to register parties on the ledger dynamically, during runtime

### PR DESCRIPTION
**Pull request by robin-da**
This fixes a bug in daml assistant. `daml deploy` would fail if there
were no project parties listed in the daml.yaml project config file. Now
project parties are not required anymore.

Fixes #8487.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
Thanks! Maybe worth adding a test for?

**Comment by robin-da** [comment]
added a test.

File: daml-assistant/integration-tests/src/DA/Daml/Assistant/IntegrationTests.hs [hunk 1]
```diff
@@ -363,6 +363,23 @@ damlStartTests getDamlStart =
               withCurrentDirectory projDir $
                   callCommand $
                   unwords ["daml", "ledger", "allocate-party", "--port", show sandboxPort, "Bob"]
+        , testCase "run a daml deploy without project parties" $ do
```
Comment (cocreature) [inline daml-assistant/integration-tests/src/DA/Daml/Assistant/IntegrationTests.hs:366]: Can we add this to the other deployment tests in https://github.com/digital-asset/daml/blob/main/daml-assistant/daml-helper/test/DA/Daml/Helper/Test/Deployment.hs instead? I’m slightly hesitant to add more stuff to the integration tests.

Comment (robin-da) [reply daml-assistant/integration-tests/src/DA/Daml/Assistant/IntegrationTests.hs:366]: I tried to put it in the other location first, but `daml deploy` needs the DAML_PROJECT path etc. set, so in the deployment tests I would have to set up all environment variables. In the integration tests, we have the environment setup for free.

Comment (cocreature) [reply daml-assistant/integration-tests/src/DA/Daml/Assistant/IntegrationTests.hs:366]: Isn’t it only DAML_PROJECT that is needed? that doesn’t sound that bad.

Comment (robin-da) [reply daml-assistant/integration-tests/src/DA/Daml/Assistant/IntegrationTests.hs:366]: It also needs DAML_ASSISTANT and then wants to call it to build the package.

Comment (cocreature) [reply daml-assistant/integration-tests/src/DA/Daml/Assistant/IntegrationTests.hs:366]: Ah I see, that’s probably too annoying to set it up.

Comment (robin-da) [reply daml-assistant/integration-tests/src/DA/Daml/Assistant/IntegrationTests.hs:366]: That's what I was thinking.

**Review by sofiafaro-da — APPROVED** [review]
LGTM, thank you!
