### PR TITLE
Source location plumbing

### LINKED ISSUE #15572: Missing interface method error is reported in the wrong location
```
module Main where

data IView = IView {}

interface I where
  viewtype IView
  method : ()

template T
  with
    p : Party
  where
    signatory p
    interface instance I for T where
      view = IView
```

I'd expect the error in the interface instance but the actual error I get is at the template header.

```

2022-11-15 09:21:33.01 [INFO]  [build] 
Compiling foobar to a DAR.
File:     daml/Main.daml
Hidden:   no
Range:    9:10-11:14
Source:   Daml-LF typechecker
Severity: DsError
Message: 
  error type checking template Main.T interface instance Main:I for Main:T:
  Interface instance lacks an implementation for method 'method'
ERROR: Creation of DAR file failed.
```

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Resolves #15572 
Includes changes to protobuf
Change to Scala not needed, as the scala decoders throw away source locations at the moment

CHANGELOG_BEGIN

- [Daml Compiler] Improve error source locations for Daml specific syntax
  See `#15572 <https://github.com/digital-asset/daml/issues/15572>`__.

CHANGELOG_END

### CODE REVIEW

File: compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/Check.hs [hunk 1]
```diff
@@ -768,15 +768,15 @@ typeOf' = \case
     checkExpr val ty2
     pure ty1
   EToInterface iface tpl val -> do
-    checkUniqueInterfaceInstanceExists (InterfaceInstanceHead iface tpl)
+    checkUniqueInterfaceInstanceExists (InterfaceInstanceHead iface tpl Nothing)
```
Comment (akrmn) [inline compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/Check.hs:771]: having to add `Nothing`s here makes me think that the location field doesn't belong in `InterfaceInstanceHead`. Since the value of the new field is only used from `{T,I}PInterfaceInstance` and `pPrintInterfaceInstance`, I'd instead make the location a field of the former and an argument of the latter.

Comment (akrmn) [reply compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/Check.hs:771]: on that note, could you please also handle the location in `pPrintInterfaceInstance`? it should be a matter of wrapping the existing body with `withSourceLoc lvl <maybe loc>`

**Review by akrmn — APPROVED** [review]
LGTM, thank you @samuel-williams-da!
Just two requests regarding the location in `InterfaceInstanceHead` and `pPrintInterfaceInstance`

File: compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/Check.hs (hunk 1 above)
Comment (samuel-williams-da) [reply compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/Check.hs]: Yeah thats a fair point, I was treating the InterfaceInstanceHead as a more complete view of the instance than it really is, I've moved the source locations to the template/interface parts

**Review by akrmn — APPROVED** [review]
thanks for addressing my feedback!

File: daml-lf/archive/src/main/protobuf/com/daml/daml_lf_dev/daml_lf_1.proto [hunk 2]
```diff
@@ -1592,6 +1592,7 @@ message DefTemplate {
   message Implements {
     TypeConName interface = 1;
     InterfaceInstanceBody body = 2;
+    Location location = 3;
```
Comment (remyhaemmerle-da) [inline daml-lf/archive/src/main/protobuf/com/daml/daml_lf_dev/daml_lf_1.proto:1595]: Could you add a comment explaining they are ignored by Scala (I was not aware of that and quit annoyed by that) and they have been introduced latter than `Co`/`Implements` ? 

This would be probably very useful if we decide to handle this field on the scala side..

**Review by remyhaemmerle-da — APPROVED** [review]

File: daml-lf/archive/src/main/protobuf/com/daml/daml_lf_dev/daml_lf_1.proto (hunk 2 above)
Comment (samuel-williams-da) [reply daml-lf/archive/src/main/protobuf/com/daml/daml_lf_dev/daml_lf_1.proto:1595]: Sure! Though I have sadly already merged, whats the expected set of actions here? A new PR? Reopen this one with the changes?

Comment (samuel-williams-da) [reply daml-lf/archive/src/main/protobuf/com/daml/daml_lf_dev/daml_lf_1.proto:1595]: I'm working on another PR rn anyway, so I could add them in that one and link back here?
