### PR TITLE
do not wait for 2 seconds before shutting down the server

### LINKED ISSUE #178: Sandbox performance regression in versions 100.11.X
While upgrading a large application from sandbox 6.0.0 to a newer version (current target: 100.11.29) we observed that integration tests (involving sandbox, an application, and a special test driver) need much longer to run than before.

I will try to find out precisely which version introduced the regression, and whether it is really caused by sandbox performance (it may also be caused by other components, the upgrade I have tried is global) but reporting it now.

### PR DESCRIPTION
**Pull request by francesco-da**
should fix #178, will validate with @jberthold-da

### CODE REVIEW

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/services/SandboxResetService.scala [hunk 1]
```diff
@@ -55,26 +55,21 @@ class SandboxResetService(
...
-          logger.info("Rebuilding server...")
-          buildAndStartServer()
-          logger.info("Server reset complete.")
-      })(getEc())
-    p.success(Empty())
-    p.future
+    // We need to run this asynchronously since otherwise we have a deadlock: `buildAndStartServer` will block
+    // until all the in flight requests have been served, so we need to schedule this in another thread so that
+    // the code that clears the in flight request is not in an in flight request itself.
+    getEc().execute({ () =>
```
Comment (gaboraranyossy-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/services/SandboxResetService.scala]: you need to change the calling side as well, as types will not match

**Comment by jberthold-da** [comment]
I tested a version supplied by Francesco which (I assume) contains this change. Unfortunately I am getting many `java.util.concurrent.RejectedExecutionException: event executor terminated` within `netty`. It _is_ a bit faster than the other version off 100.12.1 that we tested before, though.

**Comment by gaboraranyossy-da** [comment]
That's a sign of in-flight/pending traffic after the reset has been called. Are you sure you don't have race conditions between the reset and other API requests? Another thing I would try is to set the overall timeout to non-zero like:  `_.shutdownGracefully(0L, 100L, TimeUnit.MILLISECONDS)`, just to see how it behaves.
