### PR TITLE
Fix issue in retrieving signed payloads from PostgreSQL

### LINKED ISSUE #8935: Signed payloads cannot be read from the database
A lack of testing with regards to reading out of the PostgreSQL-backed implementation of the non-repudiation storage lead to it simply not working.

Fix the issue and add proper tests.

_Originally posted by @cocreature in https://github.com/digital-asset/daml/pull/8916#discussion_r581766829_

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Closes #8935

Also adds tests for it and factors out functions shared across tests and benchmarks.

changelog_begin
changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: runtime-components/non-repudiation-postgresql/src/test/scala/com/daml/nonrepudiation/postgresql/TablesSpec.scala [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+  PayloadBytes,
+  SignatureBytes,
+  SignedPayload,
+}
+import com.daml.testing.postgresql.PostgresAroundEach
+import org.scalatest.OptionValues
+import org.scalatest.flatspec.AsyncFlatSpec
+import org.scalatest.matchers.should.Matchers
+
+final class TablesSpec
```
Comment (cocreature) [inline runtime-components/non-repudiation-postgresql/src/test/scala/com/daml/nonrepudiation/postgresql/TablesSpec.scala:22]: Totally fine for now but maybe worth considering for the future: property testing can work very well for these type of roundtrip tests.

**Review by cocreature — APPROVED** [review]
Thanks!

File: runtime-components/non-repudiation-postgresql/src/test/scala/com/daml/nonrepudiation/postgresql/TablesSpec.scala (hunk 1 above)
Comment (stefanobaghino-da) [reply runtime-components/non-repudiation-postgresql/src/test/scala/com/daml/nonrepudiation/postgresql/TablesSpec.scala:22]: Tracked by https://github.com/digital-asset/daml/issues/8946
