### PR TITLE
Fix data-deps dictionary function name mismatches.

### LINKED ISSUE #7362: Dictionary function names mismatch when using data-dependencies.
Dictionary function names are lost when going from DAML-LF back to DAML via data-dependencies, and we rely on the good will of ghc to provide the same names. In #7284 (which was resolved in #7361), this caused HasField instances to fail for parametrized types, because type var names weren't being preserved by the compiler.

But this underlying issue still causes problems when instance names depend on the order of declarations, as in this example.

Have the following module in one package:

```
module A where

data Foo t = Foo

instance Show (Foo Int) where
   show _ = "Foo @Int"
instance Show (Foo Bool) where
   show _ = "Foo @Bool"
instance Show (Foo Text) where
   show _ = "Foo @Text"
```

And in a separate package, import the previous via data-dependencies, and add the module:

```
module B where
import A

show1 : Foo Int -> Text
show1 = show

show2 : Foo Bool -> Text
show2 = show

show3 : Foo Text -> Text
show3 = show
```

This will compile correctly if and only if GHC happens to pick the same names for the dictionary functions when compiling the original DAML file for `A` and when compiling the stub for `A` generated by data-dependencies. My understanding is that, in this situation, dictionary function name is influenced by the order of the instance declarations, but given that GHC works in mysterious ways, sometimes reordering things behind the scenes, we should not depend on these names to be stable. 

One way to avoid this is to generate interface files directly in data-dependencies. Another approach is to find some way to record the original dictionary function names during stub generation, and rewrite references after GHC is done. Another is to replace GHC altogether.

### PR DESCRIPTION
**Pull request by sofiafaro-da**
Fixes #7362. Incredibly, it's possible to fix this issue in
data-dependencies by sorting instance names in a funny way.
This is definitely a hack, but it should fix this issue,
which affects overlapping instances as well.

This PR adds a regression test.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 1]
```diff
@@ -383,7 +384,7 @@ generateSrcFromLf env = noLoc mod
     -- | Generate instance declarations from dictionary functions.
     instanceDecls :: [Gen (Maybe (LHsDecl GhcPs))]
     instanceDecls = do
-        dval@LF.DefValue {..} <- NM.toList $ LF.moduleValues $ envMod env
+        dval@LF.DefValue {..} <- reverse . sortOn nameKey $ NM.toList $ LF.moduleValues $ envMod env
```
Comment (hurryabit) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs:387]:
```suggestion
        dval@LF.DefValue {..} <- sortOn (Down . nameKey) $ NM.toList $ LF.moduleValues $ envMod env
```

Comment (hurryabit) [reply compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs:387]: It's kind of surprising that you have to sort them in descending order. Strange...

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 2]
```diff
@@ -404,6 +405,21 @@ generateSrcFromLf env = noLoc mod
...
+        -- enough) order for recreating dictionary function names in GHC without
+        -- mismatches.
+        --
+        -- See issue #7362, and the corresponding regression test in the
+        -- packaging test suite.
+        nameKey :: LF.DefValue -> (T.Text, Maybe Int)
+        nameKey dval =
+            let name = LF.unExprValName (fst (LF.dvalBinder dval))
+                (intR,tagR) = T.span isDigit (T.reverse name)
+            in (T.reverse tagR, readMay (T.unpack (T.reverse intR)))
```
Comment (hurryabit) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs:422]: It's a bit sad that `Data.Text` doesn't have `spanEnd`, unlike `Data.Bytestring`. 😿

**Review by hurryabit — APPROVED** [review]
This is awesome. Thank you so much!

**Review by cocreature — APPROVED** [review]
Nice work tracking this down!
