### PR TITLE
purge all `Map#mapValues` from `daml-lf` codebase

### LINKED ISSUE #1861: GenTransaction#mapContractIdAndValue is lazy
The method `GenTransaction#mapContractIdAndValue(f, g)` evaluates its arguments `f` and `g` lazily. I.e. it does not evaluate `f` and `g` when it is called, but only later, when `tx.nodes.get(...)` is invoked on the resulting transaction `tx`.

This makes a difference, when `f` or `g` have side effects (e.g. logging) or throw exceptions.

The behavior is lazy, because the implementation uses `map.mapValues` which is itself lazy.

From my point of view, a caller expects eager evaluation. So this should be changed. If a change is not possible, I strongly suggest to mention in the ScalaDoc of all affected public methods, that they are lazy.

### PR DESCRIPTION
**Pull request by bitonic**
fixes #1861.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-lf/engine/src/main/scala/com/digitalasset/daml/lf/engine/Event.scala [hunk 1]
```diff
@@ -112,7 +112,8 @@ object Event {
     }
 
     def mapContractIdAndValue[Cid2, Val2](f: Cid => Cid2, g: Val => Val2): Events[Nid, Cid2, Val2] =
-      copy(events = events.mapValues(_.mapContractId(f, g)))
+      // do NOT use `Map#mapValues`! it applies the function lazily on lookup. see #1861
+      copy(events = events.transform { case (_, value) => value.mapContractId(f, g) })
```
Comment (S11001001) [inline daml-lf/engine/src/main/scala/com/digitalasset/daml/lf/engine/Event.scala]:
```suggestion
      copy(events = events.transform { (_, value) => value.mapContractId(f, g) })
```

and likewise elsewhere. (Scala does not optimize this, it does exactly the silliest thing you can imagine.)

Comment (bitonic) [reply daml-lf/engine/src/main/scala/com/digitalasset/daml/lf/engine/Event.scala]: done.
