### PR TITLE
Ensure HEX_TO_TEXT primitives generate valid UTF8

### LINKED ISSUE #22050: Ensure HEX_TO_TEXT primitives generate valid UTF8
CX made the following observations regarding the `HEX_TO_TEXT` LF primitive:
```
fromHex "68656c6c6f" == Some "hello" -- expected 
fromHex "6865c6c6f2" == Some "he\65533\65533\65533" -- unexpected
fromHex "68656c6c6f2" == None -- expected 
fromHex "0000b4334b" == Some "\NUL\NUL\65533\&3K" -- unexpected
fromHex "0000b4334b2" == None -- expected
```

From a user PoV, there is an expectation that (essentially) `forall hex: BytesHex @ (fromHex hex).map(toHex) == Some(hex)`. Here, this expectation is broken when `fromHex` (internally) decodes byte arrays into UTF8 strings. In this case, we follow a UTF8/Unicode [recommendation](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) and replace non-translatable UTF8 characters with `\65533`, which then breaks the users expectation.

Potential solutions:
- patch `HEX_TO_TEXT` so that an error state (be that an exception, `None` or whatever) is returned
    - as the underlying `SBDecoder` builtin is behaving in a reasonable manner (with a side effect of potential user surprise), this option is not preferred.
- patch the `HasFromHex (Optional Text)` Daml type instance so that we return `None` when a round trip translation can not occur
    - this option, with additional testing and documentation to describe this behaviour, is the preferred solution.

### PR DESCRIPTION
**Pull request by carlpulley-da**
Fixes #22050 

- [x] small tidy up refactor of SBDecodeHex
- [x] Refactor of `instance HasFromHex (Optional Text)` that ensures `fromHex` is injective
- [x] extra Daml testing for UTF8 strings containing replacement characters

### CODE REVIEW

File: sdk/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltinFun.scala [hunk 1]
```diff
@@ -812,22 +812,25 @@ private[lf] object SBuiltinFun {
...
+                  arg,
+                  cause = "can not parse hex string argument",
+                )
               )
-            )
-          )
-      }
+            ),
+          hexArg => {
+            val result = Ref.HexString.decode(hexArg).toStringUtf8
```
Comment (remyhaemmerle-da) [inline sdk/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltinFun.scala]: please use directly java stdlib to parse the byteString. 
We have to be sure the semantics of the parsing does not change as we update protobug dep.
