### PR TITLE
[JSON-API] Fix duplicate calls to the command service while debug logging is enabled

### LINKED ISSUE #12673: [BUG] The HTTP JSON API fetches from the ledger twice
I confirm that, if this is a bug that has security implications, I already contacted security@digitalasset.com and followed the [responsible disclosure policy](https://digitalasset.com/security/).

I confirm that this is not a question or a request for technical support by the community, for which the [Daml forum](https://discuss.daml.com/) is available.

# Affected Daml version

1.18.2

# Bug description

The following (redacted) piece of log shows that the same active contracts service request is issued twice to serve a single query:

```text
28-01-2022 11:38:06.199 [http-json-ledger-api-akka.actor.default-dispatcher-5] WARN  com.daml.http.Endpoints - missing HTTPS reverse-proxy request headers; for development launch with --allow-insecure-tokens, context: {instance_uuid: "a70f6239-76a6-4275-878d-7153e2709790", request_id: "6517b9c9-63c1-4c89-96dc-a0c5f4a1ef3b"}
28-01-2022 11:38:06.461 [http-json-ledger-api-akka.actor.default-dispatcher-5] DEBUG com.daml.http.Endpoints - Processing a query request, context: {ledger_id: "some-ledger", cmd: "GetActiveContractsRequest(OneAnd(TemplateId(Some(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949),Main,SomeTemplate),Set()),Map(),None)", request_id: "6517b9c9-63c1-4c89-96dc-a0c5f4a1ef3b", instance_uuid: "a70f6239-76a6-4275-878d-7153e2709790", application_id: "foobar", read_as: "List()", act_as: "List(Bob)"}
28-01-2022 11:38:07.338 [http-json-ledger-api-akka.actor.default-dispatcher-5] DEBUG com.daml.http.ContractsService - Searching in memory, parties: Set(Bob), templateIds: Set(TemplateId(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)), queryParms: Params(Map()), context: {ledger_id: "some-ledger", cmd: "GetActiveContractsRequest(OneAnd(TemplateId(Some(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949),Main,SomeTemplate),Set()),Map(),None)", request_id: "6517b9c9-63c1-4c89-96dc-a0c5f4a1ef3b", instance_uuid: "a70f6239-76a6-4275-878d-7153e2709790", application_id: "foobar", read_as: "List()", act_as: "List(Bob)"}
28-01-2022 11:38:07.484 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: RS downstream subscription registered.
28-01-2022 11:38:07.485 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: Starting call.
28-01-2022 11:38:07.508 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.rs.BufferingSubscription - Call 1: RS downstream signaled demand for 16 elements.
28-01-2022 11:38:07.509 [http-json-ledger-api-akka.actor.default-dispatcher-4] TRACE c.d.g.a.c.rs.DownstreamEventBuffer - Call 1: Demand of 15 buffered. Total buffered is 15.
28-01-2022 11:38:07.547 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000006:0,0075745ddf62a316f9b6f0b3d38f42a5ef135b71ad31aa2a95e4574c6eaf13c013,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(123))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.547 [http-json-ledger-api-akka.actor.default-dispatcher-4] TRACE c.d.g.a.c.rs.DownstreamEventBuffer - Call 1: Flushing demand for 15 elements. Remaining demand in buffer: 0
28-01-2022 11:38:07.548 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000007:0,00f08500c61bec7770f01afa6bda0f708c330a9e9da52a18c7e7ff370ab435d5ca,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(548))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.548 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000008:0,00f10ba00db1a1dc971c115765ad15988ac1e33fccb9f98dacb1f075e537483d01,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(999))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.548 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000009:0,007e095a02a59442b920b0fff86bea61e1e97e8bd90c3cf1e65bf017a658a22fd3,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(147))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.549 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: gRPC upstream emitted response message GetActiveContractsResponse(0000000000009745,,Vector()).
28-01-2022 11:38:07.549 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 1: gRPC upstream completed.
28-01-2022 11:38:07.583 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 2: RS downstream subscription registered.
28-01-2022 11:38:07.584 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 2: Starting call.
28-01-2022 11:38:07.586 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.rs.BufferingSubscription - Call 2: RS downstream signaled demand for 16 elements.
28-01-2022 11:38:07.586 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.rs.DownstreamEventBuffer - Call 2: Demand of 15 buffered. Total buffered is 15.
28-01-2022 11:38:07.593 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 2: gRPC upstream completed.
28-01-2022 11:38:07.607 [http-json-ledger-api-akka.actor.default-dispatcher-5] DEBUG com.daml.http.ContractsService - contracts fetch completed at: AbsoluteBookmark(0000000000009745), context: {ledger_id: "some-ledger", cmd: "GetActiveContractsRequest(OneAnd(TemplateId(Some(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949),Main,SomeTemplate),Set()),Map(),None)", request_id: "6517b9c9-63c1-4c89-96dc-a0c5f4a1ef3b", instance_uuid: "a70f6239-76a6-4275-878d-7153e2709790", application_id: "foobar", read_as: "List()", act_as: "List(Bob)"}
28-01-2022 11:38:07.611 [http-json-ledger-api-akka.actor.default-dispatcher-5] INFO  com.daml.http.Endpoints - Responding to client with HTTP 200 OK, context: {instance_uuid: "a70f6239-76a6-4275-878d-7153e2709790", request_id: "6517b9c9-63c1-4c89-96dc-a0c5f4a1ef3b", response_body: {result: [{agreementText: "", contractId: "0075745ddf62a316f9b6f0b3d38f42a5ef135b71ad31aa2a95e4574c6eaf13c013", observers: [], payload: {someField: "123", operator: "Bob"}, signatories: ["Bob"], templateId: "2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949:Main:SomeTemplate"}, {agreementText: "", contractId: "00f08500c61bec7770f01afa6bda0f708c330a9e9da52a18c7e7ff370ab435d5ca", observers: [], payload: {someField: "548", operator: "Bob"}, signatories: ["Bob"], templateId: "2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949:Main:SomeTemplate"}, {agreementText: "", contractId: "00f10ba00db1a1dc971c115765ad15988ac1e33fccb9f98dacb1f075e537483d01", observers: [], payload: {someField: "999", operator: "Bob"}, signatories: ["Bob"], templateId: "2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949:Main:SomeTemplate"}, {agreementText: "", contractId: "007e095a02a59442b920b0fff86bea61e1e97e8bd90c3cf1e65bf017a658a22fd3", observers: [], payload: {someField: "147", operator: "Bob"}, signatories: ["Bob"], templateId: "2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949:Main:SomeTemplate"}], status: 200}}
28-01-2022 11:38:07.614 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE com.daml.http.Endpoints - Processed request after 1431108137ns, context: {instance_uuid: "a70f6239-76a6-4275-878d-7153e2709790", request_id: "6517b9c9-63c1-4c89-96dc-a0c5f4a1ef3b"}
28-01-2022 11:38:07.628 [http-json-ledger-api-akka.actor.default-dispatcher-9] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: RS downstream subscription registered.
28-01-2022 11:38:07.628 [http-json-ledger-api-akka.actor.default-dispatcher-9] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: Starting call.
28-01-2022 11:38:07.629 [http-json-ledger-api-akka.actor.default-dispatcher-9] TRACE c.d.g.a.c.rs.BufferingSubscription - Call 3: RS downstream signaled demand for 16 elements.
28-01-2022 11:38:07.629 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.rs.DownstreamEventBuffer - Call 3: Demand of 15 buffered. Total buffered is 15.
28-01-2022 11:38:07.659 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000006:0,0075745ddf62a316f9b6f0b3d38f42a5ef135b71ad31aa2a95e4574c6eaf13c013,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(123))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.660 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.rs.DownstreamEventBuffer - Call 3: Flushing demand for 15 elements. Remaining demand in buffer: 0
28-01-2022 11:38:07.661 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000007:0,00f08500c61bec7770f01afa6bda0f708c330a9e9da52a18c7e7ff370ab435d5ca,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(548))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.661 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000008:0,00f10ba00db1a1dc971c115765ad15988ac1e33fccb9f98dacb1f075e537483d01,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(999))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.662 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: gRPC upstream emitted response message GetActiveContractsResponse(,,Vector(CreatedEvent(#0000000000000009:0,007e095a02a59442b920b0fff86bea61e1e97e8bd90c3cf1e65bf017a658a22fd3,Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),None,Some(Record(Some(Identifier(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949,Main,SomeTemplate)),Vector(RecordField(operator,Some(Value(Party(Bob)))), RecordField(someField,Some(Value(Text(147))))))),Vector(Bob),Vector(Bob),Vector(),Some()))).
28-01-2022 11:38:07.662 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: gRPC upstream emitted response message GetActiveContractsResponse(0000000000009745,,Vector()).
28-01-2022 11:38:07.662 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 3: gRPC upstream completed.
28-01-2022 11:38:07.664 [http-json-ledger-api-akka.actor.default-dispatcher-9] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 4: RS downstream subscription registered.
28-01-2022 11:38:07.664 [http-json-ledger-api-akka.actor.default-dispatcher-9] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 4: Starting call.
28-01-2022 11:38:07.665 [http-json-ledger-api-akka.actor.default-dispatcher-9] TRACE c.d.g.a.c.rs.BufferingSubscription - Call 4: RS downstream signaled demand for 16 elements.
28-01-2022 11:38:07.665 [http-json-ledger-api-akka.actor.default-dispatcher-5] TRACE c.d.g.a.c.rs.DownstreamEventBuffer - Call 4: Demand of 15 buffered. Total buffered is 15.
28-01-2022 11:38:07.672 [grpc-default-executor-2] TRACE c.d.g.a.c.r.BufferingResponseObserver - Call 4: gRPC upstream completed.
28-01-2022 11:38:07.674 [http-json-ledger-api-akka.actor.default-dispatcher-5] DEBUG com.daml.http.ContractsService - contracts fetch completed at: AbsoluteBookmark(0000000000009745), context: {ledger_id: "some-ledger", cmd: "GetActiveContractsRequest(OneAnd(TemplateId(Some(2c0a02b11c351a04e4b6735ac3cb4a8fe6bb99c82930b2ca360f715445b9b949),Main,SomeTemplate),Set()),Map(),None)", request_id: "6517b9c9-63c1-4c89-96dc-a0c5f4a1ef3b", instance_uuid: "a70f6239-76a6-4275-878d-7153e2709790", application_id: "foobar", read_as: "List()", act_as: "List(Bob)"}
```

# To reproduce

1. set up the HTTP JSON API to log at `TRACE` level
2. start the HTTP JSON API
3. shoot a query at `POST /v1/query` asking for a specific template
4. examine your logs

# Expected behavior

For each downstream query, the HTTP JSON API performs exactly one active contracts request followed by at most one flat transaction request.

# Additional context

- in this case in particular, the in-memory store was used.
- due to the relevance of the issue, the eventual solution should probably be backported

### PR DESCRIPTION
**Pull request by realvictorprm**
Fixes #12673.

Need to think further about whether I should apply the same to the input.

changelog_begin

- [HTTP-JSON] Fixed duplicate calls to the command service while debug logging is enabled.

changelog_end

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by realvictorprm** [comment]
The new changes will now omit logging the request/response body if the body is either too big or the size is not known. Moreover it will specifically report in the context why it was omitted including the info whether the request/response was chunked.

```
16:12:46.893 [HttpServiceIntegrationTest-akka.actor.default-dispatcher-5] INFO  com.daml.http.Endpoints - Responding to client with HTTP 200 OK, context: {instance_uuid: "08add3bd-a71a-43a4-b560-cd89ac033aee", request_id: "30a1000c-7e38-438f-a27d-bbc452a4dccd", response_body: "OMITTED BECAUSE REQUEST BODY IS CHUNKED & OVERALL SIZE IS UNKNOWN"}
```

I had to implement this, because logging the request/response body always requires that the body is completely available in the memory which sometimes is not possible because either a) the body is really too big or b) we run into the configured limits of the json api which are currently 1 MiB for body materialization which was the case for one test in our test suite.

Besides all that I also noticed that at a certain length of the logging message, the message seems to be minimized by `...` such that I decided to only include bodies in the logging context which have a size of less than 10 KiB (because that is already pretty big).

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala [hunk 1]
```diff
@@ -120,38 +122,65 @@ class Endpoints(
...
           .contains(ContentTypes.`application/json`)
-      )
-        httpMessage
-          .entity()
-          .toStrict(maxTimeToCollectRequest)
-          .map(it =>
+      ) {
+        httpMessage.entity.contentLengthOption match {
+          // Limit logging of bodies to content with size of less than 10 KiB
+          case Some(length) if length < 1024 * 10 =>
```
Comment (stefanobaghino-da) [inline ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:145]: I would recommend extracting this magical number into its own variable and giving it a name, e.g. `HttpRequestBodyLoggingSizeLimit`.

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala [hunk 2]
```diff
@@ -120,38 +122,65 @@ class Endpoints(
...
+            import akka.stream.scaladsl._
+            logger.debug("Calling transformEntityDataBytes")
```
Comment (stefanobaghino-da) [inline ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:147]: Should this be at `trace` level?

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala [hunk 3]
```diff
@@ -120,38 +122,65 @@ class Endpoints(
...
+                }
+              )
+          case other =>
+            val ctxContent = other
+              .map(length => s"OMITTED BECAUSE BODY SIZE OF $length IS TOO BIG FOR LOGGING")
+              .getOrElse {
+                if (httpMessage.entity.isChunked())
+                  "OMITTED BECAUSE REQUEST BODY IS CHUNKED & OVERALL SIZE IS UNKNOWN"
+                else
+                  "OMITTED BECAUSE REQUEST BODY SIZE IS UNKNOWN"
```
Comment (stefanobaghino-da) [inline ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:171]: This was probably good for debugging, but this should be capitalized normally going forward.

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala [hunk 4]
```diff
@@ -120,38 +122,65 @@ class Endpoints(
...
+              .transformEntityDataBytes(
+                Flow.fromFunction { it =>
+                  try {
+                    withEnrichedLoggingContext(
+                      LoggingContextOf.label[RequestEntity],
+                      s"${kind}_body" -> it.utf8String.parseJson,
+                    )
+                      .run { implicit lc => logger.info(msg) }
+                  } catch {
+                    case ex: Exception =>
```
Comment (stefanobaghino-da) [inline ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:158]: Prefer using [`NonFatal`](https://www.scala-lang.org/api/2.13.3/scala/util/control/NonFatal$.html).

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala [hunk 5]
```diff
@@ -120,38 +122,65 @@ class Endpoints(
...
-          }
-      else Future.successful(logger.info(msg))
+              s"${kind}_body" -> ctxContent,
+            ).run { implicit lc => logger.info(msg) }
+            httpMessage
+        }
+      } else {
+        logger.info(msg)
+        httpMessage
+      }
```
Comment (stefanobaghino-da) [inline ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:182]: There's a lot of nesting and apparently some repetition within these method. Would it be possible to factor out those parts that seem to do similar things

1.
```
                    withEnrichedLoggingContext(
                      LoggingContextOf.label[RequestEntity],
                      s"${kind}_body" -> it.utf8String.parseJson,
                    )
                      .run { implicit lc => logger.info(msg) }
```
2.
```
              s"${kind}_body" -> ctxContent,
            ).run { implicit lc => logger.info(msg) }
            httpMessage
```
3.
```
        logger.info(msg)
        httpMessage
```

and possibly reduce the nesting by extracting methods and flattening the nested `other.map` into part of the `match` expression?

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala (hunk 2 above)
Comment (realvictorprm) [reply ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:147]: Forgot to remove that one, thanks :facepalm:

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala (hunk 3 above)
Comment (realvictorprm) [reply ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:171]: OK :)

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala [hunk 6]
```diff
@@ -120,38 +122,65 @@ class Endpoints(
...
+        } yield transformedResponse
       }
     }
 
   private def logJsonRequestAndResult(implicit
       lc: LoggingContextOf[InstanceUUID with RequestID]
   ): Directive0 = {
-    def logWithHttpMessageBodyIfAvailable(
-        httpMessage: HttpMessage,
+    def logWithHttpMessageBodyIfAvailable[A <: HttpMessage](
```
[the remark this answers is not in the document]
Comment (realvictorprm) [reply ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:132]: That thing is obsolete, there was a reason for it but I didn't need it after all. Thanks for the suggestion!

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala (hunk 1 above)
Comment (realvictorprm) [reply ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:145]: Yeah good idea, will add minimal explanation why I chose 10 KiB too.

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala (hunk 4 above)
Comment (realvictorprm) [reply ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:158]: Okey-doke :)

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala (hunk 5 above)
Comment (realvictorprm) [reply ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:182]: I agree that this can be improved. Will reduce duplication here as possible.

File: ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala [hunk 7]
```diff
@@ -95,23 +101,25 @@ class Endpoints(
...
+        logIncomingRequest(request, remoteAddress).asInstanceOf[HttpRequest]
+      ) & mapRouteResultFuture { responseF =>
         for {
-          _ <- logIncomingRequest(request, remoteAddress)
           response <- responseF
-          _ <- response match {
-            case Complete(httpResponse) => logResponse(httpResponse)
+          transformedResponse <- response match {
+            case Complete(httpResponse) =>
+              Future.successful(Complete(logResponse(httpResponse).asInstanceOf[HttpResponse]))
```
Comment (S11001001) [inline ledger-service/http-json/src/main/scala/com/digitalasset/http/Endpoints.scala:122]: Please don't cast.

**Comment by realvictorprm** [comment]
What shall I do instead here? I sadly have to cast :(

Stephen Compall ***@***.***> schrieb am Mi., 9. Feb. 2022,
19:00:

**Comment by S11001001** [comment]
> What shall I do instead here? I sadly have to cast :(

a38f78f0c207882438697a8df70b5f5cf5f668a0

**Comment by S11001001** [comment]
To expand on this, most APIs that tie [a knot like this](https://github.com/akka/akka-http/blob/664142ee803c627ee0582b1a5e34788b6cd5513a/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala#L38) have some kind of ["identity"](https://github.com/akka/akka-http/blob/664142ee803c627ee0582b1a5e34788b6cd5513a/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala#L39), _conceptually_, that lets you jump through one loop without doing anything.

* Scala collections library: [knot](https://www.scala-lang.org/api/2.13.8/scala/collection/immutable/SeqOps.html), identity: `C <: SeqOps[..., ..., C]`
* akka streams: [knot](https://doc.akka.io/api/akka/current/akka/stream/scaladsl/Source.html#Repr%5B+O%5D=akka.stream.scaladsl.Source%5BO,Mat@scala.annotation.unchecked.uncheckedVariance%5D), identity: `R[+X] <: FlowOps[O, M] {type Repr[+X] = R[X]}`
* our Scala codegen: [knot](https://github.com/digital-asset/daml/blob/449a68cb33e866a78faef7a58c8e359a9e231f3b/language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Template.scala#L9), [identity](https://github.com/digital-asset/daml/blob/449a68cb33e866a78faef7a58c8e359a9e231f3b/language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/TemplateCompanion.scala#L49)

The reason is exactly as you might have discovered: the knot lets you do one or more operations that all conform to the same `Self` abstractions, but zero operations (i.e. return the argument) is trickier to describe as conforming to the knot at the type level.

Forgive me for wildly speculating about your state of mind while writing this, because the implications are interesting. You might have tried to do something of the form

```scala
[A <: HttpMessage](m: A): A
```

only to discover that you couldn't get the return values to conform to `A`. But worry not, there was never a way to get that to work. The above signature is [method-equivalent](https://typelevel.org/blog/2015/07/16/method-equiv.html), and you can perform the test described there to prove this, to

```scala
(m: HttpMessage): m.type
```

In other words, the argument is the only value that conforms to the result type.

That doesn't mean the signature that (I wager) you tried is *useless*, far from it! It conveys exactly the same information as the `m.type` version—the result is the argument—but in a Java-compatible way, notwithstanding `null` shenanigans.

The best indicator is that `A` occurs as the argument type, but nowhere else.  Compare [our NonEmpty](https://github.com/digital-asset/daml/blob/d2e2c21684e2d9eade40f74990208125ad4b4ccb/libs-scala/scala-utils/src/main/scala/com/daml/scalautil/nonempty/NonEmpty.scala#L120), where `C` occurs as a parameter instead (and can therefore occur in the signatures of the type's associated operations).

If you're designing an API, it's much simpler to use typeclasses if you can, because the knot comes for free, and there's one obvious way to do it that just works, instead of a bunch of weird variations with slightly varying semantics. Expanding on _that_ idea would be going on a bit, though.

**Review by S11001001 — APPROVED** [review]
