### PR TITLE
damlc: fix: relative output path relative to cwd

### LINKED ISSUE #7913: daml build output path is relative to project root instead of being relative to current directory.
From @tamaskalcza-da : https://discuss.daml.com/t/output-path-is-not-relative-from-current-location/1596

When running `daml build --project-root PATH1 --output PATH2` the `PATH2` seems to be relative to the project root (`PATH1`) instead of being relative to the current directory. That's unexpected and confusing for users.

### PR DESCRIPTION
**Pull request by robin-da**
This fixes #7913. Build output paths were considered relative to the
project root instead of the current working directory.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Review by cocreature — APPROVED** [review]
nice, thanks! maybe worth writing a test for but it’s also small enough that I’ll leave it up to you.

File: compiler/damlc/lib/DA/Cli/Damlc.hs [hunk 1]
```diff
@@ -599,11 +599,13 @@ execBuild projectOpts opts mbOutFile incrementalBuild initPkgDb =
...
-                    let fp = targetFilePath $ unitIdString (pkgNameVersion pName pVersion)
+                    fp <- targetFilePath relativize $ unitIdString (pkgNameVersion pName pVersion)
                     createDarFile fp dar
             where
-                targetFilePath name = fromMaybe (distDir </> name <.> "dar") mbOutFile
-
+                targetFilePath rel name =
+                  case mbOutFile of
+                    Nothing -> pure $ distDir </> name <.> "dar"
+                    Just out -> rel out
```
Comment (hurryabit) [inline compiler/damlc/lib/DA/Cli/Damlc.hs:608]: I don't think we need to pass `relativize` as an argument, do we?
```suggestion
                    Just out -> relativize out
```

**Review by hurryabit — APPROVED** [review]
Very nice. Thank you.

File: compiler/damlc/lib/DA/Cli/Damlc.hs (hunk 1 above)
Comment (robin-da) [reply compiler/damlc/lib/DA/Cli/Damlc.hs:608]: looks like we do, I think because the `where` clause is not relative to the lambda.

File: compiler/damlc/tests/src/DA/Test/Packaging.hs [hunk 2]
```diff
@@ -801,6 +805,24 @@ tests Tools{damlc} = testGroup "Packaging" $
...
+            ]
+          writeFileUTF8 (dir </> "A.daml") $ unlines
+            [ "module A where"
+            , "dep1 = 0"
+            ]
+          let outDir = dir </> "out"
+          createDirectoryIfMissing True outDir
+          withCurrentDirectory outDir $
+            callProcessSilent damlc ["build", "--project-root", dir, "-o", "A.dar"]
+          assertFileExists $ outDir </> "A.dar"
```
Comment (hurryabit) [inline compiler/damlc/tests/src/DA/Test/Packaging.hs:825]: Nice!

**Comment by sofiafaro-da** [comment]
Very nice, thank you!
