### PR TITLE
Disable Multi-IDE for older Daml

### LINKED ISSUE #19869: Daml Studio 2.9x error, "Invalid argument `multi-ide'" for older projects
# Affected Daml version

In VS Code, opening 2.8.x or earlier projects with the 2.9.1 - 2.9.4 Daml Extension.

# Bug description

As reported [in the forums](https://discuss.daml.com/t/run-script-results-in-older-sdk-version/7364?u=wallacekelly), if you open a 2.8.x or earlier project using a 2.9.x Daml Extension, then VS Code displays:

```
The Daml Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

The Daml Language Server output includes the following:

```
Invalid argument `multi-ide`
```

The "script results" link does not appear above Daml script functions in the editor.

# To reproduce

1. In the Daml Extension settings, enable the early access feature, "Multi Package Ide Support".  

2. Create a 2.8.9 Daml project.
```
DAML_SDK_VERSION=2.8.9 daml new daml289
```

3. Use VS Code's "Install Specific Version" feature to alternately install the 2.9.4 and then the 2.8.9 extension.

image

4. Observe the following:

* The 2.9.4 extension _fails_ with the 2.8.9 project.
* The 2.8.9 extension _works_ with the 2.8.9 project.

# Expected behavior

The latest Daml Extension is compatible with projects built with previous Daml SDK versions.

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Resolves #19869

### CODE REVIEW

File: sdk/compiler/daml-extension/src/extension.ts [hunk 1]
```diff
@@ -318,10 +332,28 @@ function getLanguageServerArgs(
...
+    "selected by env var ",
+    "project SDK version from daml.yaml",
+    "default SDK version for new projects",
+  ];
+  const { stdout } = await exec(damlPath + " version", { cwd: projectPath });
+  const lines = stdout.split("\n");
+  for (const selection of selectionStrings) {
+    const line = lines.find((line: string) => line.includes(selection));
+    if (line) return line.trim().split(" ")[0];
+  }
```
Comment (samuel-williams-da) [inline sdk/compiler/daml-extension/src/extension.ts:350]: Considered using something like `daml exec env` or `daml exec printenv DAML_SDK_VERSION`, but the windows equivalents are messy

File: sdk/compiler/daml-extension/src/extension.ts [hunk 2]
```diff
@@ -285,8 +288,19 @@ function addIfInConfig(
...
   config: vscode.WorkspaceConfiguration,
   telemetryConsent: boolean | undefined,
+  sdkVersion: string | undefined,
 ): string[] {
-  const multiIDESupport = config.get("multiPackageIdeSupport");
+  let multiIDESupport = config.get("multiPackageIdeSupport");
+
+  // We'll say multi-ide is introduced in 2.9.0. The command existed
+  // in 2.8, but it was unfinished, so we shouldn't allow it to be used.
+  if (sdkVersion && sdkVersion != "0.0.0" && semver.lt(sdkVersion, "2.9.0")) {
```
Comment (moisesackerman-da) [inline sdk/compiler/daml-extension/src/extension.ts:297]: small suggestion, to avoid showing the warning when `multiPackageIdeSupport` is already off or undefined

```suggestion
  if (multiIDESupport && sdkVersion && sdkVersion != "0.0.0" && semver.lt(sdkVersion, "2.9.0")) {
```

Comment (samuel-williams-da) [reply sdk/compiler/daml-extension/src/extension.ts:297]: Oh! :facepalm: of course - good catch

File: sdk/compiler/daml-extension/src/extension.ts [hunk 3]
```diff
@@ -318,10 +332,28 @@ function getLanguageServerArgs(
...
+  const selectionStrings = [
+    "selected by env var ",
+    "project SDK version from daml.yaml",
+    "default SDK version for new projects",
+  ];
+  const { stdout } = await exec(damlPath + " version", { cwd: projectPath });
+  const lines = stdout.split("\n");
+  for (const selection of selectionStrings) {
+    const line = lines.find((line: string) => line.includes(selection));
+    if (line) return line.trim().split(" ")[0];
```
Comment (moisesackerman-da) [inline sdk/compiler/daml-extension/src/extension.ts:349]: this feels a bit brittle, since we might inadvertently change the `daml version` output. perhaps we could add a flag to `daml version` that prints _only_ the version of daml that's active in cwd - no need to address it now, though.

Comment (samuel-williams-da) [reply sdk/compiler/daml-extension/src/extension.ts:349]: The problem with that is that it won't work with old versions. I need this check to essentially work in all of 2.9 at least.
I had considered a check where I just run `daml multi-ide --help` first, and see if that launches
but 2.8 has a worse version of multi-ide :/

I agree that such a flag would be _very_ helpful. We could even have a `json` flag, to make the output info easier to consume

Comment (moisesackerman-da) [reply sdk/compiler/daml-extension/src/extension.ts:349]: aaaah yes backwards compatibility fun :(

Comment (samuel-williams-da) [reply sdk/compiler/daml-extension/src/extension.ts:354]: Endless fun for the whole family!

**Review by moisesackerman-da — APPROVED** [review]
oops, i forgot to actually approve 😅. thanks @samuel-williams-da!

File: sdk/compiler/daml-extension/src/extension.ts (hunk 3 above)
Comment (samuel-williams-da) [reply sdk/compiler/daml-extension/src/extension.ts:354]: Note to self, leave comment on the daml version code saying to update this
