### PR TITLE
hunt down DAML better

### LINKED ISSUE #13190: Fix remaining incorrect spelling of Daml
There are some place where we still have Daml spelled as an acronym. As the name no longer stands for anything, it would be nice to remove those. Some care should be taken as some occurrences are valid (e.g. in environment variables) so you cannot really do a batch re-write of all occurrences.

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Process:

- `git ls-files -z | xargs -0 -n 100 sed -i --follow-symlinks 's/DAML/Daml/g'`
- `git add -p`
- `git restore -p`
- Check there is no unstaged change left.

To review:

- Check for false positives by carefully reviewing the diff in this PR.
- Check for false negatives with `git grep DAML`.
- Quicker check for fals positives:

```
git grep DAML | grep -v migration | grep -v DAML_
```

Fixes #13190

Note: This is the "second half" of #13191, which failed to cover all the
remaining DAMLs because of:

```
$ git ls-files | grep "'"
compiler/damlc/tests/daml-test-files/MangledScenario'.daml
```

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

File: compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs [hunk 1]
```diff
@@ -104,7 +104,7 @@ featureBigNumeric = Feature
 
 featureExceptions :: Feature
 featureExceptions = Feature
-    { featureName = "DAML Exceptions"
+    { featureName = "Daml Exceptions"
```
Comment (stefanobaghino-da) [inline compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:107]: @remyhaemmerle-da does this string need to remain capitalized as before for some reason? Same with the one below.

File: compiler/damlc/tests/daml-test-files/Text.daml [hunk 2]
```diff
@@ -296,7 +296,7 @@ testNuls = scenario do
   "\0" === "\0"
   "£" === "£"
   "£\0" === "£\0"
-  "\0DAML" === "\0DAML"
+  "\0Daml" === "\0Daml"
   "DA\0ML" === "DA\0ML"
```
Comment (remyhaemmerle-da) [inline compiler/damlc/tests/daml-test-files/Text.daml:300]: Should you add this one also?

File: compiler/damlc/tests/daml-test-files/Text.daml [hunk 3]
```diff
@@ -310,7 +310,7 @@ testCodePoints = scenario do
 testAsciiToLower = scenario do
   T.asciiToLower "HELLO WORLD" === "hello world"
   T.asciiToLower "HELLO world" === "hello world"
-  T.asciiToLower "\0DAML" === "\0daml"
+  T.asciiToLower "\0Daml" === "\0daml"
   T.asciiToLower "DA\0⛄ML" === "da\0⛄ml"
```
Comment (remyhaemmerle-da) [inline compiler/damlc/tests/daml-test-files/Text.daml:314]: here as well.

File: daml-assistant/src/DA/Daml/Assistant/Env.hs [hunk 4]
```diff
@@ -83,7 +83,7 @@ getLatestStableSdkVersion damlPath cachePath =
 testDamlEnv :: Env -> IO (Maybe Text)
 testDamlEnv Env{..} = firstJustM (\(test, msg) -> unlessMaybeM test (pure msg))
     [ ( doesDirectoryExist (unwrapDamlPath envDamlPath)
-      ,  "The daml home directory does not exist. Please check if DAML_HOME is incorrectly set, "
+      ,  "The Daml home directory does not exist. Please check if DAML_HOME is incorrectly set, "
```
Comment (stefanobaghino-da) [inline daml-assistant/src/DA/Daml/Assistant/Env.hs:86]: This makes sense to me, but probably worth having an extra pair of eyeballs from language confirming.

**Review by remyhaemmerle-da — APPROVED** [review]
Thanks.

File: docs/theme/da_theme_skeleton/navbar.html [hunk 5]
```diff
@@ -2,7 +2,7 @@
 <!-- SPDX-License-Identifier: Apache-2.0 -->
 
 <div class="navbar">
-    <h1><img src="{{ pathto('_static/images/DAML_Logo_Blue.svg', 1) }}"></h1>
+    <h1><img src="{{ pathto('_static/images/Daml_Logo_Blue.svg', 1) }}"></h1>
```
Comment (stefanobaghino-da) [inline docs/theme/da_theme_skeleton/navbar.html:5]: Was this file renamed appropriately?

File: ledger/participant-integration-api/src/main/resources/db/migration/oracle-appendonly/V1__Append_only_schema.sql [hunk 6]
```diff
@@ -18,13 +18,13 @@ CREATE TABLE packages
...
     source_description NVARCHAR2(1000),
-    -- The size of the archive payload (i.e., the serialized DAML-LF package), in bytes
+    -- The size of the archive payload (i.e., the serialized Daml-LF package), in bytes
     package_size       NUMBER                     not null,
     -- The time when the package was added
     known_since        NUMBER                     not null,
     -- The ledger end at the time when the package was added
     ledger_offset      VARCHAR2(4000)             not null,
-    -- The DAML-LF archive, serialized using the protobuf message `daml_lf.Archive`.
+    -- The Daml-LF archive, serialized using the protobuf message `daml_lf.Archive`.
```
Comment (stefanobaghino-da) [inline ledger/participant-integration-api/src/main/resources/db/migration/oracle-appendonly/V1__Append_only_schema.sql:27]: Touching database migration files could cause issues as their content is hashed and check by the migration tool (that's why these files are excluded from copyright notice changes -- notice it still says 2021 up on top).

**Review by stefanobaghino-da — COMMENTED** [review]
Looks mostly OK, I left a couple of notes and recommend someone from the language team having a second look.

File: compiler/damlc/tests/daml-test-files/Text.daml (hunk 2 above)
Comment (garyverhaegen-da) [reply compiler/damlc/tests/daml-test-files/Text.daml:300]: Yes; will do. Thanks!

File: docs/theme/da_theme_skeleton/navbar.html (hunk 5 above)
Comment (garyverhaegen-da) [reply docs/theme/da_theme_skeleton/navbar.html:5]: 🤦 

Yes, it was, on my local machine. On a case-insensitive filesystem. I'm so not used to that. 😿

File: compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs (hunk 1 above)
Comment (remyhaemmerle-da) [reply compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:107]: Does this was added after we change the capitalization ? 
@sofiafaro-da  what do you think ?

File: ledger/participant-integration-api/src/main/resources/db/migration/oracle-appendonly/V1__Append_only_schema.sql (hunk 6 above)
Comment (remyhaemmerle-da) [reply ledger/participant-integration-api/src/main/resources/db/migration/oracle-appendonly/V1__Append_only_schema.sql:27]: We should probably not touch this file.

Comment (garyverhaegen-da) [reply ledger/participant-integration-api/src/main/resources/db/migration/oracle-appendonly/V1__Append_only_schema.sql:27]: I tried very hard to avoid those. I avoided so many of them!

Will restore that one. Thanks for noticing!

File: compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs (hunk 1 above)
Comment (garyverhaegen-da) [reply compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:107]: For what it's worth:

```
$ git grep featureName
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName :: !T.Text
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "String interning"
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "Type interning"
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "Unstable, experimental features"
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "BigNumeric type"
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "Daml Exceptions"
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "Nat type synonyms"
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "Daml Interfaces"
compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:    { featureName = "Daml Experimental"
compiler/daml-lf-proto/src/DA/Daml/LF/Proto3/EncodeV1.hs:    | otherwise = error $ "Daml-LF " ++ renderPretty version ++ " cannot encode feature: " ++ T.unpack (featureName feature)
compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/Error.hs:      "unsupported feature:" <-> pretty featureName
```

So:

* Other features are not all caps.
* It looks like this field is only used for error reporting towards humans.

So my impression is that this is a safe change, at least given that there's a changelog entry that says error messages have changed (from #13191).

Comment (sofiafaro-da) [reply compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:107]: This is safe! Thanks for checking!

Comment (stefanobaghino-da) [reply compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Version.hs:107]: Thanks for lending a couple of extra eyeballs. 🙇🏻‍♂️ 👀 I'll consider this item solved.

File: daml-assistant/src/DA/Daml/Assistant/Env.hs (hunk 4 above)
Comment (stefanobaghino-da) [reply daml-assistant/src/DA/Daml/Assistant/Env.hs:86]: Given that @remyhaemmerle-da already reviewed this and gave a green light and given that this is CLI feedback text, I believe it's safe to consider this item safe and resolve it.
