### PR TITLE
Trigger: return less confusing message when trigger is not found.

### LINKED ISSUE #13893: Internal wrapped expression type is returned by the Trigger service in an error message.
### What is the problem you want to solve?

When the trigger service is requested to run a trigger and the name is of the wrong type, an HTTP 422 (Unprocessable Entity) is returned with a message that refers to the full type of the expression built in the trigger service that will run the trigger. This makes the original type mangled and the possible resolution confusing to understand. When trying to "run" a TriggerA instead of a Trigger, this message was returned:
```
{
"errors": [
"TForall((s,KStar),TApp(TApp(TBuiltin(BTArrow),TBuiltin(BTParty)),TApp(TApp(TTyCon(06430080c9d08699ebbbc1b7a581b6a49241f44cbb0505fcb12144a57ae61c5f:Daml.Trigger.Internal:TriggerA),TVar(s)),TBuiltin(BTUnit)))) is not a valid type for a trigger"
],
"status": 422
}
```

### What is the solution you would propose?

Return the original type the trigger service was asked to run.

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
fixes #13893

CHANGELOG_BEGIN
CHANGELOG_END

### CODE REVIEW

File: triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala [hunk 1]
```diff
@@ -140,39 +140,39 @@ object Trigger extends StrictLogging {
...
-        val triggerState = TTyCon(triggerIds.damlTriggerInternal("TriggerState"))
-        val stateTy = TApp(triggerState, tyArg)
-        val lowLevelTriggerTy = triggerIds.damlTriggerLowLevel("Trigger")
-        val ty = TypeConApp(lowLevelTriggerTy, ImmArray(stateTy))
-
-        Right(TypedExpr(expr, ty))
-      } else {
-        Left(s"Unexpected trigger type constructor $tyCon")
+    def detectTriggerType(triggerId: Identifier): Either[String, TypedExpr] = {
+      def error = Left(s"unknown trigger $triggerId")
```
Comment (cocreature) [inline triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala:144]: I think I don’t understand how this actually solves the issue. If I read this code correctly you’re now producing the same error for an identifier that doesn’t exist and one that has the wrong type. That seems pretty confusing. If you just want to shorten it maybe don’t print the actual type but print something like "identifier $triggerId is not a trigger".

Comment (remyhaemmerle-da) [reply triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala:144]: Is `s"identifier $triggerId is not a trigger"` very different from `s"unknown trigger $triggerId"` ?

Comment (cocreature) [reply triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala:144]: I think there are two user errors I can make:
1. I know the trigger I’m trying to reference and it really is a trigger but I typoed the name so there is nothing with that identifier.
2. I don’t really understand what I’m supposed to reference so I referenced the trigger rule instead of the trigger or something like that. The identifier exists but it has the wrong type.

I think providing enough info that users can distinguish which of the two they hit is useful.

File: triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala [hunk 2]
```diff
@@ -137,42 +137,54 @@ object Trigger extends StrictLogging {
       triggerId: Identifier,
   )(implicit loggingContext: LoggingContextOf[Trigger]): Either[String, Trigger] = {
 
+    def error(triggerId: Identifier, ty: Type): Left[String, Nothing] = {
+      val triggerIds = TriggerIds(Ref.PackageId.assertFromString("-"))
+      val highLevelTrigger = TTyCon(triggerIds.damlTrigger("Trigger"))
+      val lowLevelTrigger = TTyCon(triggerIds.damlTriggerLowLevel("Trigger"))
+      val a = TVar(Name.assertFromString("a"))
+      Left(
+        s"the definition $triggerId has not a valid trigger type: " +
```
Comment (cocreature) [inline triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala:146]:
```suggestion
        s"the definition $triggerId does not have valid trigger type: " +
```

File: triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala [hunk 3]
```diff
@@ -137,42 +137,54 @@ object Trigger extends StrictLogging {
...
+          "expected a type of the form " +
+          s"(${TApp(highLevelTrigger, a).pretty}) or (${TApp(lowLevelTrigger, a).pretty}) " +
+          s"but get (${ty.pretty})"
```
Comment (cocreature) [inline triggers/runner/src/main/scala/com/digitalasset/daml/lf/engine/trigger/Runner.scala:149]:
```suggestion
          s"but got (${ty.pretty})"
```

**Review by cocreature — APPROVED** [review]
thanks!

**Comment by stefanobaghino-da** [comment]
It's too bad this improvement doesn't have a visible change log entry. 😢
