### PR TITLE
Fix rare out of order transaction delivery on the ledger api

### LINKED ISSUE #7521: find consistent failing cases in random transaction stream testing
With #7482, the test "fall back to limit-based query with consistent results" fails occasionally here:

https://github.com/digital-asset/daml/blob/60449fe24da93bfbf87c83c769dba13a447e2e31/ledger/participant-integration-api/src/test/lib/scala/platform/store/dao/JdbcLedgerDaoTransactionsSpec.scala#L531-L534

With a message like so

```
  Vector("0100000c21", ...) did not equal Vector(...)
  Random parameters:
    actual frequency: 50/1000
    code path: singlePartyWithTemplates
```

If you get such a failure, please copy those lines to a comment on this issue, **along with which test class failed**; this will help us find the cause of failure.

### PR DESCRIPTION
**Pull request by gerolf-da**
Akka's mergeSubstreams does not guarantee the order of the output.
In rare cases the order of the output doesn't match with the order
of the input, even though we know that the input events are in the
correct order (otherwise groupContiguous would delivery transactions
with random events from other transactions).

This change ~removes the need for substreams by collecting the events
for a transaction inside statefulMapConcat~ replaces `mergeSubstreams` with `concatSubstreams`, which limits the parallelism of _the whole sub-flow_ to 1 (see [Akka docs](https://doc.akka.io/docs/akka/current/stream/stream-substream.html#groupby)). The loss of mergeSubstreams'
parallelism is likely no problem, because we anyway need to send out transactions
in the correct order.

Fixes #7521.

CHANGELOG_BEGIN
Ledger API: Fixed an issue that rarely caused transactions to be sent out of order. See #7521
CHANGELOG_END

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
https://github.com/digital-asset/daml/pull/8336/commits/6d1853c7a4936d8acc3b6888b8956c28be57962d#diff-2e0c7568dd0dcd6a69386706abe53d5f311fefcef91e0fbc823c69afb3dd178e reverts https://github.com/digital-asset/daml/pull/7895 as part of this PR.

**Review by SamirTalwar-DA — APPROVED** [review]

**Comment by stefanobaghino-da** [comment]
Converted to draft to prevent accidental merging before we have a repro (but thanks for the trust, @SamirTalwar-DA). 🙂

File: ledger/participant-integration-api/src/main/scala/platform/store/dao/events/package.scala [hunk 1]
```diff
@@ -68,7 +68,7 @@ package object events {
       .splitWhen(_._2)
       .map(_._1)
       .fold(Vector.empty[A])(_ :+ _)
-      .mergeSubstreams
+      .concatSubstreams
```
Comment (gerolf-da) [inline ledger/participant-integration-api/src/main/scala/platform/store/dao/events/package.scala:71]: Could I ask you to put a comment here that `concatSubstreams` is crucial for delivery of the groups in the correct order?

Comment (stefanobaghino-da) [reply ledger/participant-integration-api/src/main/scala/platform/store/dao/events/package.scala:71]: Sure, thanks for raising this.

**Comment by gerolf-da** [comment]
Thanks for taking this over and diving deeper, @stefanobaghino-da!

**Comment by stefanobaghino-da** [comment]
Good news: after some manipulation on a user-provided repro sample, I noticed that the problem went away when all the create and exercise arguments where reduced to the bare minimum.

I hypothesized that the error condition is caused by _skew in the raw size of process items_ rather than the skew of lengths of individual groups as initially thought.

The following test triggers the error condition with a very low probability but the output is impossible to read:

```scala
  it should "keep the order of the input even with items of widely skewed size" in {
    val pairs = Iterator.range(0, 1000).flatMap { outerKey =>
      Iterator.tabulate(Random.nextInt(10) + 10)(innerKey =>
        outerKey -> (f"$outerKey%05d:$innerKey%05d:" + Random.nextString(
          Random.nextInt(10000) + 10)))
    }
    val pairsSource =
      Source.lazyFuture(() => Future(pairs)).mapConcat(_.toVector)
    val grouped = groupContiguous(pairsSource)(by = _._1)
    whenReady(grouped.runWith(Sink.seq[Vector[(Int, String)]])) {
      _.flatMap(_.map(_._2)) shouldBe sorted
    }
  }
```

 I'll see if I can come up with something clever (probably with repeated invisible characters instead of random strings).

**Comment by stefanobaghino-da** [comment]
Further attempts:
* use property-based testing to generate the "transaction" and "event" size
* use specific values to make smaller or larger events (e.g.: even/odd, first/last item, etc.)

For some reason, purely randomized tests like the one above seem to hit the "right spot" to trigger the error condition. I suspect that for some reason (Akka Streams buffer sizing?) there is some specific combination of stream length, "transaction" size and "event" size that has a slightly higher chance of triggering the error.

My best attempt so far is a modified version of the code above, which runs the same test 50 times over. It fails with 100% accuracy but is very heavy: it detects the bug in 30 seconds but takes more than 1 minute on the correct implementation.

I'll push it but my recommendation is to use this work to pin down the randomized values that trigger the error condition and work on those.

File: ledger/participant-integration-api/src/main/scala/platform/store/dao/events/package.scala (hunk 1 above)
Comment (stefanobaghino-da) [reply ledger/participant-integration-api/src/main/scala/platform/store/dao/events/package.scala:78]: Addressed by https://github.com/digital-asset/daml/pull/8336/commits/9af9baff0d7032327028da6ebfd9c1515eb237c9

**Comment by stefanobaghino-da** [comment]
@gerolf-da I changed the copyright notice so that this builds again. Do you have someone who can work on this moving forward?

**Comment by gerolf-da** [comment]
@stefanobaghino-da: thanks, @rautenrieth-da is looking into it now.

File: ledger/participant-integration-api/src/main/scala/platform/store/dao/events/package.scala [hunk 2]
```diff
@@ -51,6 +51,13 @@ package object events {
     * contiguous stretch of the input [[Source]]. Well suited to perform group-by
     * operations of streams where [[K]] attributes are either sorted or at least
     * show up in blocks.
+    *
+    * Implementation detail: this method _must_ use concatSubstreams instead of
+    * mergeSubstreams to prevent the substreams to be processed in parallel,
+    * potentially causing the outputs to be delivered in a different order.
+    *
+    * See: https://github.com/digital-asset/daml/pull/8336
```
Comment (miklos-da) [inline ledger/participant-integration-api/src/main/scala/platform/store/dao/events/package.scala:59]: Please remove this reference, i.e., `git blame` will show the relevant merge commit.

**Review by miklos-da — APPROVED** [review]

**Comment by S11001001** [comment]
What a find. Congratulations @stefanobaghino-da

**Comment by stefanobaghino-da** [comment]
> What a find. Congratulations @stefanobaghino-da

@gerolf-da Actually found the issue initially, I just found a way to reproduce but it's been deemed to heavy and removed. Ideally we could have used the heavy test to narrow down the exact conditions to make this test pass, but it's probably too much effort.

**Comment by rautenrieth-da** [comment]
> we could have used the heavy test to narrow down the exact conditions to make this test pass

Wouldn't that then be a test that likely only fails with the previous implementation? It would only protect us from someone accidentally changing `concatSubstreams` back to `mergeSubstreams`.

**Comment by stefanobaghino-da** [comment]
> > we could have used the heavy test to narrow down the exact conditions to make this test pass
> 
> Wouldn't that then be a test that likely only fails with the previous implementation? It would only protect us from someone accidentally changing `concatSubstreams` back to `mergeSubstreams`.

Likely, yes.
