### PR TITLE
Handle generic variant records in data-deps.

### LINKED ISSUE #4707: data-dependencies does not support variant types with type parameters AND record constructors .
Minimal test case:

```
daml 1.2
module Main where

data A t = B t | C { x : t, y : t }
```

Adding the resulting dar as a data-dependency causes this error:

```
  .daml/package-database/1.7/foo-0.0.1-1c0879c1f0ffc9759aada1e0380937c14046355307b0ae3f13a11446d3add43a/Main.daml
Hidden:   no
Range:    11:28-11:52
Source:   typecheck
Severity: DsError
Message: 
  .daml/package-database/1.7/foo-0.0.1-1c0879c1f0ffc9759aada1e0380937c14046355307b0ae3f13a11446d3add43a/Main.daml:11:29:
  error:
  • Record syntax is illegal here: {x : t_aim, y : t_aim}
  • In the type ‘({x : t_aim, y : t_aim} t_aim)’
  In the definition of data constructor ‘C’
  In the data declaration for ‘A’
damlc: Failed to compile interface for data-dependency: foo-0.0.1
```

Clearly the problem is that such data definitions are poorly translated from LF into DAML.

### PR DESCRIPTION
**Pull request by associahedron**
Fixes #4707.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/damlc/tests/src/DA/Test/Packaging.hs [hunk 1]
```diff
@@ -1287,6 +1287,45 @@ dataDependencyTests damlc repl davlDar oldProjDar = testGroup "Data Dependencies
...
+            , "name: proj"
+            , "source: ."
+            , "version: 0.1.0"
+            , "dependencies: [daml-prim, daml-stdlib]"
+            , "data-dependencies: "
+            , "  - " <> (tmpDir </> "type" </> "type.dar")
+            ]
+        writeFileUTF8 (tmpDir </> "proj" </> "Main.daml") $ unlines
+            [ "daml 1.2"
+            , "module Main where"
```
Comment (cocreature) [inline compiler/damlc/tests/src/DA/Test/Packaging.hs]: Maybe a usage of that type would be useful?

Comment (associahedron) [reply compiler/damlc/tests/src/DA/Test/Packaging.hs]: Added!
