### PR TITLE
Fix Numeric encoding and decoding in Scala bindings

### LINKED ISSUE #7474: Invalid argument: Could not read Numeric string "1E-13"
1. Given:
  * using com.daml.ledger.client.binding.Value.encode to build the command request
  * using ledger-api-client commandServiceClient.submitAndWait
2. When submitting a payload has a big decimal field `0.0000000000001`
3. Then it returns `Invalid argument: Could not read Numeric string "1E-13"`
 
In contrast - submitting a payload has a big decimal field `0.1234567890123` successful completed.

I suspect the following code (https://github.com/digital-asset/daml/blob/ab1c114c74e730f0a03fb25e159e197d0c173a2b/language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Value.scala#L78)
should be updated to use `bd.toPlainString`

### PR DESCRIPTION
**Pull request by cocreature**
fixes #7474

There are a few issues here:

1. We used toString which produces an exponential notation in some
cases which is not supported by the ledger API.

2. On the other hand, we used BigDecimal.exact for decoding which
isn’t completely wrong but more lax than what the ledger API supports

1 and 2 are fixed by switching to the respective functions in
daml-lf/data

3. The tests in ValueSpec were never executed! The tests are split
into a scala_library and a scala_test_suite and ValueSpec ended up in
the library. I’ve split out the utilities from the actual code.

4. The generator for Numeric produced things that are not valid
numerics (e.g. 92233720368547758070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
showed up in one test) which now fails with the more strict requirements.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Value.scala [hunk 1]
```diff
@@ -75,7 +76,9 @@ object DamlCodecs extends encoding.ValuePrimitiveEncoding[Value] {
   }
 
   implicit override val valueNumeric: Value[P.Numeric] =
-    fromArgumentValueFuns(_.numeric map BigDecimal.exact, bd => VSum.Numeric(bd.toString))
+    fromArgumentValueFuns(
+      _.numeric map lf.Numeric.assertFromString,
+      bd => VSum.Numeric(lf.Numeric.toString(bd.bigDecimal)))
```
Comment (remyhaemmerle-da) [inline language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Value.scala:81]: :+1:

**Review by remyhaemmerle-da — APPROVED** [review]
Looks good to me.  Thanks.

> 3.  The tests in ValueSpec were never executed! 

Good catch !

File: language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Value.scala [hunk 2]
```diff
@@ -75,7 +76,9 @@ object DamlCodecs extends encoding.ValuePrimitiveEncoding[Value] {
   }
 
   implicit override val valueNumeric: Value[P.Numeric] =
-    fromArgumentValueFuns(_.numeric map BigDecimal.exact, bd => VSum.Numeric(bd.toString))
+    fromArgumentValueFuns(
+      _.numeric map lf.Numeric.assertFromString,
```
Comment (S11001001) [inline language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Value.scala:80]: Use `fromString`, `toOption`, and `flatMap` instead.

File: language-support/scala/codegen-testing/src/test/scala/com/digitalasset/ledger/client/binding/ValueSpec.scala [hunk 3]
```diff
@@ -29,119 +25,18 @@ class ValueSpec extends WordSpec with Matchers with GeneratorDrivenPropertyCheck
...
-
-    override def valueTextMap[A](implicit vc: ValueCheck[A]) = {
-      import vc._
-      implicit val arbTM: Arbitrary[P.TextMap[A]] = Arbitrary(
-        GenEncoding.primitive.valueTextMap(TA.arbitrary))
-      ValueCheck[P.TextMap[A]](s"Map[$tName]")
+    "encode Numeric without exponents" in {
+      import com.daml.ledger.client.binding.{Primitive => P}
+      import com.daml.ledger.api.v1.value.Value.{Sum => VSum}
+      Value.Encoder[P.Numeric].write(BigDecimal.exact("0.0000000000001"): P.Numeric) shouldBe VSum
```
Comment (S11001001) [inline language-support/scala/codegen-testing/src/test/scala/com/digitalasset/ledger/client/binding/ValueSpec.scala:31]:
```suggestion
      Value.encode(BigDecimal.exact("0.0000000000001"): P.Numeric) shouldBe VSum
```

File: language-support/scala/codegen-testing/src/test/scala/com/digitalasset/ledger/client/binding/ValueGen.scala [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+  private[binding] implicit val dateArb: Arbitrary[P.Date] =
+    Arbitrary(GenEncoding.primitive.valueDate)
+
+  private[binding] implicit val timestampArb: Arbitrary[P.Timestamp] =
+    Arbitrary(GenEncoding.primitive.valueTimestamp)
+
+  private[this] object TautologicalValueChecks extends ValuePrimitiveEncoding[ValueCheck] {
+    override val valueInt64 = ValueCheck[P.Int64]("Int64")
+    override val valueNumeric = {
+      implicit val PA: Arbitrary[P.Numeric] = Arbitrary(GenEncoding.primitive.valueNumeric)
```
Comment (S11001001) [inline language-support/scala/codegen-testing/src/test/scala/com/digitalasset/ledger/client/binding/ValueGen.scala:42]: 👍

File: language-support/scala/codegen-testing/src/test/scala/com/digitalasset/ledger/client/binding/ValueGen.scala [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+// SPDX-License-Identifier: Apache-2.0
+
+package com.daml.ledger.client.binding
+
+import encoding.{ValuePrimitiveEncoding, GenEncoding}
+import org.scalacheck.{Arbitrary, Gen, Shrink}
+
+import scala.language.higherKinds
+
+object ValueGen {
```
Comment (S11001001) [inline language-support/scala/codegen-testing/src/test/scala/com/digitalasset/ledger/client/binding/ValueGen.scala:11]:
```suggestion
private[binding] object ValueGen {
```

`object ValueSpec` was public because `class ValueSpec` must be. This was just superstition on my part, I think.

**Review by S11001001 — CHANGES_REQUESTED** [review]

File: language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Value.scala (hunk 2 above)
Comment (cocreature) [reply language-support/scala/bindings/src/main/scala/com/digitalasset/ledger/client/binding/binding/Value.scala]: Duh, somehow I didn’t realize that `_.numeric` returns an `Option`. That’s what I get for trying to avoid intellij for this small patch. Thanks for catching it! That’s much nicer.

**Review by S11001001 — APPROVED** [review]
