### PR TITLE
Fix handling of packages in damlc visual

### LINKED ISSUE #5776: Enable sandbox on postgres in compat tests on Windows
This is not super important since this should be platform independent but it should be sufficiently easy to setup that it’s probably worth doing anyway at some point.

### PR DESCRIPTION
**Pull request by cocreature**
Previously we just ran the analysis on the modules of the main
package. This failed for obvious reasons as soon as you reference a
template from another package which happens pretty
frequently (e.g. for anything that uses finlib).

This PR fixes this to run the analysis on the whole World which is
self-contained. This required a bunch of reshuffling to make sure that
we always reference fully qualified identifiers but most of it is
very mechanical.

Note that currently you cannot distinguish between templates with
identical names in the resulting graph (they will be separate but you
have no idea which one is which). This was already an issue
before if you have the same template name in different modules so I
consider this an orthogonal issue.

This fixes the expected failure we already had and I added another
test that checks that colliding template names do at least show up as
separate nodes in the graph. I also manually tested this against
ex-bond-issuance.

Disclaimier: I’m aware that the code is very messy but I tried to
resist the urge to rewrite it completely and only change what was
necessary.

fixes #5776

changelog_begin

- [DAML Compiler] ``damlc visual`` now works properly in projects
  consisting of multiple packages.

changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/damlc/daml-visual/src/DA/Daml/Visual.hs [hunk 1]
```diff
@@ -41,32 +41,33 @@ import DA.Bazel.Runfiles
...
 
 
 data TemplateChoices = TemplateChoices
-    { template :: LF.Template
-    , modName :: LF.ModuleName
+    { template :: LF.Qualified LF.Template
     , choiceAndActions :: [ChoiceAndAction]
     } deriving (Show)
 
+templateChoiceId :: TemplateChoices -> LF.Qualified LF.TypeConName
```
Comment (hurryabit) [inline compiler/damlc/daml-visual/src/DA/Daml/Visual.hs:63]: I find this function name misleading. I understand that it returns a "choice id" when it actually returns a "template id". Maybe something like `templateIdFromChoices` would be better.

Comment (cocreature) [reply compiler/damlc/daml-visual/src/DA/Daml/Visual.hs]: Good point, I’ve renamed it to just `templateId`.
