### PR TITLE
Track erased types in data-dependencies.

### LINKED ISSUE #4470: Generic instances break data-dependencies
Testcase
```
module Test where
import qualified DA.Generics
data XGeneric = XGeneric deriving Generic
```

Error
```
  .daml/package-database/1.dev/proja-0.0.1-c90ee292b4fc2b7227dc5fdd057b3c06aeec923dda65585498927e5c8cc09d0a/A.daml:51:74:
  error:
  • Expected kind ‘DA.Generics.Meta’, but ‘()’ has kind ‘*’
  • In the second argument of ‘DA.Generics.M1’, namely ‘()’
  In the second argument of ‘DA.Generics.Generic’, namely
  ‘(((DA.Generics.M1 DA.Generics.D) ()) (((DA.Generics.M1 DA.Generics.C) ()) DA.Generics.U1))’
  In the instance declaration for
  ‘DA.Generics.Generic XGeneric (((DA.Generics.M1 DA.Generics.D) ()) (((DA.Generics.M1
  DA.Generics.C) ()) DA.Generics.U1))’
```

The reason for this is that `Generics` heavily rely on `DataKinds` which we do not support in DAML-LF and therefore we just translate them to `Unit`.

Possible solutions:
* Just filter out `Generic` (and `Generic1`) based on the name.
* Introduce a fixed `Erased` type which is isomorphic to `Unit` which we translate erased types to. That gives us a more robust solution and we don’t have to support instances pre DAML-LF so we don’t even need to keep the name-based filtering for older SDK versions.

cc @associahedron

### PR DESCRIPTION
**Pull request by associahedron**
This PR introduces a tracker for Erased types, DA.Generics, and any type, typeclass, or typeclass instance that dependens on them transitively. This is designed to detect and cut out any such definition that will cause problems.

Apologies for the large PR. Originally this was just a small extension to the tracking of old-style typeclasses, but each bugfix uncovered a new bug, and the only way to get it to completely work was to do it all at once. That's why the tracker is so extensive -- the only thing it doesn't track is regular functions, because they will never introduce a cyclic reference to an erased type that gets exposed in the type system (until we implement dependent DAML).

Right now the tracker runs once per data-dependency module, but in a future PR I will make it run once per data-dependency package to reduce the repetitive. This was all tested on a very large DAR, and it runs fine, but it should be much faster once it runs once per package.

Fixes #4470 

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 1]
```diff
@@ -794,23 +805,193 @@ generateSrcPkgFromLf config pkg = do
...
+        Right m -> m
+  where
+    refGraphList :: [(Ref, Bool, [Ref])]
+    refGraphList =
+        [ (ref, hidden, deps)
+        | (ref, (hidden, deps)) <- HMS.toList refGraph
+        ]
+
+    refGraph :: RefGraph
+    refGraph = foldl visitRef HMS.empty (rootRefs env)
```
Comment (cocreature) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]:
```suggestion
    refGraph = foldl' visitRef HMS.empty (rootRefs env)
```

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 2]
```diff
@@ -794,23 +805,192 @@ generateSrcPkgFromLf config pkg = do
...
+        | LF.PRImport pkgId <- refPackage ref
+        , MS.member pkgId (configStablePackages (envConfig env))
+            = HMS.insert ref (False, []) refGraph -- stable pkgs are always available
+
+        | RTypeCon tcon <- ref
+        , Just defDataType <- envLookupDataType tcon env
+        , refs <- DL.toList (refsFromDefDataType defDataType)
+        , hidden <- defDataTypeIsOldTypeClass defDataType
+        , refGraph' <- HMS.insert ref (hidden, refs) refGraph
+            = foldl visitRef refGraph' refs
```
Comment (cocreature) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]:
```suggestion
            = foldl' visitRef refGraph' refs
```

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 3]
```diff
@@ -794,23 +805,192 @@ generateSrcPkgFromLf config pkg = do
...
+
+        | RTypeSyn tsyn <- ref
+        , Just defTypeSyn <- envLookupSynonym tsyn env
+        , refs <- DL.toList (refsFromDefTypeSyn defTypeSyn)
+        , refGraph' <- HMS.insert ref (False, refs) refGraph
+            = foldl visitRef refGraph' refs
```
Comment (cocreature) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]:
```suggestion
            = foldl' visitRef refGraph' refs
```
we need an HLint hint :slightly_smiling_face:

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 4]
```diff
@@ -794,23 +805,192 @@ generateSrcPkgFromLf config pkg = do
...
+
+        | RValue val <- ref
+        , Just dval@LF.DefValue{..} <- envLookupValue val env
+        , refs <- if hasDFunSig dvalBinder -- we only care about typeclass instances
+            then DL.toList (refsFromDFun dval)
+            else mempty
+        , refGraph' <- HMS.insert ref (False, refs) refGraph
+            = foldl visitRef refGraph' refs
```
Comment (cocreature) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]:
```suggestion
            = foldl' visitRef refGraph' refs
```

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 5]
```diff
@@ -794,23 +805,192 @@ generateSrcPkgFromLf config pkg = do
...
+    visitRef :: RefGraph -> Ref -> RefGraph
+    visitRef !refGraph ref
+        | HMS.member ref refGraph
+            = refGraph -- already in the map
+        | ref == RTypeCon erasedTCon
+            = HMS.insert ref (True, []) refGraph -- Erased is always erased
+        | refModule ref == LF.ModuleName ["DA", "Generics"]
+            = HMS.insert ref (True, []) refGraph -- DA.Generics is not supported
+        | LF.PRImport pkgId <- refPackage ref
+        , Set.member pkgId (configDependencyPackages (envConfig env))
```
Comment (cocreature) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: Will we ever look up a reference to a `dependency`? Presumably the case where this matters is for reexported typeclasses. Do we check if the original typeclass is hidden or if the new typeclass is hidden? I think I don’t really understand why we need to “white-list” this so maybe it would be good to expand on this in a comment.

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 6]
```diff
@@ -794,23 +805,192 @@ generateSrcPkgFromLf config pkg = do
...
+    refGraph :: RefGraph
+    refGraph = foldl visitRef HMS.empty (rootRefs env)
+
+    visitRef :: RefGraph -> Ref -> RefGraph
+    visitRef !refGraph ref
+        | HMS.member ref refGraph
+            = refGraph -- already in the map
+        | ref == RTypeCon erasedTCon
+            = HMS.insert ref (True, []) refGraph -- Erased is always erased
+        | refModule ref == LF.ModuleName ["DA", "Generics"]
```
Comment (cocreature) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: Can we add a comment why `Erased` is not sufficient to throw out the problematic stuff from `DA.Generics`?

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs [hunk 7]
```diff
@@ -794,23 +805,192 @@ generateSrcPkgFromLf config pkg = do
...
+            = HMS.insert ref (True, []) refGraph -- DA.Generics is not supported
+        | LF.PRImport pkgId <- refPackage ref
+        , Set.member pkgId (configDependencyPackages (envConfig env))
+            = HMS.insert ref (False, []) refGraph -- dependencies are always available
+        | LF.PRImport pkgId <- refPackage ref
+        , MS.member pkgId (configStablePackages (envConfig env))
+            = HMS.insert ref (False, []) refGraph -- stable pkgs are always available
```
Comment (cocreature) [inline compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: Similar question here, why do we need to whitelist this?

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs (hunk 3 above)
Comment (associahedron) [reply compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: Ahahah, yes, absolutely. :)

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs (hunk 6 above)
Comment (associahedron) [reply compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: I'll add a comment. It's because `GenConvertible` causes kind errors in the back and forth translation, without actual  references to `Erased`.

Comment (cocreature) [reply compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: FWIW, `GenConvertible` is killed in https://github.com/digital-asset/daml/pull/4839. Although I don’t really understand why `GenConvertible` causes issues here since it’s not used in the project you tested on afaik and we have other tests that use `daml-stdlib`. Either way, happy to keep this code if we add a comment.

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs (hunk 5 above)
Comment (associahedron) [reply compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: I didn't check to see if it made a significant difference, but this whitelist is for the case where the data-dependency shares a dependency with the package being built. It doesn't check re-exports, it's just a check for actual references to the same dependencies.

The only case where this is logically relevant is if both the package being built & the data-dependencies depend on the same package, and that package contains something that would otherwise be erased. That's pretty rare. OTOH, this check prevents us from building up the a complicated dependency graph for daml-stdlib / daml-prim modules each time, on the assumption that the SDK hasn't changed.

Given that the case where it matters is quite rare, I can try removing this and see if it makes a difference to compile times. If removing it makes it significantly worse, I'll keep the whitelist and add a comment, and then see if we can just eat the cost once we start building this map once per package instead of once per module.

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs (hunk 7 above)
Comment (associahedron) [reply compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: Same as above. I can probably just remove it though.

File: compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs (hunk 5 above)
Comment (cocreature) [reply compiler/damlc/daml-compiler/src/DA/Daml/Compiler/DataDependencies.hs]: Thanks for the explanation! Happy to keep it for this PR if we add a comment.
