### PR TITLE
Consistently display stakeholders for key visibility errors

### LINKED ISSUE #6404: Inconsistent "Disclosed to" messages in scenarios
In the Keys example, there are two failing transactions which fail with inconsistent error messages.

If I change the `submitMustFail` in line 145 to `submit`, I get 

```
  Attempt to fetch, lookup or exercise a key associated with a contract not visible to the committer.
  Contract:  #0:0 (Keys:Keyed)
  Key:  's'
  Committer: 'd'
  Disclosed to: 'o', 's'
```

If I make the same change in 169, I get

```
  Attempt to fetch, lookup or exercise a key associated with a contract not visible to the committer.
  Contract:  #0:0 (Keys:Keyed)
  Key:  's'
  Committer: 'b'
  Disclosed to: 'd', 's', 'o'
```

Note that `d` now appears in the "Disclosed to". If I add a second divulgee `d2`, that divulgee also only appears in the second message, not the first.

That suggests to me that if the committer is a divulgee, the Disclosed to clause shows only stakeholders. If not, it shows all witnesses. That seems inconsistent. As long as only stakeholders can do lookups, the "Disclosed to" line should show only the stakeholders, I think.

### PR DESCRIPTION
**Pull request by cocreature**
fixes #6404

As pointed out by Bernhard in #6404, the previous behavior was pretty
weird. If the committer was only a divulgee, we only displayed
stakeholders. If the committer was neither a stakeholder nor a
divulgee, we displayed stakeholders + parties the contract has been
divulged to. Given that only stakeholders can do lookups it makes much
more sense to display them consistently which is what this PR
achieves. I’ve also renamed “disclosed to” to “stakeholders” to make
it very explicit what is shown there.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by cocreature** [comment]
The tests are going to fail until #6433 is merged but the rest of this PR is independent of that.

File: daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala [hunk 1]
```diff
@@ -222,9 +222,9 @@ final case class ScenarioRunner(
             missingWith(SErrorCrash(s"contract $acoid not effective, but we found its key!"))
           case ScenarioLedger.LookupContractNotActive(_, _, _) =>
             missingWith(SErrorCrash(s"contract $acoid not active, but we found its key!"))
-          case ScenarioLedger.LookupContractNotVisible(coid, tid, observers) =>
+          case ScenarioLedger.LookupContractNotVisible(coid, tid, _, stakeholders) =>
```
Comment (hurryabit) [inline daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala:225]:
```suggestion
          case ScenarioLedger.LookupContractNotVisible(coid, tid, observers@_, stakeholders) =>
```

File: daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala [hunk 2]
```diff
@@ -184,7 +184,7 @@ final case class ScenarioRunner(
       case ScenarioLedger.LookupContractNotActive(coid, tid, consumedBy) =>
         missingWith(ScenarioErrorContractNotActive(coid, tid, consumedBy))
 
-      case ScenarioLedger.LookupContractNotVisible(coid, tid, observers) =>
+      case ScenarioLedger.LookupContractNotVisible(coid, tid, observers, _) =>
```
Comment (hurryabit) [inline daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala:187]:
```suggestion
      case ScenarioLedger.LookupContractNotVisible(coid, tid, observers, stakeholders@_) =>
```
