### PR TITLE
Return the ledger beginning as the ledger end on an empty ledger

### LINKED ISSUE #6529: Invalid offsets returned by CompletionEnd service on an empty ledger
Steps to reproduce:
1. start from an empty ledger
2. call `CompletionEnd` endpoint to get an offset
3. try to use `CompletionStream` or `GetTransactions` with the offset returned in step 2

The problem is that step 2 will return a `LedgerOffset(Absolute(()))` protobuf value, which I guess is treated as the default gRPC value, so the completion stream will complain about the missing `offset` field.

We ran into the problem in Canton when using this guy on an empty ledger:
https://github.com/digital-asset/daml/blob/master/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/services/commands/CommandClient.scala#L110

### PR DESCRIPTION
**Pull request by oggy-**
Previously, the services would return `Offset.beforeBegin` to the clients, and the other services deem this offset to be invalid.

Closes #6529 

### Pull Request Checklist

- [X] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [X] Include appropriate tests
- [X] Set a descriptive title and thorough description
- [X] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [X] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/index/LedgerBackedIndexService.scala [hunk 1]
```diff
@@ -143,8 +143,12 @@ abstract class LedgerBackedIndexService(
...
     }
 
-  override def currentLedgerEnd(): Future[LedgerOffset.Absolute] =
-    Future.successful(toAbsolute(ledger.ledgerEnd))
+  override def currentLedgerEnd(): Future[LedgerOffset.Absolute] = {
+    if (ledger.ledgerEnd == Offset.beforeBegin) {
+      Future.successful(toAbsolute(Offset.begin))
+    } else
+      Future.successful(toAbsolute(ledger.ledgerEnd))
+  }
```
Comment (S11001001) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/index/LedgerBackedIndexService.scala:151]: Factoring

```suggestion
    Future.successful(toAbsolute(
      if (ledger.ledgerEnd == Offset.beforeBegin) Offset.begin
      else ledger.ledgerEnd
    ))
```

File: ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala [hunk 2]
```diff
@@ -36,6 +36,8 @@ object Offset {
 
   val beforeBegin: Offset = Offset.fromByteArray(Array.empty[Byte])
 
+  val begin: Offset = Offset.fromByteArray(Array(0: Byte))
```
Comment (SamirTalwar-DA) [inline ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala:39]: I seem to remember that some ledgers might not use `0` as the beginning. I'm not sure if this is an issue; it might be OK because it's the lowest possible offset, even if there isn't a `0`.

@simonmaxen-da, can you comment?

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+  override protected def config: SandboxConfig =
+    super.config.copy(
+      damlPackages = List.empty,
+      ledgerConfig = super.config.ledgerConfig.copy(
+        initialConfigurationSubmitDelay = Duration.ofDays(5)
+      ),
+      implicitPartyAllocation = false
+    )
+
+  private[this] val applicationId = "CompletionServiceIT"
```
Comment (SamirTalwar-DA) [inline ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:48]: Should this have the same name as the class?
```suggestion
  private[this] val applicationId = getClass.getSimpleName
```

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+
+  // How long it takes to download the entire completion stream.
+  // Because the stream does not terminate, we use a timeout to determine when the stream
+  // is done emitting elements.
+  private[this] val completionTimeout = FiniteDuration(2, TimeUnit.SECONDS)
```
Comment (SamirTalwar-DA) [inline ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:53]:
```suggestion
  private[this] val completionTimeout = 2.seconds
```

You'll need to import `scala.concurrent.duration.DurationInt`.

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+  "CommandCompletionService gives sensible ledger end on an empty ledger" in {
+
+    val partyA = "partyA"
+    val lid = ledgerId().unwrap
+    val completionService = CommandCompletionServiceGrpc.stub(channel)
+    for {
+      end <- completionService.completionEnd(CompletionEndRequest(lid))
+      completions <- completionsFromOffset(completionService, lid, List(partyA), end.getOffset)
+    } yield {
+      completions shouldBe empty
```
Comment (SamirTalwar-DA) [inline ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:79]: What happens when a transaction is written to the ledger after opening the stream? Does using `end.getOffset` get that completion?

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/index/LedgerBackedIndexService.scala (hunk 1 above)
Comment (SamirTalwar-DA) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/index/LedgerBackedIndexService.scala:151]:
```suggestion
    val offset =
      if (ledger.ledgerEnd == Offset.beforeBegin) Offset.begin
      else ledger.ledgerEnd
    Future.successful(toAbsolute(offset))
  }
```

File: ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala (hunk 2 above)
Comment (oggy-) [reply ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala:39]: This is basically what we used to return before this:

https://github.com/digital-asset/daml/commit/12c05c408af5abefad56d1135aa9d36ee1c2ea3c

So I hope it's not problematic from a functional behavior perspactive, at least the commit message in that commit doesn't suggest that it was

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala (hunk 5 above)
Comment (oggy-) [reply ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:79]: `.getOffset` is just an unsafe value getter for the (optional) protobuf field, so it should return the empty ledger begin regardless of what happens later. The cases where there are existing transactions before the end is requested are covered by the `CompletionServiceIT`

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/index/LedgerBackedIndexService.scala (hunk 1 above)
Comment (oggy-) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/index/LedgerBackedIndexService.scala]: Hopefully Samir's suggestion works for both of you

File: ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala (hunk 2 above)
Comment (simonmaxen-da) [reply ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala:39]: @SamirTalwar-DA - the first used offset should be at the discretion of the ledger implementor.  With the current DAML-on-Corda offset calculation the first offset will not be Offset.begin.   In future it could be.

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala (hunk 5 above)
Comment (SamirTalwar-DA) [reply ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:79]: I'm specifically wondering what happens in the case where we return `Offset.begin` rather than a value from the database, which we don't test elsewhere.

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala [hunk 6]
```diff
@@ -0,0 +1,82 @@
+// Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
+// SPDX-License-Identifier: Apache-2.0
+
+package com.daml.platform.sandbox.services.completion
+
+import java.time.Duration
+import java.util.concurrent.TimeUnit
```
Comment (SamirTalwar-DA) [inline ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:7]: This import is no longer used.

File: ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala (hunk 2 above)
Comment (oggy-) [reply ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala:39]: The ledger API server doesn't expose the underlying ledger's offsets; see the `parameters` table of the indexer and the `ledger_end` and `external_ledger_end` column. So IIUC, whatever the underlying ledger uses as the first offset, `0` should be consistent with what the Ledger API server uses.

Comment (SamirTalwar-DA) [reply ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala:39]: That makes sense. This line probably belongs in `ApiOffset`, not here, then.

Comment (oggy-) [reply ledger/participant-state/src/main/scala/com/daml/ledger/participant/state/v1/Offset.scala]: Moved to `ApiOffset` then

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala (hunk 5 above)
Comment (SamirTalwar-DA) [reply ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:78]: Discussed with @oggy-; this flags further issues so we're going to open a separate issue.

Comment (oggy-) [reply ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/services/completion/EmptyLedgerIT.scala:78]: Tracked now in #6640
