### PR TITLE
Bug fix. template id of archived contracted should be interface id instead

### LINKED ISSUE #15055: in WS query stream, template IDs are not translated to interface IDs for archive events
Example block from the stream, for which `templateId` is the implementing template even though this is an interface query:

```js
[
        {
            "archived": {
                "contractId": "00bf7f99faacb2c8d609b7cc02189555325f9878fbcadc28ac19dfd04fd2fba2f4ca00122093fdada3b2c8e1c3c9135c20414fe31a9d270e66cbc83a426906399c33cb8e82",
                "templateId": "8e0e4f359d0f65be65883ff8bd047511f33b97b0ead9d6b47e10a681879e95f7:Daml.Finance.Holding.Fungible:Fungible"
            }
        },
        {
            "created": {
// snip
```

Just as we swap template IDs for interface IDs in `created` events, so must we do so for `archived` events.

* [x] rewrite "interface sub query endpoint" test to use the `Consume` language, so it can test archive events
* [x] add an exercise to the test
* [x] test that the archive events have the interface ID
* [x] add the template-ID-to-interface-ID mapping to archive events in websocket result stream

_Originally posted by @GeorgSchneider in https://github.com/digital-asset/daml/issues/15042#issuecomment-1251176163_

### PR DESCRIPTION
**Pull request by chunlokling-da**
fixes #15055

### CODE REVIEW

File: ledger-service/fetch-contracts/src/main/scala/fetchcontracts/domain.scala [hunk 1]
```diff
@@ -122,7 +122,7 @@ package domain {
             val payload = in.interfaceViews
               .find(_.interfaceId.exists(_ == id))
               .flatMap(_.viewValue) required "interfaceView"
-            (\/-(ContractTypeId.Interface fromLedgerApi id), None, payload)
```
Comment (chunlokling-da) [inline ledger-service/fetch-contracts/src/main/scala/fetchcontracts/domain.scala:125]: I think we can just use interfaceId here right?

File: ledger-service/http-json/src/itlib/scala/http/AbstractWebsocketServiceIntegrationTest.scala [hunk 2]
```diff
@@ -262,51 +262,167 @@ abstract class AbstractWebsocketServiceIntegrationTest
...
+            "contractId" -> cid.toJson,
+            "choice" -> "ChangeAmount".toJson,
+            "argument" -> Map("newAmount" -> "abcxx").toJson,
+          ).toJson
+        }
+
+        val dslSyntax = Consume.syntax[JsValue]
+        import dslSyntax._
+
+//        def readAndExtract(amount: String): Consume.FCC[JsValue, CreatedAccountEvent] = for {
```
Comment (chunlokling-da) [inline ledger-service/http-json/src/itlib/scala/http/AbstractWebsocketServiceIntegrationTest.scala:300]: I have tried to reduce duplicated code here by what @S11001001 suggested. I have got it complied but IntelliJ doesn't like it with a lot of red error here. I wonder if I can make IntelliJ happier

Comment (S11001001) [reply ledger-service/http-json/src/itlib/scala/http/AbstractWebsocketServiceIntegrationTest.scala:300]: Making IntelliJ happier is like separating out the red M&Ms. Less red, but ultimately pointless because they all taste the same anyhow.

File: ledger-service/fetch-contracts/src/main/scala/fetchcontracts/domain.scala (hunk 1 above)
Comment (S11001001) [reply ledger-service/fetch-contracts/src/main/scala/fetchcontracts/domain.scala:127]: Yes.

**Review by S11001001 — APPROVED** [review]
I pushed 0c2ff6c1b08652392cd6fbcf674641f5b23644df...5403cbb8b98ee8c0bb6ae6f65cf4ee4e573b4778 to this branch as suggested changes; please take a look.
