### PR TITLE
Fix handling of non-visibile contract keys in scenario runner

### LINKED ISSUE #6403: Scenario transaction both succeeds and fails
The scenario in https://github.com/digital-asset/daml/blob/a27890adcd6e1a065d6f6ad496fe73220a8ff4de/docs/source/daml/code-snippets/Keys.daml behaves oddly. The submit at line 139 _should_ fail, which it does. But if I change the `submitMustFail` to `submit`, the scenario also succeeds. We should clearly never have a situation where `submit` and `submitMustFail` both succeed so something is fishy. `submit` should fail with an error message about the `None` lookup being incorrect.

### PR DESCRIPTION
**Pull request by cocreature**
fixes #6403

I am not entirely sure why I thought that using `missingWith` makes
sense here but it clearly doesn’t make sense and resulted in a pretty
bad bug where a transaction both succeeded via `submit` as well as
failed via `submitMustFail` which is clearly the wrong thing to do.

This PR fixes this issue and introduces a `notVisibleWith` function
that does the right thing. I’ve also added some comments and an extra
assertion to clarify things a bit.

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala [hunk 1]
```diff
@@ -192,14 +192,18 @@ final case class ScenarioRunner(
   private def lookupKey(
       gk: GlobalKey,
       committers: Set[Party],
-      cb: SKeyLookupResult => Boolean,
+      canContinue: SKeyLookupResult => Boolean,
```
Comment (hurryabit) [inline daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala:195]: Wasn't `cb` clear enough? 😉
Did you figure out what it stands for?

Comment (cocreature) [reply daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala:195]: `callback` presumably but that isn’t much more useful than `cb` so I’ve renamed it to what it actually does :slightly_smiling_face:

**Comment by cocreature** [comment]
> It's getting more and more worrying that the scenario service has its own code paths for things like this. I've added it to my list of things to consider for the next planning round.

If we do tackle it (and I agree that the current situation is shitty), I very much would like to combine this with making DAML Script work in the IDE.

File: daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala (hunk 1 above)
Comment (hurryabit) [reply daml-lf/scenario-interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/ScenarioRunner.scala:195]: Yeah, `callback` sounds very reasonable. Thanks. I haven't done enough JS yet to make the word omnipresent in my head. And I agree that `callback` carries almost as little information as `cb`.

**Comment by hurryabit** [comment]
> If we do tackle it (and I agree that the current situation is shitty), I very much would like to combine this with making DAML Script work in the IDE.

I absolutely agree with that sentiment. I'll refine my list item.
