### PR TITLE
interfaces: Improve fixed choice lookup

### LINKED ISSUE #11346: Improve efficiently of interface lookup of interfaces

### PR DESCRIPTION
**Pull request by sofiafaro-da**
This PR adds a lazy map to match fixed choice names to their
interface, so we're not doing a linear search over every interface.

Part of #10810
Fixes #11346

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-lf/language/src/main/scala/com/digitalasset/daml/lf/language/Ast.scala [hunk 1]
```diff
@@ -712,7 +712,12 @@ object Ast {
       observers: E, // Observers of the contract.
       key: Option[GenTemplateKey[E]],
       implements: Map[TypeConName, GenTemplateImplements[E]],
-  )
+  ) {
+    lazy val inheritedChoices: Map[ChoiceName, TypeConName] =
+      implements.iterator.flatMap { case (iface, impl) =>
+        impl.inheritedChoices.iterator.map ( chName => (chName, iface) )
+      }.toMap
```
Comment (remyhaemmerle-da) [inline daml-lf/language/src/main/scala/com/digitalasset/daml/lf/language/Ast.scala]: In this case, the first `.iterator` together with the `.toMap` are not useful because there is not intermediary `Map` that is built. 
In general,  when available, prefer `.view` over `iterator` as the later is pure. 

```suggestion
    lazy val inheritedChoices: Map[ChoiceName, TypeConName] =
      implements.flatMap { case (iface, impl) =>
        impl.inheritedChoices.view.map ( chName => (chName, iface) )
      }
```

**Review by remyhaemmerle-da — APPROVED** [review]
Nice.

File: daml-lf/language/src/main/scala/com/digitalasset/daml/lf/language/Ast.scala (hunk 1 above)
Comment (sofiafaro-da) [reply daml-lf/language/src/main/scala/com/digitalasset/daml/lf/language/Ast.scala]: Thanks!
