### PR TITLE
install script: check available disk space

### LINKED ISSUE #6993: Check if /tmp dir is large enough for install and fail or provide an alternative if it's not
As [airplatform3 encountered on the forum](https://discuss.daml.com/t/debian-buster-and-ubuntu-beaver-feedback-on-installing-daml/884) if your `/tmp` dir is too small the daml installation script will fail.

I'm not sure of the error message provided but there's some possible ways to improve this issue:

- Provide an error message that links to an alternative installation path that avoids `/tmp`. In airplatform3's post they mention that they were able to manually download the release and run `install.sh`
- Offer to use `./tmp` and cleanup afterwards

### PR DESCRIPTION
**Pull request by robin-da**
This fixes #6993. We check that /tmp offers enough space to extract the
sdk tarball and fail otherwise. An alternative extraction directory can
be set by setting the TEMPDIR environment variable.

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

**Comment by sofiafaro-da** [comment]
Nice, thank you.

One caution: I think we should avoid running `rm -rf $TMPDIR` if `$TEMPDIR` was set manually.  This means checking that `$TEMPDIR` was passed in the `cleanup()` procedure and at the end of the shell script. It would be best to have some message saying "feel free to remove DAML files from $TEMPDIR" or something.

File: daml-assistant/get-daml.sh [hunk 1]
```diff
@@ -26,13 +26,23 @@ else
 fi
 cd $TMPDIR
 
+# Don't remove user specified temporary directory on cleanup.
+rmTmpDir() {
+  if [ -z $TEMPDIR ]; then
+    rm -rf $TMPDIR
+  else
+    echo "Feel free to remove DAML files in $TEMPDIR."
```
Comment (sofiafaro-da) [inline daml-assistant/get-daml.sh:34]: Ok, this is perhaps too blasé 😅 How about . . .

```suggestion
    echo "You may now remove the DAML installation files from $TEMPDIR"
```

**Review by sofiafaro-da — APPROVED** [review]
Thanks so much!

File: daml-assistant/get-daml.sh [hunk 2]
```diff
@@ -18,16 +18,43 @@
 
 set -eu
 readonly SWD="$PWD"
-readonly TMPDIR="$(mktemp -d)"
+readonly INSTALL_MINSIZE=1000000
+if [ -z $TEMPDIR ]; then
+  readonly TMPDIR="$(mktemp -d)"
+else
+  readonly TMPDIR=$TEMPDIR
```
Comment (hurryabit) [inline daml-assistant/get-daml.sh:25]: I'm somewhat afraid that `TMPDIR` and `TEMPDIR` are too easy to mix up. Maybe it worth renaming the former into something like `ACTUAL_TEMPDIR`?

Comment (hurryabit) [reply daml-assistant/get-daml.sh:25]: Also, would it make sense to define `rmTmpDir` in both branches instead of branching in `rmTmpDir` itself? This way, we would have the code that depends on whether `TEMPDIR` is set or not next to each other.

**Review by hurryabit — COMMENTED** [review]
Very nice. Thank you so much!
