### PR TITLE
Perform name collision check against other names in package.

### LINKED ISSUE #3252: Perform DAML-LF name collision check in Haskell per package, not per module.
After a refactor of my DAML code, I'm getting this rather scary error upon submitting commands on a fresh sandbox started with
```
daml start --sandbox-option="--ledgerid=danban" --sandbox-option="-w"
```

This persists after a `daml clean`.

```
Submission of command d7be6093-df87-4d92-b2dd-3d63d1686d10 has failed.
com.digitalasset.daml.lf.validation.ECollision: null
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$6(Collision.scala:35)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$2(Collision.scala:32)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$2$adapted(Collision.scala:31)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.digitalasset.daml.lf.validation.Collision$.checkCollisions(Collision.scala:31)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkPackage$2(Collision.scala:15)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkPackage$2$adapted(Collision.scala:15)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
	at com.digitalasset.daml.lf.validation.Collision$.checkPackage(Collision.scala:15)
	at com.digitalasset.daml.lf.validation.Validation$.checkPackage(Validation.scala:28)
	at com.digitalasset.daml.lf.validation.Validation$.checkPackage(Validation.scala:17)
	at com.digitalasset.daml.lf.speedy.Compiler.compilePackage(Compiler.scala:131)
	at com.digitalasset.daml.lf.engine.ConcurrentCompiledPackages.addPackageInternal(ConcurrentCompiledPackages.scala:60)
	at com.digitalasset.daml.lf.engine.ConcurrentCompiledPackages.addPackage(ConcurrentCompiledPackages.scala:39)
	at com.digitalasset.daml.lf.engine.Result$.$anonfun$needPackage$2(Result.scala:108)
	at com.digitalasset.daml.lf.engine.CommandPreprocessor.$anonfun$preprocessCommands$3(CommandPreprocessor.scala:225)
	at com.digitalasset.daml.lf.engine.Result.$anonfun$flatMap$2(Result.scala:37)
	at com.digitalasset.platform.sandbox.stores.ledger.CommandExecutorImpl.$anonfun$consume$3(CommandExecutorImpl.scala:107)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Unhandled internal error.
```

To reproduce, checkout branch https://github.com/bame-da/react-kanban/tree/daml-refactor/danban, start using the above command, log in as `Admin` through Navigator, and try to create a `Danban:App` with `operator = Admin`.

I don't know whether the issue is with the interpreter of the LF that's being generated so assigning  both @hurryabit and @gerolf-da .

### PR DESCRIPTION
**Pull request by associahedron**
This PR advances #3252 by checking the current module's names against the type names from ascendant modules, and against module names from descendent modules.

I ran this change against a very large DAML codebase and the difference was insignificant (it was actually 0.9% faster, i.e. up to random variation).

It also cleans up the handling of type synonyms in the name collision checker.

### CODE REVIEW

File: compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/NameCollision.hs [hunk 1]
```diff
@@ -148,21 +154,50 @@ checkDataType moduleName DefDataType{..} =
...
+            checkTemplate (moduleName m) tpl
+
+checkModuleFully :: MonadGamma m => Module -> S.StateT NCState m ()
+checkModuleFully m = do
+    checkModuleName m
+    checkModuleTypes m
+
+-- | Is the first module an ascendant of the second? This check
+-- is case-insensitive because name collisions are case-insensitive.
+isAscendant :: ModuleName -> ModuleName -> Bool
```
Comment (cocreature) [inline compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/NameCollision.hs]: I’m a bit confused about this. Do we have some concept of hierarchical modules in DAML-LF? I thought this worked just like in Haskell where the hierarchy doesn’t really mean anything.

Comment (cocreature) [reply compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/NameCollision.hs]: Ah I think I got it now, we need to check for collisions between module `A.B` and type `B` in module `A`. It would be good to add a comment on this.

**Comment by associahedron** [comment]
> Looks great thanks a lot! I think a comment with the case that we want to catch here would be nice and maybe also a test case (I think the issue had one that you can trigger from DAML).

I added a test but discovered that the package-wide collision only works when colliding modules depend on each other, which is less than ideal. I think it might be time for me to learn how to make shake rules... Will merge this PR for now (once it's green) and try to improve the collision checker.
