### PR TITLE
Fix projection on sum-of-product types

### LINKED ISSUE #310: Problem with dot-notation for field access in SDK 0.12.1
The following code produces an error whose location spans the entire file (0-10000).
```
daml 1.2
module FieldBug where
data AType = Con1 with field: Text
            | Con2 with field: Text

fieldBug : AType -> Text
fieldBug f = f.field -- error [1]
-- fieldBug f = field f -- works

{-
[1] 
error type checking value FieldBug.fieldBug:
  expected record type:
  * found: 
      TypeConApp {tcaTypeCon = Qualified {qualPackage = PRSelf, qualModule = Tagged ["FieldBug"], qualObject = Tagged ["AType"]}, tcaArgs = []}
-}
```
The code is accepted when the field accessor `field` is used instead of the dot notation `.field`.
SDK 0.12.31 works fine with this code.

### PR DESCRIPTION
**Pull request by martin-drhu-da**
Fixes #310.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](./CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](./docs/source/support/release-notes.rst), if appropriate

### CODE REVIEW

File: daml-foundations/daml-ghc/src/DA/Daml/GHC/Compiler/Convert.hs [hunk 1]
```diff
@@ -566,7 +566,11 @@ convertExpr env0 e = do
     go env (VarIs "getFieldPrim") (Type (isStrLitTy -> Just name) : Type record : Type _field : args) = fmap (, args) $ do
         record' <- convertType env record
         pure $ ETmLam (varV1, record') $ ERecProj (fromTCon record') (mkField $ unpackFS name) $ EVar varV1
-    go env (VarIs "getField") (Type (isStrLitTy -> Just name) : Type recordType : Type _fieldType : _dict : record : args) = fmap (, args) $ do
+    -- NOTE(MH): We only inline `getField` for record types. This is required
+    -- for contract keys. Projections on sum-of-records types have to through
+    -- the type class for `getField`.
+    go env (VarIs "getField") (Type (isStrLitTy -> Just name) : Type recordType@(TypeCon recordTyCon _) : Type _fieldType : _dict : record : args)
+        | Just [_] <- tyConDataCons_maybe recordTyCon = fmap (, args) $ do
```
Comment (neil-da) [inline daml-foundations/daml-ghc/src/DA/Daml/GHC/Compiler/Convert.hs]: Didn't we have a helper function to test if something was a single constructor?

Comment (martin-drhu-da) [reply daml-foundations/daml-ghc/src/DA/Daml/GHC/Compiler/Convert.hs]: The helper function works on the data constructor level, not the type constructor level.
