### PR TITLE
Daml-script: Use curly braces notation for records in ledger export

### LINKED ISSUE #13620: daml ledger export script not well formatted
# Affected Daml version
1.18.1.

# Bug description
Output of `daml ledger export script` does not indent enough in lists and tuples:
image

# To reproduce

# Expected behavior

Could/Should be:

image

# Additional context

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
instead of `with` notation

fixes #13620

CHANGELOG_BEGIN
- [Daml-script] fix a bug in daml-script export formatting
  See https://github.com/digital-asset/daml/issues/13620
CHANGELOG_END

### CODE REVIEW

File: daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala [hunk 1]
```diff
@@ -43,12 +43,14 @@ class EncodeValueSpec extends AnyFreeSpec with Matchers {
           ),
         )
       )
-      encodeValue(Map.empty, Map.empty, r).render(80) shouldBe
-        """M.R1 with
```
Comment (cocreature) [inline daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:47]: I don’t actually understand what broke. This looks like indentation of nested records works fine so what didn’t work? Can we capture that in a test?

Comment (remyhaemmerle-da) [reply daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:47]: I added a test for list of record.

File: daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala [hunk 2]
```diff
@@ -88,9 +94,25 @@ class EncodeValueSpec extends AnyFreeSpec with Matchers {
...
+      val l = List(0L, 1L).map(v.Value().withInt64(_))
+      val value = v.Value().withList(v.List(l))
+      encodeValue(Map.empty, Map.empty, value.sum).render(80) shouldBe "[0, 1]"
+    }
+    "list of record" in {
+      val l = List(record, record).map(v.Value().withRecord(_))
+      val value = v.Value().withList(v.List(l))
+      encodeValue(Map.empty, Map.empty, value.sum).render(
+        100
+      ) shouldBe "[(M.R1 {a = 1, b = (M.R2 {c = 42}), c = M.R3}), (M.R1 {a = 1, b = (M.R2 {c = 42}), c = M.R3})]"
```
Comment (remyhaemmerle-da) [inline daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:107]: without my change the output is 
```
[M.R1 with
  a = 1
  b = M.R2 with
    c = 42
  c = M.R3, M.R1 with
  a = 1
  b = M.R2 with
    c = 42
  c = M.R3]
```
which is not syntactically correct.

Comment (remyhaemmerle-da) [reply daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:107]: I followed @sofiafaro-da advice to use curly braces notation which is easier to ident.

Comment (cocreature) [reply daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:107]: We actually considered using curly braces initially but decided against it because the output of an export is intended to be read and for better or for worse, we push users towards `with`-syntax so using someting different in exports seemed off. I don’t feel too strongly about it but I think it’s at least worth thinking about whether we cannot fix the indentations instead.

Comment (akrmn) [reply daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:107]: Now I'm thinking that the problem is actually in the parser, I don't see why the current output 

```haskell
[M.R1 with
  a = 1
  b = M.R2 with
    c = 42
  c = M.R3, M.R1 with
  a = 1
  b = M.R2 with
    c = 42
  c = M.R3]
```

shouldn't be syntactically correct. It reminds me of `do` notation, where the actions can be less indented than the `do` keyword, plus `BlockArguments`, where a function can appear just before the `do` (no `$` required). Which is to say, maybe we should fix the parser to support this syntax instead?

Comment (sofiafaro-da) [reply daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:107]: @cocreature I disagree. We don't have a daml formatter (or even an AST) so trying to create particularly "human friendly" output is not a realistic goal. Moving to curly braces syntax here is fine, especially if it fixes a bug and is easier to maintain.

Comment (cocreature) [reply daml-script/export/src/test/scala/com/daml/script/export/EncodeValueSpec.scala:107]: I’m not that concerned about particularly nice formatting but using syntax that we don’t really use anywhere else in our docs just seems to make it unnecessarily hard for users to understand the output.
I don’t feel very strongly here though so feel free to move forward with this change.

File: daml-script/export/src/main/scala/com/daml/script/export/Encode.scala [hunk 3]
```diff
@@ -105,7 +104,7 @@ private[export] object Encode {
   }
 
   private def encodePartyBinding(party: Party, binding: String): Doc =
-    s"let $binding = lookupParty" &: quotes(Doc.text(Party.unwrap(party))) :& "parties"
+    s"let $binding = lookupParty" &: quotes(Party.unwrap(party)) :& "parties"
```
Comment (sofiafaro-da) [inline daml-script/export/src/main/scala/com/daml/script/export/Encode.scala:107]: Unrelated to this PR (this is the first time I look at this code): Shouldn't we escape party names? Or are there strict rules on what constitutes a party name?

File: daml-script/export/src/main/scala/com/daml/script/export/Encode.scala [hunk 4]
```diff
@@ -346,12 +350,14 @@ private[export] object Encode {
...
       qualifyId(r.getRecordId)
-    } else {
-      (qualifyId(r.getRecordId) + Doc.text(" with") /
-        Doc.stack(r.fields.map(f => encodeField(partyMap, cidMap, f)))).nested(2)
-    }
+    else
+      parens(
+        qualifyId(r.getRecordId) &
+          braces(Doc.intercalate(comma, r.fields.map(encodeField(partyMap, cidMap, _))))
+      )
```
Comment (sofiafaro-da) [inline daml-script/export/src/main/scala/com/daml/script/export/Encode.scala:359]: I don't think the outer parens here is necessary. Curly brace syntax binds tightly.

**Review by sofiafaro-da — APPROVED** [review]
Thank you!

File: daml-script/export/src/main/scala/com/daml/script/export/Encode.scala (hunk 3 above)
Comment (remyhaemmerle-da) [reply daml-script/export/src/main/scala/com/daml/script/export/Encode.scala:107]: from the [spec](../tree/main/daml-lf/spec/daml-lf-1.rst) : 
```
PartyId strings
     PartyIdString  ∈  [a-zA-Z0-9:\-_ ]{1,255}      -- PartyIdString
```

**Review by akrmn — APPROVED** [review]
