### PR TITLE
ledger-api-test-tool: Run tests on Canton, and fix a few issues.

### LINKED ISSUE #3380: Ledger api test tool: Extend test framework to initialize parties on all participants
waiting until non-local parties are known to other participants.

@SamirTalwar , @stefanobaghino-da please rephrase as necessary or close if you are already tracking this elsewhere.

This should address the lion-share of the flaky tests listed in #3059

I can help do a multi-participant test run to try out the code beforehand if you want.

### PR DESCRIPTION
**Pull request by SamirTalwar**
Run the ledger-api-test-tool against [Canton][], a distributed ledger built by Digital Asset that supports DAML.

This adds Canton v0.3.0 to our external dependencies. We will endeavor to track the released version of Canton.

Right now we only run the SemanticTests, as a few of the other tests fail.

There are two main changes to the test suite:

- We now wait for all parties to propagate to all participants. Previously we didn't bother, as most ledgers are not truly distributed and centralize party creation. This closes #3380.
- All tests referencing contract keys have been moved into the "ContractKeys" test file, as Canton does not yet support contract keys and it's useful to be able to exclude those tests.

I've also made a change to the test runner to fail fast if a test name specified in an `--include` or `--exclude` switch is misspelled.

In other news, I hate Bazel. (About as much as all the other build tools.)

[Canton]: https://www.canton.io/

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/infrastructure/Eventually.scala [hunk 1]
```diff
@@ -3,14 +3,15 @@
...
-import scala.concurrent.duration.DurationInt
+import scala.concurrent.duration.{Duration, DurationInt}
 import scala.concurrent.{ExecutionContext, Future}
 
 object Eventually {
-  private val withRetryStrategy = RetryStrategy.exponentialBackoff(10, 10.millis)
-
-  def eventually[A](runAssertion: => Future[A])(implicit ec: ExecutionContext): Future[A] =
-    withRetryStrategy { _ =>
+  def eventually[A](
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/infrastructure/Eventually.scala]: This creates a new instance of the retry strategy object at every call of `eventually`, which is anyhow fine, we're talking about a few objects, so not a problem, I'm mostly thinking out loud in the review. :slightly_smiling_face: :+1:

Comment (SamirTalwar) [reply ledger/ledger-api-test-tool/src/main/scala/com/daml/ledger/api/testtool/infrastructure/Eventually.scala]: Yeah, didn't seem to be a big deal. I can revert this if you like; not actually using it. I just needed to slow down the timeout to debug the propagation check because it was swamping the logs with errors.

(I got the `subsetOf` call the wrong way around, of course.)
