### PR TITLE
Ensure trigger service stops runners that throw trigger overflow exceptions

### LINKED ISSUE #16224: Trigger runner overflows should be stopped by the trigger service
With the new hard limits for trigger ACS and in-flight data structures, the Runner may now throw a `InFlightCommandOverflowException` or a `ACSOverflowException`. Currently, these exceptions would be error logged by the trigger service and the trigger runner restarted.

As these overflows are indicative of a bigger issue with how the trigger rules have been written and so require some operational intervention, this is not an acceptable course of action. The trigger runner, in these cases, should be stopped by the trigger service.

TODO:
- [ ] ~~add in supervisor behaviours to trap (and so stop) when the runner throws these overflow exceptions~~ (potentially not required as existing trigger service will stop runner on the overflow exceptions?)
- [ ] add in trigger service tests to validate that the runner does stop when overflows occur

### PR DESCRIPTION
**Pull request by carlpulley-da**
Fixes #16224 

- [x] add in supervisor behaviours to trap (and so stop) when the runner throws these overflow exceptions - whilst testing shows this may not be required, supervisor code to do this has been added (that way restart config/policy can not control this behaviour)
- [x] add in trigger service tests to validate that the runner does stop when overflows occur

### CODE REVIEW

File: triggers/service/src/main/scala/com/digitalasset/daml/lf/engine/trigger/TriggerRunner.scala [hunk 1]
```diff
@@ -51,19 +51,23 @@ object TriggerRunner {
...
-                      .onFailure[InitializationHalted](stop)
+                      .supervise(
+                        Behaviors
+                          .supervise(TriggerRunnerImpl(config))
+                          .onFailure[InitializationHalted](stop)
+                      )
+                      .onFailure[UnauthenticatedException](stop)
                   )
-                  .onFailure[UnauthenticatedException](stop)
+                  .onFailure[TriggerOverflowException](stop)
```
Comment (carlpulley-da) [inline triggers/service/src/main/scala/com/digitalasset/daml/lf/engine/trigger/TriggerRunner.scala:70]: Feel its safer to have an explicit stop for overflow exceptions rather than relying on current observations from testing

File: triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala [hunk 2]
```diff
@@ -86,6 +91,13 @@ trait AbstractTriggerServiceTestHelper
     DarReader.assertReadArchiveFromFile(darPath).map(p => p.pkgId -> p.proto)
   protected lazy val testPkgId: PackageId = dar.main._1
 
+  private[this] val triggerRunnerLogAppender = new ListAppender[ILoggingEvent]()
+  private[this] val triggerRunnerLogger: Logger =
+    LoggerFactory.getLogger(classOf[Runner]).asInstanceOf[Logger]
+
+  triggerRunnerLogAppender.start()
+  triggerRunnerLogger.addAppender(triggerRunnerLogAppender)
```
Comment (carlpulley-da) [inline triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala:99]: Code to snag log events from the trigger runner (current test code only snags log events from the trigger service)

File: triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala [hunk 3]
```diff
@@ -272,6 +284,20 @@ trait AbstractTriggerServiceTestHelper
     eventually {
       pred(getTriggerStatus(triggerInstance).map(_._2))
     }
+
+  def assertTriggerRunnerStatus(
+      triggerInstance: UUID,
+      pred: Vector[String] => Assertion,
+  ): Assertion = {
+    val filterString = s"id: \"$triggerInstance\""
```
Comment (carlpulley-da) [inline triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala:292]: The log marker (in the log event) holds our trigger logging context. We use this knowledge to match on the trigger ID which will be present within this logging context (and so log marker).

File: triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala [hunk 4]
```diff
@@ -272,6 +284,20 @@ trait AbstractTriggerServiceTestHelper
...
+
+    eventually {
+      pred(triggerRunnerLogAppender.list.toArray.toVector.collect {
+        case event: ILoggingEvent if event.getMarker.toString contains filterString =>
+          event.toString
+      })
```
Comment (carlpulley-da) [inline triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala:298]: We filter the logging events and apply our predicate to the set which have the given trigger ID - i.e. the predicate is applied to only log events emitted by the trigger runner with the given UUID.

File: triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala [hunk 5]
```diff
@@ -616,6 +642,157 @@ trait AbstractTriggerServiceTest extends AbstractTriggerServiceTestHelper {
...
+        .flatMap(events =>
+          Future.sequence(events.map { event =>
+            submitCmd(client, alice.unwrap, killCat(event.contractId))
+          })
+        )
+      // Wait until there are no Cat contracts
+      _ <- RetryStrategy.constant(20, 1.seconds) { (_, _) =>
+        getActiveContracts(client, alice, Identifier(testPkgId, "Cats", "Cat"))
+          .map(_ shouldBe Vector())
+      }
```
Comment (carlpulley-da) [inline triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala:744]: Pollution from prior testing requires us to cleanup prior to allowing this test to proceed

File: triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala [hunk 6]
```diff
@@ -616,6 +642,157 @@ trait AbstractTriggerServiceTest extends AbstractTriggerServiceTestHelper {
...
```
Comment (carlpulley-da) [inline triggers/service/src/test/scala/com/digitalasset/daml/lf/engine/trigger/TriggerServiceTest.scala:785]: Pollution from prior testing requires us to cleanup prior to allowing this test to proceed

File: triggers/service/BUILD.bazel [hunk 7]
```diff
@@ -317,6 +317,7 @@ da_scala_test_suite(
         "//libs-scala/ports",
         "//libs-scala/resources",
         "//libs-scala/test-evidence/tag:test-evidence-tag",
+        "//triggers/runner:trigger-runner-lib",
```
Comment (carlpulley-da) [inline triggers/service/BUILD.bazel:320]: Required for the linux_oracle build

**Review by remyhaemmerle-da — APPROVED** [review]
LGTM.
