### PR TITLE
Fix race condition in scenario service context updates

### LINKED ISSUE #4525: Shake tests are flaky
They sometimes seem to fail with

```
Virtual resource gets updated with a note when file compiles, but scenario is no longer present: FAIL (1.91s)
      compiler\damlc\tests\src\DA\Test\ShakeIdeClient.hs:56:
      Shake test resulted in an error: Left (ExpectedNoErrors [(NormalizedFilePath "C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\shake-api-test-cc29873f03ec6678\\F.daml",ShowDiag,Diagnostic {_range = Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 9}}, _severity = Just DsError, _code = Nothing, _source = Just "Scenario", _message = "\"Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusNotFound (StatusDetails {unStatusDetails = \\\" context 83 not found!\\\"})))\"", _relatedInformation = Nothing}),(NormalizedFilePath "C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\shake-api-test-cc29873f03ec6678\\F.daml",ShowDiag,Diagnostic {_range = Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 9}}, _severity = Just DsError, _code = Nothing, _source = Just "Scenario", _message = "\"Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusNotFound (StatusDetails {unStatusDetails = \\\" context 83 not found!\\\"})))\"", _relatedInformation = Nothing})])
```

So far I’ve only seen this on Windows I believe but I doubt it’s OS specific.

### PR DESCRIPTION
**Pull request by cocreature**
If we get interrupted after updating our local view but before doing
the actual context update on the server side bad things happen. To fix
this, we first clone the context then update the clone which avoids
this and is a bit nicer than throwing an `uninterruptibleMask` around
updating the local view and sending the updateCtx gRPC request.

fixes #4525

changelog_begin
changelog_end

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/scenario-service/client/src/DA/Daml/LF/ScenarioServiceClient.hs [hunk 1]
```diff
@@ -142,23 +145,30 @@ getNewCtx Handle{..} Context{..} = withLock hContextLock $ withSem hConcurrencyS
...
       ctxSkipValidation
-  writeIORef hLoadedPackages newLoadedPackages
-  writeIORef hLoadedModules ctxModules
-  res <- LowLevel.updateCtx hLowLevelHandle hContextId ctxUpdate
-  case res of
-    Left err -> pure (Left err)
-    Right () -> LowLevel.cloneCtx hLowLevelHandle hContextId
+  rootCtxId <- readIORef hContextId
+  runExceptT $ do
+      clonedRootCtxId <- ExceptT $ LowLevel.cloneCtx hLowLevelHandle rootCtxId
```
Comment (aherrmann-da) [inline compiler/scenario-service/client/src/DA/Daml/LF/ScenarioServiceClient.hs]: How are these cloned contexts cleaned up? Sure, on the Haskell side they are GC'ed. But, don't we need to explicitly delete them to avoid leaking resources in the scenario service?

Comment (cocreature) [reply compiler/scenario-service/client/src/DA/Daml/LF/ScenarioServiceClient.hs]: There is a `gcCtxs` gRPC request that we send to the server https://github.com/digital-asset/daml/blob/master/compiler/damlc/daml-ide-core/src/Development/IDE/Core/Rules/Daml.hs#L908

Comment (aherrmann-da) [reply compiler/scenario-service/client/src/DA/Daml/LF/ScenarioServiceClient.hs]: Thanks for clarifying!
