### PR TITLE
reduce package service calls to avoid `THREADPOOL_OVERLOADED` errors

### LINKED ISSUE #15922: THREADPOOL_OVERLOADED when loading large number of packages
Spin-off of #15551, as reported by @GeorgSchneider . When loading a large number of packages (66 is good enough), and perhaps also starting many active websocket streams (which may trigger a race that multiplies said loading), we see sometimes

```
11-11-2022 14:58:35.623 [http-json-ledger-api-akka.actor.default-dispatcher-13] ERROR akka.actor.ActorSystemImpl - Websocket handler failed with ABORTED: THREADPOOL_OVERLOADED(2,0): The Index Database Connection Threadpool queue size (1005) has exceeded the maximum (1000). Api services metrics are available at daml.index.db.threadpool.connection.api-server. 
io.grpc.StatusRuntimeException: ABORTED: THREADPOOL_OVERLOADED(2,0): The Index Database Connection Threadpool queue size (1005) has exceeded the maximum (1000). Api services metrics are available at daml.index.db.threadpool.connection.api-server.
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Unlike with #15551, json-api manages to recover from this problem. See that issue for reproduction.

### PR DESCRIPTION
**Pull request by S11001001**
Backport of #16116 (81b4e17f00be433613a81b1a74c67d9dbdb78a3f) to fix #15922 in 2.5.x.

### CODE REVIEW

File: ledger-service/utils/src/main/scala/com/digitalasset/ledger/service/Grpc.scala [hunk 1]
```diff
@@ -0,0 +1,27 @@
+// Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
```
Comment (garyverhaegen-da) [inline ledger-service/utils/src/main/scala/com/digitalasset/ledger/service/Grpc.scala:1]:
```suggestion
// Copyright (c) 2022 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
```

The 2.5 branch is not up-to-date in that regard.

File: libs-scala/scala-utils/src/main/scala/com/daml/scalautil/TraverseFMSyntax.scala [hunk 2]
```diff
@@ -0,0 +1,23 @@
+// Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
```
Comment (garyverhaegen-da) [inline libs-scala/scala-utils/src/main/scala/com/daml/scalautil/TraverseFMSyntax.scala:1]:
```suggestion
// Copyright (c) 2022 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
```

File: ledger-service/utils/src/main/scala/com/digitalasset/ledger/service/Grpc.scala (hunk 1 above)
Comment (S11001001) [reply ledger-service/utils/src/main/scala/com/digitalasset/ledger/service/Grpc.scala]: 822369dd89a

**Review by ray-roestenburg-da — APPROVED** [review]
