### PR TITLE
Check that crypto primitives generate no unexpected exceptions

### LINKED ISSUE #22087: Check that crypto primitives generate no unexpected exceptions
Whilst working on https://github.com/digital-asset/daml/pull/21954 I was noticing surprising exceptions such as:
- "number not in range [1, n - 1]"
- and "point not on EC curve"

Double check that these (and all other) exceptions are managed. Maybe use property based testing to improve confidence that crypto primitives with broken format inputs can not throw unexpected exceptions?

### PR DESCRIPTION
**Pull request by carlpulley-da**
Fixes #22087

- [x] Add in property based testing to ensure invalid DER signature encodings are handled correctly by `SBSECP256K1Bool`
- [x] Add in property based testing to ensure invalid DER public key encodings are handled correctly by `SBSECP256K1Bool`
- [x] Provide potential patch for `SBSECP256K1Bool` when it hits `IllegalArgumentException` when processing badly formatted DER public keys

### CODE REVIEW

File: sdk/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltinFun.scala [hunk 1]
```diff
@@ -778,6 +778,15 @@ private[lf] object SBuiltinFun {
           crash("JCE Provider BouncyCastle not found")
         case _: NoSuchAlgorithmException =>
           crash("BouncyCastle provider fails to support SECP256K1")
+        case _: IllegalArgumentException =>
```
Comment (carlpulley-da) [inline sdk/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltinFun.scala:781]: This is the fix that we will ultimately need to apply.

From a backwards compatibility/data continuity PoV, I'd argue that fixing this is low risk.

File: sdk/daml-lf/interpreter/src/test/scala/com/digitalasset/daml/lf/speedy/SBSECP256K1BoolTest.scala [hunk 2]
```diff
@@ -6,17 +6,48 @@ package speedy
...
+    with Matchers
+    with ScalaCheckPropertyChecks {
+  import SBSECP256K1BoolTest._
+  import SpeedyTestLib.loggingContext
 
-class SBSECP256K1BoolTest extends AnyFreeSpec with Matchers {
   Security.addProvider(new BouncyCastleProvider)
 
+  private val compilerConfig = Compiler.Config.Default(majorLanguageVersion)
+  private val dummyMachine = Speedy.Machine.fromPureExpr(
```
Comment (carlpulley-da) [inline sdk/daml-lf/interpreter/src/test/scala/com/digitalasset/daml/lf/speedy/SBSECP256K1BoolTest.scala:46]: As `SBSECP256K1Bool` doesn't use its speedy machine argument, we just need some dummy machine to allow `execute` calls
