### PR TITLE
Query store support for interface query/fetch

### LINKED ISSUE #14819: query store support for interface query/fetch
Overall design in https://github.com/digital-asset/daml/issues/14067#issuecomment-1149150541.

* [x] permit multiple DB rows per contract ID
* [x] the final caller of `ActiveContract.fromLedgerApi`, this time in `ContractsFetch`, must do as with #14815
* [x] include contract type IDs in `InsertDeleteStep`
* [x] add contract type ID argument to `Queries#deleteContracts`, in the form of `SurrogateTpId`
* [x] in `ContractsFetch#insertAndDelete`, find the appropriate SurrogateTpIds for the `deleteContracts` call
* [x] in `SearchDB#findByContractId`, remove the `ByInterfaceId` special case
* [x] in `SearchDB#search`, remove the `ByInterfaceId` special case
* [x] in `WebSocketService#fetchAndPreFilterACS`, remove the `ByInterfaceId` special case
* [x] #15316
    * [x] create two contracts with a signatory and a _different_ observer, of a template that implements an interface with a non-empty view
    * [x] using an auth **with both parties**:
    * [x] query the template ID; ensure there are 2 contracts
    * [x] query the interface ID; ensure there are 2 contracts
    * [x] query the template ID _again_; ensure there are 2 contracts
    * [x] if this fails (with too many contracts) it is most likely to be Oracle-specific; if so, and it's fine on Postgres, the `JOIN` in `OracleQueries#selectContractsMultiTemplate` is the place to start looking e894eed23ec16c236ec3a5cd65870cfafcef370d 
* [x] other test coverage is there already, as we duplicate query/WS tests with query store on and off

The issues below are "soft prerequisites"; while we can make some advances, particularly the first four above items, we might run into weird bugs without having fixes for these in place:

* [x] #15040
* [x] #15098
* [x] #14844

### PR DESCRIPTION
**Pull request by fayi-da**
Fixes #14819.

```rst
CHANGELOG_BEGIN
- [JSON API] The JSON API query store database has changed schema and
  needs to be reset. If you are migrating from a previous version,
  either reset your database manually or start the HTTP JSON API with
  one of the options that regenerate the schema (``create-only``,
  ``create-if-needed-and-start``, ``create-and-start``).
CHANGELOG_END
```

### CODE REVIEW

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala [hunk 1]
```diff
@@ -5,14 +5,14 @@ package com.daml.http.dbbackend
...
 import nonempty.NonEmptyReturningOps._
-
 import doobie._
 import doobie.implicits._
+
 import scala.annotation.nowarn
-import scala.collection.immutable.{Seq => ISeq, SortedMap}
-import scalaz.{@@, Cord, Functor, OneAnd, Tag, \/, -\/, \/-}
+import scala.collection.immutable.{SortedMap, Seq => ISeq}
+import scalaz.{-\/, @@, Cord, Functor, OneAnd, Tag, \/, \/-}
```
Comment (S11001001) [inline ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:15]: Don't commit the garbage IntelliJ inserts; please revert.

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala [hunk 2]
```diff
@@ -582,6 +590,49 @@ object Queries {
...
+    def takeSize(size: Int, acc: Groups, remaining: Remaining): (Groups, Remaining) =
+      if (size <= 0 || remaining.isEmpty) (acc, remaining)
+      else {
+        val (k, sv) = remaining.head
+        if (sv.size <= size)
+          takeSize(size - sv.size, acc.updated(k, sv), remaining - k)
+        else {
+          // ! <= proves that both sides of the split are non-empty
+          val NonEmpty(taken) = sv take size
+          val NonEmpty(left) = sv -- taken
```
Comment (S11001001) [inline ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:612]: * [ ] factor this idea (maybe take smaller bit for faster `--`?)

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala [hunk 3]
```diff
@@ -69,13 +69,14 @@ sealed abstract class Queries(tablePrefix: String, tpIdCacheMaxEntries: Long)(im
...
         $contractTableName
-        (contract_id $contractIdType NOT NULL CONSTRAINT ${tablePrefixFr}contract_k PRIMARY KEY
+        (contract_id $contractIdType NOT NULL
         ,tpid $bigIntType NOT NULL REFERENCES $templateIdTableName (tpid)
         ,${jsonColumn(sql"key")}
         ,key_hash $keyHashColumn
         ,${jsonColumn(contractColumnName)}
         $contractsTableSignatoriesObservers
         ,agreement_text $agreementTextType
+        ,CONSTRAINT ${tablePrefixFr}contract_k PRIMARY KEY (contract_id, tpid)
```
Comment (S11001001) [inline ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:79]: * [ ] will the btree be better if the tpid is first?

File: ledger-service/db-backend/src/test/scala/com/digitalasset/http/dbbackend/QueriesSpec.scala [hunk 4]
```diff
@@ -59,6 +67,47 @@ class QueriesSpec extends AnyWordSpec with Matchers with TableDrivenPropertyChec
...
+          arbitrary[Int],
+          Gen.nonEmptyContainerOf[Set, Int](arbitrary[Int]).map { case NonEmpty(xs) => xs },
+        )
+      )
+      .map { case NonEmpty(xs) => xs }
+    implicit val shrinkArg: Shrink[Arg] = {
+      implicit val shrinkSet: Shrink[NonEmpty[Set[Int]]] =
+        Shrink { nes => Shrink.shrink(nes.forgetNE).collect { case NonEmpty(s) => s } }
+      Shrink { arg =>
+        Shrink.shrink(arg.forgetNE).collect { case NonEmpty(m) => m }
```
Comment (S11001001) [inline ledger-service/db-backend/src/test/scala/com/digitalasset/http/dbbackend/QueriesSpec.scala:92]: * [ ] factor this `Shrink`, it should be shorter generalized

File: ledger-service/db-backend/src/test/scala/com/digitalasset/http/dbbackend/QueriesSpec.scala [hunk 5]
```diff
@@ -59,6 +67,47 @@ class QueriesSpec extends AnyWordSpec with Matchers with TableDrivenPropertyChec
...
+      chunk.toNEF.foldMap(_.size)
+
+    "never exceed size in each chunk" in scForAll(sizes, randomArg) { (s, r) =>
+      all(chunkBySetSize(s, r) map measuredChunkSize) should be <= s
+    }
+
+    "make chunks as large as possible" in scForAll(sizes, randomArg) { (s, r) =>
+      all(chunkBySetSize(s, r).init map measuredChunkSize) should ===(s)
+    }
+  }
```
Comment (S11001001) [inline ledger-service/db-backend/src/test/scala/com/digitalasset/http/dbbackend/QueriesSpec.scala:110]: * [ ] extra property check: combining any two chunks with the map-of-intersection monoid should yield a map of all empty sets

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 3 above)
Comment (ray-roestenburg-da) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:79]: Maybe better to have a serial PK and then if needed a unique constraint on (contract_id, tpid)

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala [hunk 6]
```diff
@@ -303,24 +304,31 @@ sealed abstract class Queries(tablePrefix: String, tpIdCacheMaxEntries: Long)(im
...
     import cats.instances.int._
     import cats.syntax.foldable._
-    NonEmptyVector.fromVector(cids.toVector) match {
-      case None =>
+    import nonempty.catsinstances._
+    (cids: Iterable[(SurrogateTpId, Set[String])]).view.collect { case (k, NonEmpty(cids)) =>
+      (k, cids)
+    }.toMap match {
+      case NonEmpty(cids) =>
+        val chunks = maxListSize.fold(Vector(cids))(chunkBySetSize(_, cids))
```
Comment (ray-roestenburg-da) [inline ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:319]: If I understand correctly the maxListSize limits how many rows are selected for the delete at a time?

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala [hunk 7]
```diff
@@ -582,6 +590,49 @@ object Queries {
     (allTpids diff grouped.keySet).view.map((_, Map.empty[Party, Off])).toMap ++ grouped
   }
 
+  // invariant: each element x of result has `x.values.flatten.size <= size`
+  private[dbbackend] def chunkBySetSize[K, V](
```
Comment (ray-roestenburg-da) [inline ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:594]: I'll read on but maybe a good ide to do a little unit test for `chunkBySetSize`.

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala [hunk 8]
```diff
@@ -582,6 +590,49 @@ object Queries {
...
+      size: Int,
+      groups: NonEmpty[Map[K, NonEmpty[Set[V]]]],
+  ): Vector[NonEmpty[Map[K, NonEmpty[Set[V]]]]] = {
```
Comment (ray-roestenburg-da) [inline ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:597]: would it not be easier to allow for chunks to be empty and, if empty, not delete?

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala [hunk 9]
```diff
@@ -723,7 +774,7 @@ private final class PostgresQueries(tablePrefix: String, tpIdCacheMaxEntries: Lo
       s"""
         INSERT INTO $contractTableNameRaw
         VALUES (?, ?, ?::jsonb, ?, ?::jsonb, ?, ?, ?)
-        ON CONFLICT (contract_id) DO NOTHING
+        ON CONFLICT (contract_id, tpid) DO NOTHING
```
Comment (ray-roestenburg-da) [inline ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:777]: Is there an Oracle version for do nothing on conflict? (just curious)

File: ledger-service/db-backend/src/test/scala/com/digitalasset/http/dbbackend/QueriesSpec.scala [hunk 10]
```diff
@@ -59,6 +70,53 @@ class QueriesSpec extends AnyWordSpec with Matchers with TableDrivenPropertyChec
       )
     }
   }
+
+  "chunkBySetSize" should {
```
Comment (ray-roestenburg-da) [inline ledger-service/db-backend/src/test/scala/com/digitalasset/http/dbbackend/QueriesSpec.scala:74]: Nice.

**Review by ray-roestenburg-da — APPROVED** [review]

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 7 above)
Comment (S11001001) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:594]: There are a lot of tests for `chunkBySetSize`.

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 3 above)
Comment (S11001001) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:79]: We've considered a serial in the past, but it will cause tremendous contention issues with concurrent updates to the same tpid that simply go away if we don't have one.

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 8 above)
Comment (S11001001) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:597]: Unfortunately, we would implement that by filtering them out, because the SQL expression won't work on empty things.

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 9 above)
Comment (S11001001) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:777]: Yes, and I recommend sitting down before [clicking on this link](https://github.com/digital-asset/daml/pull/9286#discussion_r604141044).

Comment (S11001001) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:777]: And regarding the followup d50e483a88f9edb729571e77d30ef82560388a60 I just added to this PR, I don't know why Oracle accepted it without this change.

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 6 above)
Comment (S11001001) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:319]: It's probably overconservative to make the chunks as small as they are now, since the limiting factor seems to be the `in`. Maybe we should just go back to a single query that joins everything with `OR` all at once, only using chunks to limit the size of each argument passed to `in`.

Comment (S11001001) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:319]: #15412

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 9 above)
Comment (ray-roestenburg-da) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:777]: 🤷‍♂️

File: ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala (hunk 8 above)
Comment (ray-roestenburg-da) [reply ledger-service/db-backend/src/main/scala/com/digitalasset/http/dbbackend/Queries.scala:597]: (I meant not to have a SQL expression in the case the chunk is empty, but it's not a big deal)
