### PR TITLE
[ScenarioService] add evaluation timeout

### LINKED ISSUE #3643: DAML Studio: non-terminating recursive calls get scenario service stuck
When calling a non-terminating recursive function in an action, e.g.:

```
recF : Int -> Int
recF x = recF x
```

`scenario-service.jar` spins the CPU even before running the scenario and killing it won't help as it will re-spawn, the only way to get rid of it is closing VSCode. The following IDE problem are displayed:

```
{
	"resource": "/home/fabio/Study/Self-study/DAML/quickstart-scala/daml/Tests/Iou.daml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "\"Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusDeadlineExceeded (StatusDetails {unStatusDetails = \\\"Deadline Exceeded\\\"})))\"",
	"source": "Scenario",
	"startLineNumber": 9,
	"startColumn": 1,
	"endLineNumber": 9,
	"endColumn": 9
}
```

```
damlc: user error (Scenario service exited unexpectedly)
[Info  - 8:46:22] Connection to server got closed. Server will restart.
[Error - 8:46:22] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/main.js:902:25)
	at Object.dispose (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/client.js:2236:42)
	at LanguageClient.handleConnectionClosed (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/main.js:154:15)
	at closeHandler (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-languageclient/lib/client.js:2223:18)
	at CallbackList.invoke (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/main.js:238:26)
	at CallbackList.invoke (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/home/fabio/.vscode/extensions/digitalassetholdingsllc.daml-0.13.37/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
```

### LINKED ISSUE #13954: Ensure scenario service finishes before gRPC deadline
Currently, if the scenario service is given a script that loops, for example,

```
module Main where

import Daml.Script

main : Script ()
main = do
  pure ()
  main
```

daml studio will (eventually) only show the error message 

```
"Scenario service backend error: BErrorClient (ClientIOError (GRPCIOBadStatusCode StatusDeadlineExceeded (StatusDetails {unStatusDetails = \"Deadline Exceeded\"})))"
```

This is because the client stops waiting after a default of 60 seconds, while the server gets stuck in an infinite loop. Instead, the server should check the deadline for each request and `await` on the result of the request only for the duration of the deadline (perhaps subtracting a few seconds to be safe).

We should try to turn this into a proper script execution failure, if possible showing the partial ledger state before the timeout. 

Note: this was previously https://github.com/digital-asset/daml/issues/13518, but the associated PR fixes other fatal errors instead.

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
fixes #3643, 
fixes #13954

No measurable slow down:

-- before -- 
```
Result "com.daml.lf.speedy.perf.CollectAuthority.bench":
  11.859 ±(99.9%) 0.019 ms/op [Average]
  (min, avg, max) = (11.730, 11.859, 12.158), stdev = 0.079
  CI (99.9%): [11.841, 11.878] (assumes normal distribution)


# Run complete. Total time: 00:07:14

Benchmark                                                             (dar)             (scenario)  Mode  Cnt   Score   Error  Units
CollectAuthority.bench  //daml-lf/scenario-interpreter/CollectAuthority.dar  CollectAuthority:test  avgt  200  11.859 ± 0.019  ms/op
```

-- after --
```
Result "com.daml.lf.speedy.perf.CollectAuthority.bench":
  11.740 ±(99.9%) 0.026 ms/op [Average]
  (min, avg, max) = (11.542, 11.740, 12.098), stdev = 0.108
  CI (99.9%): [11.714, 11.765] (assumes normal distribution)


# Run complete. Total time: 00:07:15

Benchmark                                                             (dar)             (scenario)  Mode  Cnt   Score   Error  Units
CollectAuthority.bench  //daml-lf/scenario-interpreter/CollectAuthority.dar  CollectAuthority:test  avgt  200  11.740 ± 0.026  ms/op
```

### CODE REVIEW

File: compiler/scenario-service/client/src/DA/Daml/LF/PrettyScenario.hs [hunk 1]
```diff
@@ -495,6 +495,8 @@ prettyScenarioErrorError (Just err) =  do
         , label_ "Template: " $ prettyMay "<missing template>" (prettyDefName world) templateId
         , label_ "Key Hash: " $ ltext keyHash
         ]
+    ScenarioErrorErrorEvaluationTimeout timeout ->
+      pure $ text $ T.pack $ "Evaluation times out after " <> show timeout <> " seconds"
```
Comment (akrmn) [inline compiler/scenario-service/client/src/DA/Daml/LF/PrettyScenario.hs:499]:
```suggestion
      pure $ text $ T.pack $ "Evaluation timed out after " <> show timeout <> " seconds"
```

File: compiler/damlc/tests/daml-test-files/Loop.daml [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+-- SPDX-License-Identifier: Apache-2.0
+
+-- @ENABLE-SCENARIOS
+
+module Loop where
+
+loop : Int -> ()
+loop x = loop (x + 1) 
+
+-- @ERROR range=12:1-12:25; Evaluation times out after 5 seconds
```
Comment (akrmn) [inline compiler/damlc/tests/daml-test-files/Loop.daml:11]:
```suggestion
-- @ERROR range=12:1-12:25; Evaluation timed out after 5 seconds
```

File: compiler/damlc/tests/daml-test-files/Loop.daml [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+  with
+    p : Party
+  where
+    signatory p
+    choice Go : ()
+      controller p
+      do
+        pure $ loop 1
+
+-- @ERROR range=27:1-27:23; Evaluation times out after 5 seconds
```
Comment (akrmn) [inline compiler/damlc/tests/daml-test-files/Loop.daml:26]:
```suggestion
-- @ERROR range=27:1-27:23; Evaluation timed out after 5 seconds
```

File: compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/ScenarioServiceMain.scala [hunk 4]
```diff
@@ -37,6 +38,7 @@ private final case class ScenarioServiceConfig(
 private object ScenarioServiceConfig {
   // default to 128MB
   val DefaultMaxInboundMessageSize: Int = 128 * 1024 * 1024
+  val DefaultTimeout = 60.seconds
```
Comment (akrmn) [inline compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/ScenarioServiceMain.scala:41]: is this used?

File: compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/scenario/Context.scala [hunk 5]
```diff
@@ -35,8 +34,10 @@ object Context {
 
   private val contextCounter = new AtomicLong()
 
-  def newContext(lfVerion: LanguageVersion)(implicit loggingContext: LoggingContext): Context =
-    new Context(contextCounter.incrementAndGet(), lfVerion)
+  def newContext(lfVerion: LanguageVersion, timeout: Duration)(implicit
+      loggingContext: LoggingContext
+  ): Context =
+    new Context(contextCounter.incrementAndGet(), lfVerion, timeout)
```
Comment (akrmn) [inline compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/scenario/Context.scala:40]:
```suggestion
  def newContext(lfVersion: LanguageVersion, timeout: Duration)(implicit
      loggingContext: LoggingContext
  ): Context =
    new Context(contextCounter.incrementAndGet(), lfVersion, timeout)
```

File: compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/ScenarioServiceMain.scala (hunk 4 above)
Comment (remyhaemmerle-da) [reply compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/ScenarioServiceMain.scala:41]: Good catch.

Comment (remyhaemmerle-da) [inline compiler/scenario-service/server/src/main/scala/com/digitalasset/daml/lf/ScenarioServiceMain.scala:41]:
```suggestion
```

**Review by akrmn — APPROVED** [review]
very nice, thank you @remyhaemmerle-da!
