### PR TITLE
Sandbox & kvutils: Use the existing ledger ID if no ledger ID is specified.

### LINKED ISSUE #4324: Sandbox is confused about whether not providing a ledger ID is OK.
Currently, our `SqlLedger` (and `ReadOnlySqlLedger`) take an _optional_ ledger ID. They follow this logic:

- there is no existing ledger ID _and_ no ledger ID is provided: **generate a new ID (typically a UUID)**
- there is no existing ledger ID _and_ a ledger ID is provided: **use the provided ID**
- there is an existing ledger ID _and_ no ledger ID is provided: **use the existing ID**
- there is an existing ledger ID _and_ a ledger ID is provided: **compare them and crash if they're different**

This seems pretty logical. However, we never pass `None` to their constructors except in tests.

Instead, if no ledger ID is provided, we generate one further up in the chain (by `SandboxServer`, or by whatever ledger implementation you're using, which will pass it to `JdbcIndex`).

This means we never trigger the case where there's an existing ID and no ID is provided: we always generate an ID, so this will fail because they will be different.

If I start Sandbox twice with no ledger ID against the same backend store (in this case an H2 database file), it fails:

```
Ledger id mismatch. Ledger id given ('sandbox-4492c9df-e886-43af-8cdd-fffde7532c74') is not equal to the existing one ('sandbox-e4a6a25c-7544-45af-bc8e-3392695235e9')! (context: {participantId=sandbox-participant})
```

I'm not sure which behavior is correct. Forcing the user to specify the ledger ID might mitigate certain classes of failure where they accidentally run against the wrong backend; on the other hand, it's far more inconvenient.

Either way, we need to delete some code; either we should propagate the `None` through to `SqlLedger` or we should make it non-optional.

Thoughts?

### PR DESCRIPTION
**Pull request by SamirTalwar-DA**
Closes #4324 and #4423. See those issues for details.

### Changelog

- **[Sandbox]** If no ledger ID is provided when running against an existing ledger, use the existing ID. Previously, Sandbox would fail to start.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala [hunk 1]
```diff
@@ -425,89 +426,93 @@ private final class SqlLedgerFactory(ledgerDao: LedgerDao)(implicit logCtx: Logg
...
-      case None =>
-        logger.info("No ledger id given. Looking for existing ledger in database.")
-        ledgerDao
-          .lookupLedgerId()
-          .flatMap {
-            case Some(foundLedgerId) => ledgerFound(foundLedgerId)
-            case None =>
-              val randomLedgerId = LedgerIdGenerator.generateRandomId()
-              doInit(randomLedgerId).map(_ => randomLedgerId)(DEC)
-          }(DEC)
```
Comment (SamirTalwar-DA) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedger.scala]: Previously, this code path was never hit. Which is a good thing, because it was wrong—it didn't take into account any packages or entries provided.

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/Database.scala [hunk 2]
```diff
@@ -211,7 +211,10 @@ object Database {
         .placeholders(Map("table.prefix" -> TablePrefix).asJava)
         .table(TablePrefix + Flyway.configure().getTable)
         .dataSource(adminConnectionPool)
-        .locations(s"classpath:/com/daml/ledger/on/sql/migrations/${system.name}")
+        .locations(
+          "classpath:/com/daml/ledger/on/sql/migrations/common",
```
Comment (gerolf-da) [inline ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/Database.scala]: Sharing migrations across sql dialects means we now share the maximum migration number as well, right?

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/queries/Queries.scala [hunk 3]
```diff
@@ -32,8 +37,11 @@ trait Queries {
 object Queries {
   val TablePrefix = "ledger"
   val LogTable = s"${TablePrefix}_log"
+  val MetaTable = s"${TablePrefix}_meta"
   val StateTable = s"${TablePrefix}_state"
 
+  private[queries] val MetaTableKey = 0
```
Comment (gerolf-da) [inline ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/queries/Queries.scala]: What does this mean?

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/Database.scala (hunk 2 above)
Comment (SamirTalwar-DA) [reply ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/Database.scala]: Yup, absolutely. I think this is probably a good thing.

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/queries/Queries.scala (hunk 3 above)
Comment (SamirTalwar-DA) [reply ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/queries/Queries.scala]: Pushed a comment:

> By explicitly writing a value to a "table_key" column, we ensure we only ever have one row in the meta table. An attempt to write a second row will result in a key conflict.

File: ledger/api-server-damlonx/reference-v2/src/main/scala/com/daml/ledger/api/server/damlonx/reference/v2/InMemoryKVParticipantState.scala [hunk 4]
```diff
@@ -35,18 +34,24 @@ import org.slf4j.LoggerFactory
...
+import scala.concurrent.duration.DurationInt
 import scala.concurrent.{Await, ExecutionContext, Future}
 import scala.util.Try
 
 object InMemoryKVParticipantState {
 
+  /** Get a new record time for the ledger from the system clock.
+    * Public for use from integration tests.
+    */
+  private def now(): Timestamp =
```
Comment (stefanobaghino-da) [inline ledger/api-server-damlonx/reference-v2/src/main/scala/com/daml/ledger/api/server/damlonx/reference/v2/InMemoryKVParticipantState.scala]: Would it make sense to rather let constructor callers optionally pass a `() => Timestamp` so that they can read it?

Comment (stefanobaghino-da) [reply ledger/api-server-damlonx/reference-v2/src/main/scala/com/daml/ledger/api/server/damlonx/reference/v2/InMemoryKVParticipantState.scala]: Maybe passing a `Clock` could make sense in this case, depending on what the callers have to expect.

File: ledger/api-server-damlonx/reference-v2/src/main/scala/com/daml/ledger/api/server/damlonx/reference/v2/InMemoryKVParticipantState.scala [hunk 5]
```diff
@@ -35,18 +34,24 @@ import org.slf4j.LoggerFactory
...
+    Timestamp.assertFromInstant(Clock.systemUTC().instant())
+
   /** The complete state of the ledger at a given point in time.
     * This emulates a key-value blockchain with a log of commits and a key-value store.
     * The commit log provides the ordering for the log entries, and its height is used
     * as the [[Offset]].
     * */
-  case class State(
+  private case class State(
```
Comment (stefanobaghino-da) [inline ledger/api-server-damlonx/reference-v2/src/main/scala/com/daml/ledger/api/server/damlonx/reference/v2/InMemoryKVParticipantState.scala]: Nice, thanks!

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/Database.scala [hunk 6]
```diff
@@ -18,7 +18,7 @@ import scala.concurrent.duration.Duration
 import scala.concurrent.{ExecutionContext, Future}
 import scala.util.{Failure, Success}
 
-class Database(
+final class Database(
```
Comment (stefanobaghino-da) [inline ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/Database.scala]: Makes a lot of sense, thank you!

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala [hunk 7]
```diff
@@ -122,9 +124,25 @@ object SqlLedgerReaderWriter {
     for {
       uninitializedDatabase <- Database.owner(jdbcUrl)
       database = uninitializedDatabase.migrate()
+      queries = database.queries
+      ledgerId <- ResourceOwner.forFuture(() =>
+        database.inWriteTransaction("Checking ledger ID at startup") { implicit connection =>
```
Comment (stefanobaghino-da) [inline ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala]: Probably worth putting the thunk passed to `ResourceOwner.forFuture` in its own method.

File: libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala [hunk 8]
```diff
@@ -67,9 +67,12 @@ class ProgramResource[T](
 }
 
 object ProgramResource {
-  abstract class StartupException(message: String)
-      extends RuntimeException(message)
-      with NoStackTrace
 
-  abstract class SuppressedStartupException extends RuntimeException
+  trait StartupException extends NoStackTrace {
+    self: Exception =>
```
Comment (stefanobaghino-da) [inline libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala]: Why the self-type?

File: ledger/ledger-api-common/src/main/scala/com/digitalasset/platform/common/LedgerIdMode.scala [hunk 9]
```diff
@@ -3,19 +3,36 @@
 
 package com.digitalasset.platform.common
 
+import com.digitalasset.daml.lf.data.Ref
 import com.digitalasset.ledger.api.domain.LedgerId
 
-sealed abstract class LedgerIdMode extends Product with Serializable
+sealed abstract class LedgerIdMode extends Product with Serializable {
+  def or(other: => LedgerId): LedgerId
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-common/src/main/scala/com/digitalasset/platform/common/LedgerIdMode.scala]: This is effectively a noop when called over `Static`. :thinking: 

Stupid question: do we really need this type? Or can we do with just `Option[LedgerId]`?

Not necessarily an issue for this PR, so don't feel compelled to address this here.

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala [hunk 10]
```diff
@@ -122,9 +124,25 @@ object SqlLedgerReaderWriter {
...
+                domain.LedgerId(initialLedgerId.get),
+              ))
+          } else {
+            Future.successful(ledgerId)
+          }
+      })
       head <- ResourceOwner.forFuture(() =>
         database.inReadTransaction("Reading head at startup") { implicit connection =>
-          Future(database.queries.selectLatestLogEntryId().map(_ + 1).getOrElse(StartIndex))
+          Future.successful(queries.selectLatestLogEntryId().map(_ + 1).getOrElse(StartIndex))
```
Comment (stefanobaghino-da) [inline ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala]: This operation and the previous one can probably be composed in a `Future` as part of another method so that we don't have to wrap in a `ResourceOwner` twice over two steps.

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/index/ReadOnlySqlLedger.scala [hunk 11]
```diff
@@ -60,59 +62,29 @@ object ReadOnlySqlLedger {
...
-
-    private def ledgerFound(foundLedgerId: LedgerId) = {
-      logger.info(s"Found existing ledger with id: ${foundLedgerId.unwrap}")
-      Future.successful(foundLedgerId)
-    }
+    private def initialize(initialLedgerId: LedgerId): Future[LedgerId] =
+      ledgerDao
+        .lookupLedgerId()
+        .flatMap {
+          case Some(foundLedgerId) if foundLedgerId == initialLedgerId =>
```
Comment (stefanobaghino-da) [inline ledger/sandbox/src/main/scala/com/digitalasset/platform/index/ReadOnlySqlLedger.scala]:
```suggestion
          case Some(`initialLedgerId`) =>
```

File: ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedgerSpec.scala [hunk 12]
```diff
@@ -61,15 +65,15 @@ class SqlLedgerSpec
...
+        ledger.ledgerId should not be ""
       }
     }
 
     "be able to be created from scratch with a given ledger ID" in {
       for {
         ledger <- createSqlLedger(ledgerId)
       } yield {
-        ledger.ledgerId should not be equal(LedgerId)
+        ledger.ledgerId should be(ledgerId)
```
Comment (stefanobaghino-da) [inline ledger/sandbox/src/test/suite/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/SqlLedgerSpec.scala]: Good catch!

File: ledger/api-server-damlonx/reference-v2/src/main/scala/com/daml/ledger/api/server/damlonx/reference/v2/InMemoryKVParticipantState.scala (hunk 4 above)
Comment (SamirTalwar-DA) [reply ledger/api-server-damlonx/reference-v2/src/main/scala/com/daml/ledger/api/server/damlonx/reference/v2/InMemoryKVParticipantState.scala]: I just moved and renamed this function to fix a couple of warnings. Don't want to improve upon this code because it's going to be deleted.

File: libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala (hunk 8 above)
Comment (SamirTalwar-DA) [reply libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala]: To make sure people don't forget to actually extend `RuntimeException` or similar.

File: ledger/ledger-api-common/src/main/scala/com/digitalasset/platform/common/LedgerIdMode.scala (hunk 9 above)
Comment (SamirTalwar-DA) [reply ledger/ledger-api-common/src/main/scala/com/digitalasset/platform/common/LedgerIdMode.scala]: I got the feeling it's for nicer Java compatibility, but I have no real evidence.

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala (hunk 10 above)
Comment (SamirTalwar-DA) [reply ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala]: True, but then we have to return a tuple, which is less pleasant. I'm happy to combine this one with the next one, for the dispatcher.

File: libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala (hunk 8 above)
Comment (stefanobaghino-da) [reply libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala]: Then why removing the `RuntimeException`? :slightly_smiling_face:

File: ledger/sandbox/src/main/scala/com/digitalasset/platform/index/ReadOnlySqlLedger.scala (hunk 11 above)
Comment (SamirTalwar-DA) [reply ledger/sandbox/src/main/scala/com/digitalasset/platform/index/ReadOnlySqlLedger.scala]: Done; went with:

```suggestion
          case Some(foundLedgerId @ `initialLedgerId`) =>
```

File: libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala (hunk 8 above)
Comment (SamirTalwar-DA) [reply libs-scala/resources/src/main/scala/com/digitalasset/resources/ProgramResource.scala]: Because it allows me to do `new LedgerIdMismatchException(…) with StartupException`, which means that `LedgerIdMismatchException` can be moved to _ledger-api-common_, which doesn't have access to `StartupException` and doesn't know anything about the concept of "startup".

File: ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala (hunk 7 above)
Comment (SamirTalwar-DA) [reply ledger/ledger-on-sql/src/main/scala/com/daml/ledger/on/sql/SqlLedgerReaderWriter.scala]: Pulled this and the other thunk out. 🙂
