### PR TITLE
Fixes #1755: Carefully fix json message to release artefacts

### LINKED ISSUE #1755: Fix Maven release JSON message (second attempt)

### PR DESCRIPTION
**Pull request by nicholassmith-da**
### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: release/src/Upload.hs [hunk 1]
```diff
@@ -235,7 +235,7 @@ publishStagingRepo baseRequest manager comDamlRepoId comDigitalassetRepoId = do
          $ setRequestPath  "/service/local/staging/bulk/promote"
          $ setRequestHeader "content-type" [ "application/json" ]
          $ setRequestHeader "accept" [ "application/json" ]
-         $ setRequestBodyLBS (textToLazyByteString $ "{\"data\":{\"stagedRepositoryIds\":[\"" <> comDamlRepoId <> "\",\"" <> comDigitalassetRepoId <> "]\",\"description\":\"\",\"autoDropAfterRelease\":true}}") baseRequest
+         $ setRequestBodyLBS (textToLazyByteString $ "{\"data\":{\"stagedRepositoryIds\":[\"" <> comDamlRepoId <> "\",\"" <> comDigitalassetRepoId <> "\"],\"description\":\"\",\"autoDropAfterRelease\":true}}") baseRequest
```
Comment (cocreature) [inline release/src/Upload.hs]: You might just want to switch to `aeson` for doing the JSON encoding to avoid that kind of error prone string munging.

Comment (nicholassmith-da) [reply release/src/Upload.hs]: I will, if this release round doesn't work!
