### PR TITLE
Handle exceptions when sending logOptOut messages

### LINKED ISSUE #1487: IDE crashes if telemetry can't connect
A user reported this error in the IDE:

```
-hs-damlc-app: HttpExceptionRequest Request {
  host                 = "logs.daml.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Content-Type","application/json; charset=utf-8")]
  path                 = "log/ide/"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
(InternalException (HostCannotConnect "logs.daml.com" [Network.Socket.connect: <socket: 508>: failed (Connection timed out (WSAETIMEDOUT))]))
[Error - 13:26:52] Connection to server got closed. Server will not be restarted.
```

It suggests the IDE errors fatally if the logger can't connect. Failure to log should never result in a fatal error.

### PR DESCRIPTION
**Pull request by cocreature**
We already do this for all other log messages and it makes sense to do
it for the opt out message as well.

This should fix #1487.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs [hunk 1]
```diff
@@ -333,28 +335,31 @@ fetchMachineID = do
...
     env <- initialiseEnv
     let msg :: T.Text = "Opted out of telemetry"
     optOut <- createLog env Lgr.Info msg
     unless exists do
-        res <- sendLogs [optOut]
-        when (Prelude.null res) $
-            writeFile fp ""
+        res <- try $ do
+            res <- sendLogs [optOut]
+            when (null res) $ writeFile fp ""
```
Comment (neil-da) [inline libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs]: Thanks! This annoyed me too.

File: libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs [hunk 2]
```diff
@@ -311,6 +310,9 @@ sendLogQueue gcp@GCPState{..} runSync = do
           void $
           forkFinally send (handleResult)
 
+logException :: Exception e => Lgr.Handle m -> e -> m ()
+logException handle e = Lgr.logJson handle Lgr.Error $ displayException e
```
Comment (neil-da) [inline libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs]: Should this be somewhere shared? With the rest of the log functions?

Comment (neil-da) [reply libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs]: Should it also record the stack trace? Does displayException usually include that?

File: libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs [hunk 3]
```diff
@@ -49,10 +49,11 @@ import qualified Data.ByteString.Lazy as LBS
 import qualified Data.ByteString as BS
 import qualified Data.ByteString.UTF8 as UTFBS
 import Data.Time as Time
-import Data.UUID
+import Data.UUID (UUID)
+import qualified Data.UUID as UUID
```
Comment (neil-da) [inline libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs]: Thanks!

File: libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs (hunk 2 above)
Comment (cocreature) [reply libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs]: You don’t get a stack trace for where the exception was thrown unless you compile with profiling info. I suppose we could include the location of the call to `logException` but I am not sure that’s particularly useful.
I generally tend to keep these helpers local until I actually need them somewhere else.

Comment (neil-da) [reply libs-haskell/da-hs-base/src/DA/Service/Logger/Impl/GCP.hs]: Fair enough on both counts.
