### PR TITLE
Log all authorization errors

### LINKED ISSUE #3955: Show reason for authorization failure in server logs
For a ledger instance where authorization is enabled, when a particular field of the presented JWT token is invalid or rejected, there is not detail given on which field has been rejected and why, but rather a general "Not authorized for this operation" error is given.

To aid in troubleshooting during development and integration, the fields which have caused the unauthorized message should be displayed in the server logs

Steps to reproduce
1) Generate an RSA private key and cert as per https://docs.daml.com/tools/sandbox.html#generating-tokens

`openssl req -nodes -new -x509  -keyout sandbox.key -out sandbox.crt`

2) Start up a sandbox instance with authentication enabled, passing the generated cert - nhealey@brianhealey7yhtdg ~/g/daml [ECDA512-algo-support]
`daml sandbox --auth-jwt-rs256-crt sandbox.crt --log-level DEBUG`

3) Create a JWT request on jwt.io with a dummy ledgerId and pasting in the contents of the private key
image

4) save the file to `jwt.token` file and run daml ledger list-parties command in a project you have created passing that token
`daml ledger list-parties --access-token-file jwt.token`

### PR DESCRIPTION
**Pull request by rautenrieth-da**
Fixes #3955.

The example from the above issue produces the following log line:

```
WARN: Permission denied. Reason: Invalid ledger. Claims are only valid for ledgerId blah, actual ledgerId is 299b31df-74ed-4ea3-bbe7-bb7cc7e8b23e. (context: {Claims=Claims(List(ClaimPublic),Some(blah),None,None,None)})
```

CHANGELOG_BEGIN
- [Ledger API Server] The ledger API server now prints detailed log messages
  whenever a request was rejected due to a failed
  authorization.
CHANGELOG_END

### CODE REVIEW

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 1]
```diff
@@ -7,37 +7,79 @@ import java.time.Instant
...
+
   /** Validates all properties of claims that do not depend on the request,
     * such as expiration time or ledger ID. */
-  private def valid(claims: Claims): Boolean =
-    claims.notExpired(now()) &&
-      claims.validForLedger(ledgerId) &&
-      claims.validForParticipant(participantId)
+  private def valid(claims: Claims): AuthorizationResult =
+    for {
+      _ <- if (claims.notExpired(now())) Authorized else NotAuthorized("Claims expired")
```
Comment (SamirTalwar-DA) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:45]: Perhaps the various `Claims` methods could return an `AuthorizationResult`?

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 2]
```diff
@@ -60,8 +89,13 @@ final class Authorizer(now: () => Instant, ledgerId: String, participantId: Stri
       parties: Iterable[String],
       call: Req => Future[Res]): Req => Future[Res] =
     authorize(call) { claims =>
-      valid(claims) &&
-      parties.forall(claims.canReadAs)
+      for {
+        _ <- valid(claims)
+        _ <- parties.foldLeft[Either[AuthorizationError, Unit]](Right(()))((acc, e) =>
+          acc.flatMap(_ => claims.canReadAs(e)))
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:95]: This is quite long, it would be probably better to factor it out in a private method. Looking at the previous method, it appears that you can factor out the folding and pass the function that actually performs the check (something like `forall`, but on an `Either` -- not sure whether something like this exists already).

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 3]
```diff
@@ -72,9 +106,14 @@ final class Authorizer(now: () => Instant, ledgerId: String, participantId: Stri
       applicationId: Option[String],
       call: Req => Future[Res]): Req => Future[Res] =
     authorize(call) { claims =>
-      valid(claims) &&
-      party.forall(claims.canActAs) &&
-      applicationId.forall(claims.validForApplication)
+      for {
+        _ <- valid(claims)
+        _ <- party.fold[Either[AuthorizationError, Unit]](Right(()))(p => claims.canActAs(p))
+        _ <- applicationId.fold[Either[AuthorizationError, Unit]](Right(()))(id =>
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:112]: As above, I would factor the folding out.

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 4]
```diff
@@ -96,10 +135,21 @@ final class Authorizer(now: () => Instant, ledgerId: String, participantId: Stri
...
 
   private def ongoingAuthorization[Res](scso: ServerCallStreamObserver[Res], claims: Claims) =
-    new OngoingAuthorizationObserver[Res](scso, claims, _.notExpired(now()), permissionDenied())
+    new OngoingAuthorizationObserver[Res](
+      scso,
+      claims,
+      _.notExpired(now()),
+      authorizationError => {
+        // Note: only put the claims in the context, as the request can be huge
+        newLoggingContext("Claims" -> claims.toString) { implicit logCtx =>
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:144]: 1. If you want to keep the claims around, here I would recommend creating a function that takes the claims and returns a `Seq[(String, String)]` (passing it with a `:_ *). Note that everywhere else in we use lower-case keys for logging context.
2. I'm not entirely sure we should create a whole new logging context here (putting the entirety of the claims in it), as we only have a single line that already reports the exact error with the information as to what went wrong and how. Logging contexts are useful when you have a nested series of calls that need to enrich the information along the way. If you think we should have a logging context by the time we get here and enrich it with the claims information, I would recommend doing it up the call stack.

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 5]
```diff
@@ -108,29 +158,43 @@ final class Authorizer(now: () => Instant, ledgerId: String, participantId: Stri
...
+                call(
+                  request,
+                  if (claims.expiration.isDefined)
+                    ongoingAuthorization(scso, claims)
+                  else
+                    scso
+                )
+              case Left(authorizationError) =>
+                // Note: only put the claims in the context, as the request can be huge
+                newLoggingContext("Claims" -> claims.toString) { implicit logCtx =>
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:172]: Same as above.

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 6]
```diff
@@ -108,29 +158,43 @@ final class Authorizer(now: () => Instant, ledgerId: String, participantId: Stri
...
         .fold(
           Future.failed,
           claims =>
-            if (authorized(claims)) call(request)
-            else Future.failed(permissionDenied())
+            authorized(claims) match {
+              case Right(_) => call(request)
+              case Left(authorizationError) =>
+                // Note: only put the claims in the context, as the request can be huge
+                newLoggingContext("Claims" -> claims.toString) { implicit logCtx =>
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:193]: Same as above.

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/AuthorizationError.scala [hunk 7]
```diff
@@ -0,0 +1,55 @@
+// Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
+// SPDX-License-Identifier: Apache-2.0
+
+package com.daml.ledger.api.auth
+
+import java.time.Instant
+
+sealed abstract class AuthorizationError {
```
Comment (stefanobaghino-da) [inline ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/AuthorizationError.scala:8]: Instead of prepending each implementation with `AuthorizationError`, I would recommend putting them all in a companion object.

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala [hunk 8]
```diff
@@ -48,9 +71,15 @@ final class Authorizer(now: () => Instant, ledgerId: String, participantId: Stri
...
     authorize(call) { claims =>
-      valid(claims) &&
-      parties.forall(claims.canReadAs) &&
-      applicationId.forall(claims.validForApplication)
+      for {
+        _ <- valid(claims)
+        _ <- parties.foldLeft[Either[AuthorizationError, Unit]](Right(()))((acc, e) =>
+          acc.flatMap(_ => claims.canReadAs(e)))
+        _ <- applicationId.fold[Either[AuthorizationError, Unit]](Right(()))(id =>
+          claims.validForApplication(id))
```
[the remark this answers is not in the document]
Comment (gerolf-da) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:79]: not using fold but `.map(...).getOrElse(...)` let's you get rid of the explicit type annotation, because `validForApplication(id)` already determines the type:
```scala
_ <- applicationId.map(claims.validForApplication).getOrElse(Right()))
``` 

might still be a long line though.

File: ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala (hunk 4 above)
Comment (rautenrieth-da) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:144]: > I'm not entirely sure we should create a whole new logging context here

The only reason to use the logging context here is to make sure the error uses the same formatting as all other log messages. For example, in case we want to make ContextualizedLogger write JSON objects.

Without the entire claims in the log line, there is indeed no reason to use a `ContextualizedLogger`.

Comment (stefanobaghino-da) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala:146]: What do you think about tackling this with the rest of the story around using our contextual logging more? I think that we should create logging contexts when receiving a request and pushing them down the call stack to enrich them, but I would refrain from putting extra keys in the logging context only for formatting a single line.

Comment (SamirTalwar-DA) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala]: I'd rather we didn't just do string munging because our logging API makes it hard to add extra one-off key-value pairs. Strings just need parsing later.

If we find ourselves doing this a lot, let's make an abstraction that handles it.

Comment (rautenrieth-da) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala]: I have removed the extra key-value pair because, as @stefanobaghino-da mentioned, the important information is already in the error message. The class now uses a plain logger.

Comment (SamirTalwar-DA) [reply ledger/ledger-api-auth/src/main/scala/com/digitalasset/ledger/api/auth/Authorizer.scala]: Not sure why we want to throw away useful information, but I'm happy to ship this for now until we re-evaluate logging in a more holistic fashion.
