### PR TITLE
Run a package-wide name collision check when building a DAR.

### LINKED ISSUE #3252: Perform DAML-LF name collision check in Haskell per package, not per module.
After a refactor of my DAML code, I'm getting this rather scary error upon submitting commands on a fresh sandbox started with
```
daml start --sandbox-option="--ledgerid=danban" --sandbox-option="-w"
```

This persists after a `daml clean`.

```
Submission of command d7be6093-df87-4d92-b2dd-3d63d1686d10 has failed.
com.digitalasset.daml.lf.validation.ECollision: null
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$6(Collision.scala:35)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$2(Collision.scala:32)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkCollisions$2$adapted(Collision.scala:31)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.digitalasset.daml.lf.validation.Collision$.checkCollisions(Collision.scala:31)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkPackage$2(Collision.scala:15)
	at com.digitalasset.daml.lf.validation.Collision$.$anonfun$checkPackage$2$adapted(Collision.scala:15)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
	at com.digitalasset.daml.lf.validation.Collision$.checkPackage(Collision.scala:15)
	at com.digitalasset.daml.lf.validation.Validation$.checkPackage(Validation.scala:28)
	at com.digitalasset.daml.lf.validation.Validation$.checkPackage(Validation.scala:17)
	at com.digitalasset.daml.lf.speedy.Compiler.compilePackage(Compiler.scala:131)
	at com.digitalasset.daml.lf.engine.ConcurrentCompiledPackages.addPackageInternal(ConcurrentCompiledPackages.scala:60)
	at com.digitalasset.daml.lf.engine.ConcurrentCompiledPackages.addPackage(ConcurrentCompiledPackages.scala:39)
	at com.digitalasset.daml.lf.engine.Result$.$anonfun$needPackage$2(Result.scala:108)
	at com.digitalasset.daml.lf.engine.CommandPreprocessor.$anonfun$preprocessCommands$3(CommandPreprocessor.scala:225)
	at com.digitalasset.daml.lf.engine.Result.$anonfun$flatMap$2(Result.scala:37)
	at com.digitalasset.platform.sandbox.stores.ledger.CommandExecutorImpl.$anonfun$consume$3(CommandExecutorImpl.scala:107)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Unhandled internal error.
```

To reproduce, checkout branch https://github.com/bame-da/react-kanban/tree/daml-refactor/danban, start using the above command, log in as `Admin` through Navigator, and try to create a `Danban:App` with `operator = Admin`.

I don't know whether the issue is with the interpreter of the LF that's being generated so assigning  both @hurryabit and @gerolf-da .

### PR DESCRIPTION
**Pull request by associahedron**
Fixes #3252 for real this time.

I moved the name collision check out of `MonadGamma` since it really didn't use any of the typechecking features, and the error-reporting features were pretty superfluous -- and I want to run the check separately on a whole package.

### CODE REVIEW

File: compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/NameCollision.hs [hunk 1]
```diff
@@ -156,48 +164,67 @@ checkDataType moduleName DefDataType{..} =
...
-checkModuleFully m = do
+checkModule :: Module -> NCMonad ()
+checkModule m = do
     checkModuleName m
-    checkModuleTypes m
+    checkModuleBody m
 
--- | Is the first module an ascendant of the second? This check
--- is case-insensitive because name collisions are case-insensitive.
+-- | Is one module an ascendant of another? For instance
```
Comment (cocreature) [inline compiler/daml-lf-tools/src/DA/Daml/LF/TypeChecker/NameCollision.hs]: thanks for the nice comment!
