### PR TITLE
Fail if modules listed in exposed-modules are not in the DALF

### LINKED ISSUE #1041: Warn when exposed modules do not exist
Currently `daml build` will succeed and produce a DAR even when the modules listed do not exist. This can be rather confusing, e.g., I created a new project with `daml new`, then renamed the main daml file and changed `source:` but forgot to update `exposed-modules:` which lead to a really confusing error about a missing module.

cc @robin-da

### PR DESCRIPTION
**Pull request by cocreature**
fixes #1041

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/docs/source/support/release-notes.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Base.hs [hunk 1]
```diff
@@ -45,6 +45,9 @@ type ModuleName = Tagged ModuleNameTag [T.Text]
 data ModuleNameTag
 deriving instance Data ModuleNameTag
 
+moduleNameString :: ModuleName -> T.Text
```
Comment (hurryabit) [inline compiler/daml-lf-ast/src/DA/Daml/LF/Ast/Base.hs]: `DA.Daml.LF.Ast.Util` would be a better home for this function.
