### PR TITLE
Handle imports for builtin types correctly in Daml export

### LINKED ISSUE #10438: daml ledger export: build errors due to missing data constructors
## Overview

Testing with larger exports of the ledger export tool, I see sometimes build errors due to missing data constructors of internal modules. Some of them I have been able to resolve (specifically `DA.Date`, `DA.Time` and `DA.TextMap`) using the linting suggestions fuzzy matching on the available import space, but one of them in particular I don't know how to resolve, relating to `DA.Types.Tuple4`. I suspect that these issues are due to out of date versions of DA internal modules being used in the *customer templates*, but don't have any way to substantiate this.

Here is the original build output, the diffs I've made to the generated code to attempt to work around, and the final build error after my changes.

## Original Build Output (sample)

```
File:     Export.daml
Hidden:   no
Range:    312:42-312:54
Source:   typecheck
Severity: DsError
Message: 
  Export.daml:312:42: error:
  Not in scope: ‘DA.Date.date’
  No module named ‘DA.Date’ is imported.
```

```
File:     Export.daml
Hidden:   no
Range:    320:21-320:33
Source:   typecheck
Severity: DsError
Message: 
  Export.daml:320:21: error:
  Not in scope: ‘DA.Time.time’
  No module named ‘DA.Time’ is imported.
```

```
  No module named ‘TextMap’ is imported.
File:     Export.daml
Hidden:   no
Range:    382:22-382:38
Source:   typecheck
Severity: DsError
Message: 
  Export.daml:382:22: error:
  Not in scope: ‘TextMap.fromList’
  Perhaps you meant ‘DA.TextMap.fromList’ (imported from DA.TextMap)
  No module named ‘TextMap’ is imported.
```

## Diff (sample)

```
+import qualified DA.Time as DATime
+import qualified DA.Date as DADate
```

...

```
-      users = (TextMap.fromList [])
-      chargeUUIDs = (TextMap.fromList [])
-      failedChargeUUIDs = (TextMap.fromList [])
+      users = (DA.TextMap.fromList [])
+      chargeUUIDs = (DA.TextMap.fromList [])
+      failedChargeUUIDs = (DA.TextMap.fromList [])
```

```
-      usageCreationTime = (DA.Time.time (DA.Date.date 2021 DA.Date.Jul 27) 21 47 35)
+      usageCreationTime = (DATime.time (DADate.date 2021 DADate.Jul 27) 21 47 35)
```

## Final Build Output (complete)

```
$ daml build
Compiling export to a DAR.
File:     Export.daml
Hidden:   no
Range:    431:14-431:29
Source:   typecheck
Severity: DsError
Message: 
  Export.daml:431:14: error:
  Not in scope: data constructor ‘DA.Types.Tuple4’
  Module ‘DA.Types’ does not export ‘Tuple4’.
ERROR: Creation of DAR file failed.
```

## Summary

For DA.Date, replacing DA.Date with DADate and a qualified import fixes, and similarly for DA.Time. I don't yet have a workaround for resolving the issue of the resolution of the data constructor for Tuple4 yet. I can make the entire export project available upon request but don't want to include it here except in its slimmed down form as it includes data which should not be made public.

### PR DESCRIPTION
**Pull request by aherrmann-da**
Closes #10438

Changes the encoding so that values of builtin types that require imports consistently use fully qualified names, e.g. `DA.Map.fromList`.

Tracks references to such modules that require imports, e.g. `DA.Map`. (The package-id is left empty in this case, as no corresponding `--package` flag is required).

Avoids imports of `DA.Types` due to tuples as these would be unused imports.

Adds unit tests.

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-script/export/src/main/scala/com/daml/script/export/TreeUtils.scala [hunk 1]
```diff
@@ -465,26 +468,59 @@ object TreeUtils {
     case Kind.Exercised(value) => valueRefs(value.getChoiceArgument.sum)
   }
 
+  /** All identifiers referenced by the given value that require a module import.
+    *
+    * Note, the package-id component of the identifier may be empty if there is no
+    * corresponding package-id available. E.g. DA.Time.Time incurred by Timestamp values.
```
Comment (cocreature) [inline daml-script/export/src/main/scala/com/daml/script/export/TreeUtils.scala:474]:
```suggestion
    * Note, the package-id component of the identifier may be empty for stable packages
       as those are imported via daml-stdlib/daml-prim. E.g. DA.Time.Time incurred by Timestamp values.
```

File: daml-script/export/src/main/scala/com/daml/script/export/TreeUtils.scala [hunk 2]
```diff
@@ -465,26 +468,59 @@ object TreeUtils {
...
+    */
   def valueRefs(v: Value.Sum): Set[Identifier] = v match {
     case Sum.Empty => Set()
     case Sum.Record(value) =>
-      Set(value.getRecordId).union(value.fields.foldMap(f => valueRefs(f.getValue.sum)))
+      val fieldRefs = value.fields.foldMap(f => valueRefs(f.getValue.sum))
+      if (isTupleId(value.getRecordId)) {
+        fieldRefs
+      } else {
+        Set(value.getRecordId).union(fieldRefs)
```
Comment (cocreature) [inline daml-script/export/src/main/scala/com/daml/script/export/TreeUtils.scala:483]:
```suggestion
        fieldRefs + value.getRecordId
```
feel free to ignore but maybe a bit clearer and probably slightly more efficient (I highly doubt that matters).

Comment (cocreature) [reply daml-script/export/src/main/scala/com/daml/script/export/TreeUtils.scala:483]: If you don’t like the operator there’s `.incl`.

**Review by cocreature — APPROVED** [review]
Thanks!

File: daml-script/export/src/main/scala/com/daml/script/export/TreeUtils.scala (hunk 2 above)
Comment (aherrmann-da) [reply daml-script/export/src/main/scala/com/daml/script/export/TreeUtils.scala]: Good point, this was copy-pasta from some of the other cases. I've adjusted them to use `+` consistently.
