### PR TITLE
LF: check contracts are consumed when found them in the cache

### LINKED ISSUE #11874: [BUG] Controllers & choice observers are evaluated before checking that contract has not been consumed
**Affected Daml version**
Everything up to 1.18.0 and currently also HEAD

**Bug description**
Currently, we first evaluate the controllers & choice observers before checking if a contract has not been consumed in the current transaction.
This is inconsistent with contracts that have been consumed in a prior transaction which check for activeness first. It also contradicts the LF spec.

The case where this matters is if your controllers or choice observers throw an exception. Currently you can catch that exception and do something else. If we did the activeness check first, you’d get an uncatchable inactiveness error.

So fixing this bug is breaking and will cause replays of old transactions to fail. However, the only case where this is an issue is if all of the following hold:
1. Your controllers or choice observers throw an exception.
2. You catch that exception.
3. And you exercised on a contract that has been consumed in the current transaction.

That combination seems sufficiently unlikely that breaking this even for old LF versions seems reasonable.

**To reproduce**

The Script below currently fails with the controller error
```
module Main where

import Daml.Script

template T
  with
    p : Party
  where
    signatory p
    choice FailController : ()
      controller (error "abc" : Party)
      do pure ()

template Helper
  with
    p : Party
  where
    signatory p
    choice ConsumeThenFail : ()
      with
        cid : ContractId T
      controller p
      do archive cid
         exercise cid FailController
         pure ()

test = do
  p <- allocateParty "p"
  cid <- submit p $ createCmd (T p)
  submit p $ createAndExerciseCmd (Helper p) (ConsumeThenFail cid)
```

**Expected behavior**
The script should fail with an inactiveness error

### PR DESCRIPTION
**Pull request by remyhaemmerle-da**
fixes #11874

CHANGELOG_BEGIN
CHANGELOG_END

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/main/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Include changelog additions in one or more commit message bodies between the `CHANGELOG_BEGIN` and `CHANGELOG_END` tags
- [ ] Normal production system change, include purpose of change in description
- [ ] If you mean to change the status of a component, please make sure you keep [the Component Status page](https://github.com/digital-asset/daml/blob/main/docs/source/support/component-statuses.rst) up to date.

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/transaction/PartialTransaction.scala [hunk 1]
```diff
@@ -517,11 +517,8 @@ private[speedy] case class PartialTransaction(
       byInterface,
       version,
     )
-    mustBeActive(
```
Comment (cocreature) [inline daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/transaction/PartialTransaction.scala:520]: afaict you are not actually adding a replacement for this. I assume that’s not necessary because we check this before calling this already. Do you think it would make sense to keep `mustBeActive` anyway (in both cases here) as an assertion that throws an internal error as a fail-safe?

File: daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltin.scala [hunk 2]
```diff
@@ -985,6 +985,9 @@ private[lf] object SBuiltin {
           coid,
           crash(s"Contract ${coid.coid} is missing from cache"),
         )
+      onLedger.ptx.consumedBy
```
Comment (cocreature) [inline daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltin.scala:988]: I think I don’t quite understand why this is the right place for this check. Shouldn’t we check this in `SBUFetch` instead of `SBUBeginExercise`? I’m actually not sure where we are checking it for fetches now given that you dropped `mustBeActive`.

Comment (remyhaemmerle-da) [reply daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltin.scala]: My mistake. We just need the one for fetch.

File: daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/transaction/PartialTransaction.scala (hunk 1 above)
Comment (remyhaemmerle-da) [reply daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/transaction/PartialTransaction.scala:520]: I am not very fan of checking things twice.
I give you a wrong sens of security, make the code more complicate than necessary, and also more difficult to understand (why this property is check twice and this once not).  

Not feeling strongly about that, thought. I let you  judge for it. 
Should I let `mustActive` (and throw an internal error) or should I drop it completely ?

Comment (cocreature) [reply daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/transaction/PartialTransaction.scala:520]: Checking twice is definitely a bad idea if you treat both of them as actual validations because then you’re just doing shotgun validation which never works. If you make a clear distinction between "this is the actual check" and "this is an assertion which checks something that should always hold" I think it can make sense and help at least during refactoring when you violate that assumption (e.g. imagine for whatever reason exercise no longer ends up going through SBUFetch afterwards).

So I’d add it but make it an internal error/assertion failure but your choice.

**Review by cocreature — APPROVED** [review]
Nice thank you!
