### PR TITLE
language: Check for different SDK versions when building pkg db

### LINKED ISSUE #2510: improve DAML `*.dar` package dependency handling
Dependency handling in DAML projects is currently very opaque.

Documentation
============
  - would be good to have a general explanation of dependency handling. i.e. currently it's manual; there is no automatic artifact fetching. Is there a plan to create an artifact repository (like maven-central for java)?
  - what is the syntax in daml.yaml (relative path? include `*.dar` suffix? include version number?)
  - and where to put the *.dar file (in a `lib/` subdir? in root dir?)

Error Messages
=============
 @robin-da @moritzkiefer-da explained that `dar` files are currently not compatible across DAML versions. Example error:
```
Compiling example to a DAR.
File:     daml/Main.daml
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message: 
  error type checking data type Main.AssetInstance:
  unknown data type:
  33eff689d79d36ff70855fea91cbacdf41e75d61d28b67809fcf9f6845b942d7:DA.Internal.Template:PreConsuming
Code: 
ERROR: Creation of DAR file failed.
```
The version the `dar` was built against can be checked by looking in the `META-INF` file inside the `*.dar` archive, against the version number in `daml.yaml`. Make the errors easier to understand.

   I also suggested to append the language version to package names, like in scala - it's rudimentary but serves to check versions are compatible. e.g. `cdm-daml-2.0.128_0.13.15.dar` instead of just `cdm-daml-2.0.128.dar`.

### PR DESCRIPTION
**Pull request by robin-da**
This fixes #2510. We check whether packages were compiled with different
SDK versions and emit an understandable error if so.

### Pull Request Checklist

- [ ] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [ ] Include appropriate tests
- [ ] Set a descriptive title and thorough description
- [ ] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [ ] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate
- [ ] Normal production system change, include purpose of change in description

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: compiler/damlc/lib/DA/Cli/Damlc.hs [hunk 1]
```diff
@@ -747,6 +757,18 @@ getEntry fp dar =
...
     findEntryByPath fp dar
 
+-- | Parse a manifest field.
+getManifestField :: Entry -> String -> IO String
+getManifestField manifest field =
+    mbErr ("Missing field in META-INF/MANIFEST.MD: " ++ field) $
+    headMay
+        [ value
+        | l <-
+              lines $
```
Comment (cocreature) [inline compiler/damlc/lib/DA/Cli/Damlc.hs]: Can we share this logic with the DAR reader? At the very least it would be good to add a comment on why we replace `\n ` as it took me a while to remember that this is for multiline fields.

Comment (robin-da) [reply compiler/damlc/lib/DA/Cli/Damlc.hs]: I moved the function to the dar reader. I think the dar reader itself might need some rewriting.
