### PR TITLE
Fix Maven calls in daml-assistant integration tests on Windows

### LINKED ISSUE #1127: Fix Maven calls in integration tests on Windows
The maven tests in the integration tests are currently disabled on Windows since I couldn’t get them to work so far. We should try to figure out what exactly is going wrong and then reenable them.

### PR DESCRIPTION
**Pull request by majcherm-da**
Fixes #1127

These are the issues I found on Windows:
- `Codec.Archive.Tar` had some issues unpacking the archive (adding extra `.` to some file path resulting file ot found problem while unpacking)
- `mvn.cmd` needs to be called on Windows instead of `mvn`
- `mvn.cmd` needs to be called using `shell` instead of `proc` (or `callCommand` instead of `callProcess`) as otherwise Windows' `%~dp0` used in the batch file (https://stackoverflow.com/questions/5034076/what-does-dp0-mean-and-how-does-it-work/10290765#10290765) points to incorrect path and causes `mvn.cmd` to miscalculate the `MAVEN_HOME` variable
- `cmd.exe` needs to be on `PATH` (required by `mvn.cmd`)

### Pull Request Checklist

- [x] Read and understand the [contribution guidelines](https://github.com/digital-asset/daml/blob/master/CONTRIBUTING.md)
- [x] Include appropriate tests
- [x] Set a descriptive title and thorough description
- [x] Add a reference to the [issue this PR will solve](https://github.com/digital-asset/daml/issues), if appropriate
- [x] Add a line to the [release notes](https://github.com/digital-asset/daml/blob/master/unreleased.rst), if appropriate

NOTE: CI is not automatically run on non-members pull-requests for security
reasons. The reviewer will have to comment with `/AzurePipelines run` to
trigger the build.

### CODE REVIEW

File: daml-assistant/integration-tests/src/Main.hs [hunk 1]
```diff
@@ -43,10 +44,14 @@ main =
     javaPath <- locateRunfiles "local_jdk/bin"
     mvnPath <- locateRunfiles "mvn_dev_env/bin"
     tarPath <- locateRunfiles "tar_dev_env/bin"
+    -- NOTE: `COMSPEC` env. variable on Windows points to cmd.exe, which is required to be present
+    -- on the PATH as mvn.cmd executes cmd.exe
+    mbComSpec <- getEnv "COMSPEC"
```
Comment (cocreature) [inline daml-assistant/integration-tests/src/Main.hs]: Oh that looks nice! I wonder if we can use this to avoid the horrible hacks where we call `bash.exe` since `shell` relies on `cmd.exe`.

File: daml-assistant/integration-tests/src/Main.hs [hunk 2]
```diff
@@ -367,6 +366,11 @@ damlInstallerName
     | isWindows = "daml.exe"
     | otherwise = "daml"
 
+mvn :: String
+mvn
+    | isWindows = "mvn.cmd"
```
Comment (cocreature) [inline daml-assistant/integration-tests/src/Main.hs]: I thought if you use `shell`, it will automatically pick `mvn.cmd`? Is that only the case if `mvn` does not exist?

Comment (majcherm-da) [reply daml-assistant/integration-tests/src/Main.hs]: You're right, thanks! Now it's just `mvn`

File: daml-assistant/integration-tests/src/Main.hs (hunk 1 above)
Comment (majcherm-da) [reply daml-assistant/integration-tests/src/Main.hs]: I got rid of it sometime back and I just pushed another commit with a change from `proc` to `shell` for `daml` invocations, which allowed to remove `daml` / `daml.cmd` switch.
