### PR TITLE
Fix Daml Studio for 3.3.x when DPM is installed and last used

### LINKED ISSUE #22398: Daml Studio 3.4.7 extension silently fails on Splice's SDK version 3.3.0-snapshot.20250502
# Affected Daml version

3.4.7

# Bug description

With the Daml Studio extension 3.4.7 one cannot get any feedback form the Daml language server when editing the Daml code from https://github.com/hyperledger-labs/splice

# To reproduce

1. clone https://github.com/hyperledger-labs/splice
2. start `daml studio`
3. check extension version in VS Code: it is 3.4.7
4. load `daml/splice-util/daml/Splice/Util.daml`
5. observe that Daml Extension Host gets activated but no hover is shown; `Daml Extension Host` output is empty

One can recover a working version using:

1. close VS Code
1. start `daml studio --replace=always`
2. load `daml/splice-util/daml/Splice/Util.daml`
3. observe type over and stuff working

# Expected behavior

language server support from the newest version on Splice's SDK version `3.3.0-snapshot.20250502`

### PR DESCRIPTION
**Pull request by samuel-williams-da**
Fixes #22398
Ticket has details of the bug in the comments

### CODE REVIEW

File: sdk/compiler/daml-extension/src/language_client.ts [hunk 1]
```diff
@@ -355,6 +355,26 @@ export class DamlLanguageClient {
...
+  ): Promise<[string, string | undefined]> {
+    const [command, isUsingDPM] =
+      DamlLanguageClient.findAssistantCommand(config);
+    const sdkVersion = isUsingDPM
+      ? await DamlLanguageClient.getSdkVersionDPM(command, rootPath)
+      : await DamlLanguageClient.getSdkVersionDamlAssistant(command, rootPath);
+
+    if (sdkVersion && sdkVersion != "0.0.0" && semver.lt(sdkVersion, "3.4.0")) {
+      const damlPath = DamlLanguageClient.findDamlCommand();
+      if (!damlPath) throw new Error("Failed to locate assistant.");
```
Comment (dylant-da) [inline sdk/compiler/daml-extension/src/language_client.ts]: I think this error could use a bit of clearing up:
```suggestion
      if (!damlPath) throw new Error("Failed to locate Daml assistant. A Daml assistant must be installed in order to use SDK versions <= 3.3.");
```

**Review by dylant-da — APPROVED** [review]
Looks good, thank you!
